IDPT-702 fix style RDDM
surfstudio/ReactiveDataDisplayManager pull request #123
Opened 2021-03-29 11:25 UTC by KorolevSoftware

## Что сделано?

- Добавил иконку приложению-примеру
- Добавил иконку в FoldableTableViewCell
- Изменил цвет Таб и Нав бара на цвет РДДМ
- Заменил плейсхолдер на РДДМ

## Зачем это сделано?

Для красоты, приятнее анализировать библиотеку

## На что обратить внимание?

- На обилие иконок
- На цвет стандартных элементов

## Как протестировать?

- Открыть/запустить пример

2021-03-29 11:29 UTC, KorolevSoftware commented on Example/ReactiveDataDisplayManager/Application/AppDelegate.swift
>          return true
Так нормально? Или переделать?

2021-03-29 12:48 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Application/AppDelegate.swift
>          return true
это ок

2021-03-29 13:50 UTC, NullIsOne requested changes
Иконка не к той ячейке добавлена
Нужно добавить на этих экранах
![Simulator Screen Shot - iPhone 12 - 2021-03-29 at 16 51 24](https://user-images.githubusercontent.com/28707156/112846247-e4ae2e00-90b6-11eb-9a99-8e39f6184d22.png)
![Simulator Screen Shot - iPhone 12 - 2021-03-29 at 16 51 27](https://user-images.githubusercontent.com/28707156/112846260-e7108800-90b6-11eb-951a-2ff564831411.png)

Заглушка в примерах работы с коллекцией не влазит. Надо заменить
![Simulator Screen Shot - iPhone 12 - 2021-03-29 at 17 44 45](https://user-images.githubusercontent.com/28707156/112846265-e841b500-90b6-11eb-9b21-f5bd29c7f6df.png)

И см. комментарии

2021-03-29 13:50 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/Views/Cells/FoldableTableViewCell/FoldableTableViewCell.swift
> +    @IBOutlet private weak var iconImageView: UIImageView!
Не эту ячейку)
В `MainTableViewController` и `MainCollectionViewController` надо заменить `TitleTableViewCell` на ячейку с иконкой и `accessoryType = .disclosureIndicator`  = скобочка >
А то они совсем не выглядят как развилочные экраны.

2021-03-29 13:50 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Utils/UIColorExtension.swift
> +    static let RDDMMainColor = UIColor(red: 0.906, green: 0.298, blue: 0.208, alpha: 1)
Цвет тоже можно положить в ассеты

2021-03-29 13:50 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Utils/NukeImagePrefetcher.swift
> +        ImageLoadingOptions.shared.failureImage = #imageLiteral(resourceName: "ReactiveLogoPlaceholder")
еще `ImageLoadingOptions.shared.placeholder` можно установить
Из того же ресурса или сделать его монохромным, чтобы незагруженное изображение от поломанного отличалось

2021-03-29 13:50 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Utils/NukeImagePrefetcher.swift
> +        ImageLoadingOptions.shared.failureImage = #imageLiteral(resourceName: "ReactiveLogoPlaceholder")
И наверное стоит вынести установку плейсхолдера из NukeImagePrefetcher чтобы устанавливалось по месту в конкретных ячейках.
Прикреплю скриншот,  где не подошла заглушка

2021-03-30 06:07 UTC, NullIsOne commented
И еще
В develop все скидываем
master только для релизов

2021-03-31 05:14 UTC, NullIsOne requested changes
еще немного доделать с плейсхолдером

2021-03-31 05:14 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Utils/NukeImagePrefetcher.swift
> +        ImageLoadingOptions.shared.failureImage = placeholder.withRenderingMode(.alwaysTemplate)
И это все равно установка общих свойств для всего Nuke)
На боевом проекте может быть ситуация когда это стрельнет. 
Например: 2 экрана с разными плейсхолдерами в навигационном стеке, при возврате с 2го на 1й не будет создаваться новый префетчер и на 1й экран попадут неправильные плейсхолдеры.

Люди будут смотреть на наш пример и скорее всего копировать его себе в проект, поэтому лучше сразу сделать правильно)

Подсказка: в ячейке `Nuke.loadImage` можно установить ImageLoadingOptions которые будут приоритетней для этого конкретного процесса загрузки.

2021-03-31 11:54 UTC, NullIsOne approved these changes

2021-03-31 11:55 UTC, merged