Feature/IDPT-706/Example for Compositional Layout
surfstudio/ReactiveDataDisplayManager pull request #124
Opened 2021-03-31 16:57 UTC by KorolevSoftware

## Что сделано?

- Пример с Compositional Layout
- Изменил Nurk prefetcher добавил контент мод (удобнее работать с плейсхолдерами). Были проблемы если ячейка низкая и вытянутая.

## Зачем это сделано?

Пример по работе с крайне полезным лайаутом, прям 10/10. Делать такую штуку руками (не используя Compositional) чрезвычайно неприятно.

## На что обратить внимание?

- на наличие сложных элементов/секций с разными ячейками
- верхний элемент снапится к центру экрана (помню делал это руками, а тут это 1 команда)

## Как протестировать?

- Пример на экране коллекций во вкладке "Collection with composition layout"

2021-03-31 17:19 UTC, KorolevSoftware commented on Example/ReactiveDataDisplayManager/Utils/NukeImagePrefetcher.swift
>                                  tintColors: tintOptions)
Вот тут надо было добавить контент вью. Сейчас была проблема с низкими вытянутыми ячейками, им ни один  плейсхолдер не подходит, заводить 3 плейсхолдер было бы странно.

2021-04-02 12:16 UTC, NullIsOne requested changes
1. Убрать лишнюю копию контроллера
2. Добавить коллекции возможность создания футера (отдельной задачей)

В целом круто, что лейауты так легко применяются поверх rddm, однако какой-то хелпер все-таки для них хочется запилить, ибо код громоздкий.
Может как-нибудь связать секцию, хэдеры и футеры и тип лейаута вместе. 
Что-то вроде `adapter.addSection(header: nil, footer: nil, layout: someLayout)` .. надо подумать

2021-04-02 12:16 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/CollectionCompositionalViewController/CollectionCompositionalViewController.swift
> +//  CollectionCompositionaViewController.swift
Дубль файл
Один из них надо удалить

2021-04-02 12:16 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Utils/NukeImagePrefetcher.swift
>                                  tintColors: tintOptions)
правильное решение

2021-04-02 12:16 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/CollectionCompositionalViewController/CollectionCompositionaViewController.swift
> +        addHeaderGenerator(with: "Grid section")
Можно добавить еще пример футера.
Вот для них поидее нужна будет небольшая доработка внутри rddm. От `CollectionHeaderGenerator` новый протокол для генераторов будет отличаться только методом регистрации.
Сделаешь?

2021-04-02 16:28 UTC, KorolevSoftware commented on Example/ReactiveDataDisplayManager/Collection/CollectionCompositionalViewController/CollectionCompositionalViewController.swift
> +//  CollectionCompositionaViewController.swift
Удалил. Гадкий ХКод дублирует файлы при переименовании.

2021-04-05 07:57 UTC, NullIsOne approved these changes

2021-04-05 07:58 UTC, merged