Feature/IDPT-704/StackView
surfstudio/ReactiveDataDisplayManager pull request #125
Opened 2021-04-05 08:23 UTC by KorolevSoftware

## Что сделано?

- Лендинг используя StackView
- Разворачивающийся StackView
- Отдельный экран для примеров со StackView
- Исправлен баг в AllPluginsTableViewController, теперь корректно печатает в консоль

## Зачем это сделано?

Лендинг через StackView выглядит крайне интересно, нет необходимости создавать ячейку для коллекций, но возможно не лучший выбор при большом количестве повторяющихся ячеек.

Разворачивающийся StckView удобен для создания чего-то на подобии комментариев. Если нужно спрятать что-то большое но при этом показать малую часть, то это ваш выбор! 
 
## На что обратить внимание?

- Новый экран (с примерами)
- Пример с разворачивающимся StackView
- Фикс бага

## Как протестировать?

- Экран StackView там все новые прмеры
- Экран Tabe в примере all plugins корректно печатает в консоль

2021-04-12 13:26 UTC, NullIsOne requested changes
Целью примера было использовать адаптер для стека по-максимуму
Надо допилить чутка)

2021-04-12 13:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +final class LandingStackView: UIViewController {
Всё-таки `LandingStackViewController`

2021-04-12 13:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/ButtonsCellGenerator.swift
> +        view.addArrangedSubview(buttonOne)
Так и в обычной ячейке можно)
В примере лендинга хотелось бы показать адаптер в адаптере.  То есть этот генератор может создать в себе адаптер в который добавлено 2 генератора кнопок.
Дубликаты стилизации кнопки исчезнут и будет хорошо.

2021-04-12 13:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Views/View/UnrollCellStackView.swift
> +        mainStack.addArrangedSubview(bigTextLabel)
Здесь тоже через адаптер бы добавлять

2021-04-15 13:07 UTC, eysnerSurf reviewed
Отписал несколько предложений

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/TextStackCellGenerator.swift
> +}
1) Тут кажется можно уровнь доступа понизить до private, тк эти свойства не меняются извне и сразу сделать их константами
2) проще сразу передавать шрифт, чем конфигурировать его отдельными параметрами. Так мы будем сразу настраивать вес и размер, пример использования добавлю в контролл
3) Можно вообще модель сразу передавать, но возможно это и лишнее тут))

```suggestion
final class TextStackCellGenerator: StackCellGenerator {

    // MARK: - Private Properties

    private let title: String
    private let textAlignment: NSTextAlignment
    private let font: UIFont
    private let numberOfLines: Int

    // MARK: - Initialization

    init(title: String, font: UIFont, textAlignment: NSTextAlignment = .left, numberOfLines: Int = .zero) {
        self.title = title
        self.font = font
        self.textAlignment = textAlignment
        self.numberOfLines = numberOfLines
    }

}

// MARK: - ViewBuilder

extension TextStackCellGenerator: ViewBuilder {

    func build(view: UILabel) {
        view.numberOfLines = numberOfLines
        view.text = title
        view.textAlignment = textAlignment
        view.font = font
    }

}
```

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +        let description = TextStackCellGenerator.init(title: sampleText, fontSize: 30)
Тут опечатка в `title` была и предлагаю везде конструктор одинаково вызывать, избежим сразу лишнего кода `.init`. Заодно использовал обновленный инициализатор, см ниже

```suggestion
        let title = TextStackCellGenerator(title: "Title text", font: .systemFont(ofSize: 43, weight: .bold))
        let description = TextStackCellGenerator(title: sampleText, font: .systemFont(ofSize: 30))
```

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +        adapter.addCellGenerator(tite)
Правка опечатки

```suggestion
        adapter.addCellGenerator(title)
```

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +                                               right: Constants.padding)
Правка из предложения вынести в константы

```suggestion
        stackView.layoutMargins = Constants.layoutMargins
```

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +    }
Предлагаю отступы тоже вынести в константы сразу

```suggestion
        static let layoutMargins = UIEdgeInsets(top: padding, left: padding, bottom: padding, right: padding)
    }
```

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/ButtonsCellGenerator.swift
> +    let buttonTwoTapped: () -> Void
Здесь замыкания лучше сразу сделать приватными

```suggestion
    // MARK: - Private Properties

    private let buttonOneTapped: () -> Void
    private let buttonTwoTapped: () -> Void
```

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/ButtonsCellGenerator.swift
> +}
1) Обработку событий кнопок тоже стоит инкапсулировать
2) атрибут `@objc ` можно распространить сразу на все расширение

```suggestion
@objc
private extension ButtonsCellGenerator {

    func buttonOneTappedAction() {
        buttonOneTapped()
    }

    func buttonTwoTappedAction() {
        buttonTwoTapped()
    }

}
```

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/UnrollStackCellGenerator.swift
> +    var bigText: String
Здесь аналогично, скрываем private и константа

```suggestion
    // MARK: - Private Properties

    private let bigText: String
```

2021-04-15 13:07 UTC, ghost commented on Example/ReactiveDataDisplayManager/Stack/Views/View/UnrollCellStackView.swift
> +    // MARK: - UITableViewCell
Mark не та затисалась

```suggestion
    // MARK: - Initialization
```

2021-04-15 13:07 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +// MARK: - Configuration
extension с конфигурацией может быть лучше стоит передвинуть перед приватными методами?

2021-05-27 09:31 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/TextStackCellGenerator.swift
> +}
Все переделано

2021-05-27 09:31 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +        let description = TextStackCellGenerator.init(title: sampleText, fontSize: 30)
Поправлено

2021-05-27 09:31 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +        adapter.addCellGenerator(tite)
Поправлено

2021-05-27 09:32 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +                                               right: Constants.padding)
В константах

2021-05-27 09:32 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +    }
Done

2021-05-27 09:32 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/ButtonsCellGenerator.swift
> +    let buttonTwoTapped: () -> Void
переделано

2021-05-27 09:32 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/ButtonsCellGenerator.swift
> +}
перенесено в ButtonStackCellGenerator

2021-05-27 09:32 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Views/Generators/UnrollStackCellGenerator.swift
> +    var bigText: String
fixed

2021-05-27 09:33 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Views/View/UnrollCellStackView.swift
> +    // MARK: - UITableViewCell
исправлено

2021-05-27 09:34 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Stack/Landing/LandingStackView.swift
> +// MARK: - Configuration
унесено в один extension

2021-05-27 09:40 UTC, NullIsOne commented
Дима с нами больше не работает, поэтому доделал ПР за него.

В результате эксперимента 
1.  Генераторы для элементарных ячеек можно попробовать затянуть в библиотеку. Проблема с конфигурацией. Она должна быть максимально полной. Все свойства в модельке не описать. Нужно стилизовать вьюху ячейки через отдельную сущность.
2. Для сочетания контента можно использовать InnerStackCellGenerator. Надо доработать сборку генераторов. Наверное на уровне менеджера построение стека должно отличаться. Надо стремиться к api похожему на Stack.

Эти моменты выльются в задачки для следующей итерации.

2021-05-27 14:38 UTC, KorolevSoftware commented
Я забыл про пр. Простите.

2021-06-15 06:03 UTC, eysnerSurf approved these changes

2021-06-15 10:27 UTC, merged