IDPT-802 RDDM. Примеры использования кастомных лейаутов
surfstudio/ReactiveDataDisplayManager pull request #146
Opened 2021-11-16 06:46 UTC by kombatkos

## Что сделано?

- Добавил кастомные layouts в папку Collection/Layouts
- Доработал FittingCompressedSizeCollectionViewLayout (теперь привязка контента доступна по 2м сторонам left/ right)
- Для каждого кастового layout сконфигурировал экран с примером использования
- Добавил хедер для общей таблицы "Layouts expample"

## Зачем это сделано?

Это нужно для того чтобы в проектах не тратить время на написание кастового layout для collectionView

## Как протестировать?

- Тапнуть в примере на таб <Collections>
- Тапнуть на <Carousel collection view layout>
- Тапнуть на <Fitting compressed size collection>
- Тапнуть на <Aligned collection layout>
- Тапнуть на <Dynamic height ViewController>

2021-11-16 07:19 UTC, NullIsOne requested changes
Чтобы лейауты можно было использовать, их надо сделать Public и вынести в параметры, все что можно настроить.

Ну и по мелочи см. комменты.

2021-11-16 07:19 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Layouts/AlignedCollectionViewFlowLayout.swift
> +class AlignedCollectionViewFlowLayout: UICollectionViewFlowLayout {
Нужно сделать public и final
Иначе клиенты библиотеки не смогут использовать.

И описания не хватает для доки.

2021-11-16 07:19 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Layouts/AlignedCollectionViewFlowLayout.swift
> +    init(aligment: Aligment) {
И инит обязательно public

2021-11-16 07:19 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Layouts/AlignedCollectionViewFlowLayout.swift
> +    required init?(coder: NSCoder) {
```suggestion
    @available(*, unavailable)
    required init?(coder: NSCoder) {
```

2021-11-16 07:19 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Layouts/FittingCompressedSizeCollectionViewLayout.swift
> +final class FittingCompressedSizeCollectionViewLayout: UICollectionViewLayout {
Что-то странно пример выглядит у меня
Xcode 13, iOs 15, iPhone 12 Pro Max
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-11-16 at 11 03 08](https://user-images.githubusercontent.com/28707156/141937484-4c6cb929-0594-4ede-9c62-24cf4151fd71.png)

Он точно работает?

2021-11-16 07:19 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Layouts/FittingCompressedSizeCollectionViewLayout.swift
> +    private var contentInsets: UIEdgeInsets {
Это надо публичным или open сделать.
Как и interitemSpacing и lineSpacing

Или хотябы сеттер в инит добавить

2021-11-16 07:19 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/DifferentHeightViewController/DifferentHeightViewController.swift
> +class DifferentHeightViewController: UIViewController {
Не используется?

2021-11-16 07:19 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Views/Cells/DynamicHeightViewCell/DynamicHeightTableViewCell.swift
> +        return [.gray, .blue, .red, .yellow, .green]
Давай тут рандомно количество сделаем?
Чтобы нагляднее был результат?

2021-11-16 07:19 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Views/Cells/DynamicHeightViewCell/DynamicHeightTableViewCell.swift
> +        return makeModels().map { BaseCollectionCellGenerator<RectangleColorCollectionViewCell>(with: $0) }
`RectangleColorCollectionViewCell.rddm.baseBuilder(with: $0)`

по новому

2021-11-16 17:48 UTC, NullIsOne requested changes

2021-11-16 17:48 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Layouts/DynamicHeightCollectionView.swift
> +/// Does not work in ios 15
??
Норм работает же
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-11-16 at 21 44 26](https://user-images.githubusercontent.com/28707156/142037932-8a1b5474-f774-42fb-8b72-52df20b6c75d.png)

Что-то тут перепутали)
Если пометка относилась к проблеме с `FittingCompressedSizeCollectionViewLayout`, то правильней поставить ее через `@available` 

Однако лучше просто исключить нестабильный пример с "FittingSize"
(я немного посидел и не получилось сходу решить ту проблему)

2021-11-17 05:34 UTC, kombatkos commented on Example/ReactiveDataDisplayManager/Collection/Layouts/FittingCompressedSizeCollectionViewLayout.swift
> +final class FittingCompressedSizeCollectionViewLayout: UICollectionViewLayout {
Пример удален

2021-11-17 06:21 UTC, NullIsOne approved these changes

2021-11-17 06:21 UTC, merged