Idpt 737 RDDM. Плагин фокусировки для tvOs
surfstudio/ReactiveDataDisplayManager pull request #148
Opened 2021-11-25 09:55 UTC by kombatkos

## Что сделано?

- Добавлен focusable плагин для выделения ячейки в tvOS
- Добавлена модель конфигурации плагина
- Добавлена стратегия конфигурации плагина

## Зачем это сделано?

- Для кастомизации фокусировки в tvOS

## На что обратить внимание?

- Дефолтную анимацию убрать нет возможности, поэтому мы накладываем свою анимацию поверх дефолтной

## Как протестировать?

- Запустить tvOS
- Зайти в первые две галлереи
- В первой будет Коллекция с CompositionLayout и выделение ячейки красной тенью
- Во второй будет Коллекция с FlowLayout, выделение ячейки синей тенью и дополнительной анимацией

2021-11-30 06:48 UTC, NullIsOne requested changes
Круто получилось, но надо доработать немного (см замечания)

Плюс замечания от линтера поправить.
И исправить зависимость таргета с tvOS от SurfUtils
>[!] The platform of the target `ReactiveDataDisplayManagerExample_tvOS` (tvOS 13.0) is not compatible with `SurfUtils/UIImageExtensions (11.0.0)`, which does not support `tvOS`.

Либо убрать из podfile ее (все равно нужное расширение скопировано)
Либо законтрибьютить в SurfUtils. Добавив поддержку tvOS (может не взлететь, появится много  исключающих условий по платформам типа `#if iOS`

2021-11-30 06:48 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy.swift
> +                    collectionView: UICollectionView?,
Надо вынести тип коллекции через  `assosiatedType` протокола

Пример есть у `DataDisplayManager`   и его реализаций

```
public protocol DataDisplayManager: AnyObject {

    // MARK: - Associatedtypes

    associatedtype CollectionType
```

Так мы исключим ситуацию, когда метод используется с пустыми collectionView и tableView одновременно.

2021-11-30 06:48 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy.swift
> +    func didFocused(previusView: UIView?, nextView: UIView?,
nextView можно перенести на следующую строчку

2021-11-30 06:48 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy.swift
> +        nextView?.layer.shadowRadius = shadowModel?.radius ?? 10.0
Внутри shadowModel есть значения по-умолчанию.
Можем не дублировать их тут?

Если устанавливать радиус, opacity и offset только при наличии модели это будет валидно? Как считаешь?

2021-11-30 06:48 UTC, NullIsOne commented on Source/Models/FocusedPlaginModel.swift
> +    let color: UIColor
Мне кажется или цвет из модели не используется?

В стратегии используется цвет из `FocusStrategy.shadow`

2021-11-30 06:48 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy.swift
> +protocol StrategyFocusable{
```suggestion
protocol StrategyFocusable {
```

2021-11-30 06:48 UTC, NullIsOne commented on Source/Collection/Delegate/BaseCollectionDelegate.swift
> +        #endif
Тут можно `#elseif os(tvOS)` вместо двух строк

2021-11-30 07:07 UTC, kombatkos commented on Source/Models/FocusedPlaginModel.swift
> +    let color: UIColor
Если помимо тени мы будем задавать другие кастомизации, то используем 
**case byModel(model: FocusedPlaginModel)** - вот тут цвет для тени используется по модели
<img width="516" alt="Снимок экрана 2021-11-30 в 11 07 32" src="https://user-images.githubusercontent.com/56546669/144001528-bf76ba38-619d-4337-86f4-3eb17a98b0bc.png">

2021-11-30 13:06 UTC, NullIsOne requested changes
Еще немного замечаний.

2021-11-30 13:06 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusablePlugin.swift
> +    static func focusable(by: FocusStrategy<UITableView>? = nil) -> TableFocusablePlugin {
```suggestion
    static func focusable(by strategy: FocusStrategy<UITableView>? = nil) -> TableFocusablePlugin {
            .init(strategyFocusable: strategy)
```

2021-11-30 13:06 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy.swift
> +            (collection as? UITableView)?.scrollToRow(at: index, at: .middle, animated: true)
Избавиться бы от этих анврапов
И таблицу к каждому align вызывать.

Например так можно

```
private extension FocusStrategy where CollectionType == UITableView {

    // Configure scroll
    func setScroll(align: FocusableAlign?, index: IndexPath?, collection: CollectionType) {
        guard let index = index, let align = align else {
            return
        }

        let position: UITableView.ScrollPosition = {
            switch align {
            case .left:
                return .top
            case .right:
                return .bottom
            case .center:
                return .middle
            }
        }()

        collection.scrollToRow(at: index, at: position, animated: true)

    }

}
```

2021-11-30 13:06 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy.swift
> +              let table = table as? UITableView,
Реализацию этого для таблицы тоже лучше вынести отдельно как предложено для скролла.
У коллекции получается не будет установки `focusStyle`

2021-11-30 13:06 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy.swift
> +            (collection as? UITableView)?.scrollToRow(at: index, at: .middle, animated: true)
И нужно подумать как можно переименовать `FocusableAlign` чтобы было ясно, что у таблицы left=top, а right = bottom

Может `start/center/end` больше подойдут?

2021-11-30 14:00 UTC, kombatkos commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy.swift
> +            (collection as? UITableView)?.scrollToRow(at: index, at: .middle, animated: true)
У нас не только UITableView, еще и для UICollectionView придется добавлять такой же position, и потом я добавил функциональности по фокусировке со скроллом для таблицы (верх, низ) до этого была только по центру. Добавил фокусировку со скроллом для коллекции в любую сторону, центр у коллекции тоже настраивается (вертикально/горизонтально) по умолчанию - оба этих параметра

2021-12-02 05:54 UTC, NullIsOne requested changes
Функционально и по стилю все в порядке.
Осталось несколько моментов.

2021-12-02 05:54 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/CompositFocusableTableStrategy.swift
> +    private var strategys: [FocusableStrategy<CollectionType>]
Все гениальное просто)

Это также позволит пользователям через композитную стратегию добавлять свои кастомные.
Здорово получилось

2021-12-02 05:54 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/CompositFocusableTableStrategy.swift
> +public final class CompositFocusableStrategy<CollectionType>: FocusableStrategy<CollectionType> {
```suggestion
public final class CompositeFocusableStrategy<CollectionType>: FocusableStrategy<CollectionType> {
```
Composit - композит
Composite - композитный


Прилагательным правильнее будет)

2021-12-02 05:54 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/FocusableStrategy.swift
> +open class FocusableStrategy<CollectionType> {
Чтобы позволить делать кастомные стратегии, надо 

- пустой публичный init добавить
- метод пометить open

Проверить где-нибудь в контроллере Example проекта, создав кастомную стратегию.

2021-12-02 05:54 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/FocusableStrategy.swift
> +        preconditionFailure("Strategy method does nothing")
```suggestion
        preconditionFailure("\(#function) must be overriden in child")
```

2021-12-02 05:54 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/FocusablePlugin/FocusableStrategy/Strategy/CompositFocusableTableStrategy.swift
> +public final class CompositFocusableStrategy<CollectionType>: FocusableStrategy<CollectionType> {
Документации не хватает.
Напиши, что в этой стратегии можно сочетать несколько стратегий

2021-12-02 05:54 UTC, NullIsOne commented on Source/Table/TableBuilder.swift
> +        #if os(tvOS)
Финальным штрихом еще поправим эти `#if os(tvOS)`

Они много где стоят, но при этом наш плагин и стратегии не помечены `#if os(tvOS)` значит будут включены в оба таргета библиотеки.
То есть они доступны для обеих платформ.

Человек может установить этот плагин, используя  `Builder.add(plugin: )` но по факту плагин не поставится так как у нас установка закрыта условием.

При этом метод 
```
- (void)collectionView:(UICollectionView *)collectionView didUpdateFocusInContext:(UICollectionViewFocusUpdateContext *)context withAnimationCoordinator:(UIFocusAnimationCoordinator *)coordinator API_AVAILABLE(ios(9.0));
```
доступен начиная с iOs 9. И поддерживается со старта  tvOs.

В общем надо проверить, имеет ли этот плагин какой-то эффект на платформе iOS.

- имеет - убираем `#if os(tvOS)` проверки внутри билдеров
- не имеет - закрываем исходники плагина, моделек и стратегий  проверками ` #if os(tvOS)`

2021-12-02 10:13 UTC, NullIsOne approved these changes

2021-12-02 10:15 UTC, merged