IDPT-854 Рефакторинг DiffableItem
surfstudio/ReactiveDataDisplayManager pull request #160
Opened 2022-02-24 16:40 UTC by Ikeret

## Что сделано?

- Сделан рефактор DiffableItem, для того, чтобы ориентироваться на hashValue модели в DiffableDataSource
- Добавлен протокол DiffableModel, реализуемый в моделях для генератора для упрощения использования DiffableDataSource (базовый генератор реализует DiffableItemSource, если модель является DiffableModel). Таким образом, не требуется создавать отдельные генераторы ячеек для DiffableItemSource
- Расширены инициализаторы пустых хедеров/футеров коллекций и таблиц для исключения изменения хэша в DiffableDataSource, приводившего к обновлению всех ячеек в секции

## На что обратить внимание?

- Удалена система с использованием id в DiffableItem, инициализатор принимает Hashable, что позволяет использовать String и DiffableModel. В принципе ее можно вернуть, но суть идеи заключалась в том, чтобы избавить от создания лишних генераторов ячеек.
- Протокол DiffableModel был добавлен для того, чтобы в модели не приходилось реализовывать Equatable (реализация внутри экстеншена со сравнением hashValue)

2022-02-24 18:46 UTC, NullIsOne requested changes
Example не собирается, так как не адаптирован. На чем тестировалась работа Diffable?

> чтобы избавить от создания лишних генераторов ячеек

Лишних не бывает. Иногда они необходимы.

2022-02-24 18:46 UTC, NullIsOne commented on Source/Collection/Generators/BaseCollectionCellGenerator.swift
> +extension BaseCollectionCellGenerator: DiffableItemSource where Cell.Model: DiffableModel {
`where Cell: UICollectionViewCell, Cell.Model: Equatable & IdentifiableProtocol`

И мы малой кровью можем добавить diffableItem в базовый.

2022-02-24 18:46 UTC, NullIsOne commented on Source/Collection/Generators/BaseCollectionCellGenerator.swift
> +extension BaseCollectionCellGenerator: DiffableItemSource where Cell.Model: DiffableModel {
А вообще не проблема и такой создать

```
import Foundation
import ReactiveDataDisplayManager

class DiffableCollectionCellGenerator<Cell: ConfigurableItem>: BaseCollectionCellGenerator<Cell>, DiffableItemSource where Cell: UICollectionViewCell, Cell.Model: Equatable & IdentifiableProtocol {


    var diffableItem: DiffableItem {
        .init(id: model.id, state: .init(model))
    }

    init(with model: Cell.Model, registerType: CellRegisterType = .nib) {
        super.init(with: model, registerType: registerType)
    }

}

extension StaticDataDisplayWrapper where Base: UICollectionViewCell & ConfigurableItem, Base.Model: Equatable & IdentifiableProtocol {

    func diffable(
        with model: Base.Model,
        and registerType: CellRegisterType = .nib
    ) -> DiffableCollectionCellGenerator<Base> {
        .init(with: model, registerType: registerType)
    }

}

```

Использовать `Cell.rddm.diffable(...`

2022-02-24 18:46 UTC, NullIsOne commented on Source/Collection/Generators/EmptyCollectionFooterGenarator.swift
> +    public init(uniqueId: String) {
Дублирующий конструктор это здорово придумано.
Со старым вариантом тоже сработает.

2022-02-24 18:46 UTC, NullIsOne commented on Source/Protocols/Plugins/Generators/DiffableItem.swift
> +        return _hashValue == object._hashValue
Почему так нельзя расписал в проекте.

Тут только добавлю, что ошибочной реализации можно было бы избежать если бы отладку проводили на Example проекте

2022-02-25 12:07 UTC, Ikeret commented on Source/Protocols/Plugins/Generators/DiffableItem.swift
> +        return _hashValue == object._hashValue
Ок, отменю все изменения в DiffableItem файле

2022-02-25 14:13 UTC, Ikeret commented
Добавил DiffableCellGenerator, добавил расширение для создания diffable генераторов с id и без id для моделей IdOwner

2022-02-25 17:24 UTC, Ikeret commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +    var id: String { get }
есть предложение использовать свифтовый Identifierable, в котором параметр id - Hashable. Причина: не во всех моделях id имеет тип String, приходится конвертировать

2022-02-25 18:26 UTC, NullIsOne requested changes
- Определиться с способом передачи id.
- Добавить и DiffableTableCellGenerator.
- Распространить на Example проект. (заменить используемые там генераторы встроенным)
- Починить  сборку SPMExample

![Снимок экрана 2022-02-25 в 22 16 18](https://user-images.githubusercontent.com/28707156/155768033-40133024-8737-46a3-8a95-d4a6ce6b3db9.png)

2022-02-25 18:26 UTC, NullIsOne commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +    var id: String { get }
Swift не даст так просто это сделать, потому что это неопределенный протокол.
Он будет просить конкретизировать тип в `where Base.Model: Equatable & Identifierable`

Может прокатить фокус с протоколом содержащим функцию.

```
infix operator ~~ : ComparisonPrecedence
/// основа
public protocol IsIdentifiable: Equatable {
    static func ~~ (a: Self, b: Self) -> Bool
}

// реализация со строковым Id
public extension IsIdentifiable where Self: IdOwner {
    static func ~~ (a: Self, b: Self) -> Bool {
        return a.id == b.id
    }
}

// реализация с сравнением хэша
public extension IsIdentifiable where Self: Hashable {
    static func ~~ (a: Self, b: Self) -> Bool {
        return a.hashValue == b.hashValue
    }
}
```

2022-02-25 18:26 UTC, NullIsOne commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +extension StaticDataDisplayWrapper where Base: UICollectionViewCell & ConfigurableItem, Base.Model: Equatable & IdOwner {
Надо выбрать один подход. 

1. Делать id частью модели
2. Не делать

Я не против 2го варианта)
Тогда и IdOwner не нужен. В модели остается лишь представление ячейки.

2022-02-25 18:26 UTC, NullIsOne commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +public class DiffableCollectionCellGenerator<Cell: ConfigurableItem & UICollectionViewCell>: BaseCollectionCellGenerator<Cell>,
`open`

Чтобы можно было наследоваться от него когда понадобится на проекте добавить кастомный генератор с сохранением стейта.

2022-02-25 18:32 UTC, Ikeret commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +extension StaticDataDisplayWrapper where Base: UICollectionViewCell & ConfigurableItem, Base.Model: Equatable & IdOwner {
Каждый из подходов не покрывает все кейсы использования:
 1) Есть ячейки без id, но которые имею модель, т.е. не основаны на сущности с сервера
2) В генераторе не всегда может быть доступ к модели/entity и доступ к id

2022-02-25 18:32 UTC, Ikeret commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +public class DiffableCollectionCellGenerator<Cell: ConfigurableItem & UICollectionViewCell>: BaseCollectionCellGenerator<Cell>,
Ок

2022-02-25 18:40 UTC, NullIsOne commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +extension StaticDataDisplayWrapper where Base: UICollectionViewCell & ConfigurableItem, Base.Model: Equatable & IdOwner {
> Есть ячейки без id, но которые имею модель, т.е. не основаны на сущности с сервера

Согласен. Им больше подходит вариант без IdOwner.

> В генераторе не всегда может быть доступ к модели/entity и доступ к id

А вот здесь не совсем понимаю.
Имеешь ввиду ситуацию на нашем проекте, когда в VM (адаптере) создается модель ячейки, а генератор создается уже в VC?

Убедил. 
Уж лучше сразу иметь доступ к хитрому конструктору извлекающему id из модели, чем то же самое проворачивать ручками.

Ок. Оба способа имеют свои причины для существования.

2022-02-25 18:42 UTC, Ikeret commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +extension StaticDataDisplayWrapper where Base: UICollectionViewCell & ConfigurableItem, Base.Model: Equatable & IdOwner {
> Имеешь ввиду ситуацию на нашем проекте, когда в VM (адаптере) создается модель ячейки, а генератор создается уже в VC?

Да, чтобы не нужно было доставать id из вью модели. В любом случае SDK оставляет гибкость)

2022-02-25 19:20 UTC, Ikeret commented on Source/Collection/Generators/DiffableCollectionCellGenerator.swift
> +    var id: String { get }
Реализовал IdOwner с полем AnyHashable, который может принимать любое Hashable значение, которое потом используем в качестве id. Подписал пустые генераторы хедеров/футеров, а также diffable генераторы ячеек на этот же протокол

2022-02-28 12:14 UTC, Ikeret commented
- Реализовал IdOwner с полем AnyHashable, который может принимать любое Hashable значение, которое потом используем в качестве id. Подписал пустые генераторы хедеров/футеров, а также diffable генераторы ячеек на этот же протокол
- Обновил реализацию Diffable/DifferenceKit в Example проекте для таблиц и коллекций

2022-02-28 12:34 UTC, NullIsOne approved these changes

2022-02-28 12:34 UTC, merged