IDPT-855 fix clear methods and refactor comments
surfstudio/ReactiveDataDisplayManager pull request #161
Opened 2022-02-24 17:21 UTC by Ikeret

## Что сделано?

- Исправлен метод очистки генераторов ячеек. Приведен в соотвествие с остальными методами (очистка ячеек и секций)
- Исправлено описание методов очистки хедеров и футеров коллекций

2022-02-24 18:32 UTC, NullIsOne requested changes
Немного доделать

2022-02-24 18:32 UTC, NullIsOne commented on Source/Protocols/FooterDataDisplayManager.swift
> +    /// Replaces all footer generators with `EmptyCollectionFooterGenerator`
В этом нет смысла.
Методы остались с предыдущей версии clearFooterGenerators и clearHeaderGenerators не нужны после переезда с generators на sections

В версии 8.0 удаляем их смело

2022-02-24 18:32 UTC, NullIsOne commented on Source/Collection/Manager/BaseCollectionManager.swift
> +        sections.removeAll()
Продублируй пожалуйста и для таблицы

2022-02-24 18:32 UTC, NullIsOne commented on Source/Protocols/FooterDataDisplayManager.swift
> +    /// Replaces all footer generators with `EmptyCollectionFooterGenerator`
И не забудь в обоих example проектах тоже обновить

2022-02-25 15:08 UTC, Ikeret commented on Source/Collection/Manager/BaseCollectionManager.swift
> +        sections.removeAll()
В таблице уже так было

2022-02-25 15:09 UTC, Ikeret commented on Source/Protocols/FooterDataDisplayManager.swift
> +    /// Replaces all footer generators with `EmptyCollectionFooterGenerator`
Удалил в тестах, в ios example

2022-02-25 17:56 UTC, NullIsOne approved these changes

2022-02-25 17:56 UTC, merged