Fix unit tests and add sourcery
surfstudio/ReactiveDataDisplayManager pull request #167
Opened 2022-05-19 20:24 UTC by NullIsOne

## Что сделано?

- Поправлен отключенный таргет юнит-тестов в конфигурации проекта библиотеки
- Добавлена утилита Sourcery для упрощения генерации моков
- Оптимизирован makefile и инициализация
- ...

## Зачем это сделано?

Чтобы проще писать unit-тесты и повысить покрытие библиотеки.

## На что обратить внимание?

- Sourcery будет генерить моки при каждом билде unit-test таргета.
-  К сожалению утилита не может сгенерировать корректный код для генерик-протоколов, функций или свойств, а их у нас много. Можно подумать над расширением шаблона. Это немного ограничит количество кейсов для тестов, но в целом не будет помехой.
- ...

## Как протестировать?

- Выполнить `make init` для установки новых зависимостей
- Выполнить `make tests platform=iOS` для перегенерации моков и прогона тестов
или
- Открыть проект ReactiveDataDisplayManager, запустить тесты вручную и поиграться с расстановкой аннотаций `// sourcery: AutoMockable`

2022-05-23 09:45 UTC, paradi2e commented
![image](https://user-images.githubusercontent.com/47536762/169792180-23954e50-2244-48ca-ad15-c72ddaf66364.png)
на m1 ошибка с архитектурой

2022-05-23 09:48 UTC, paradi2e requested changes

2022-05-23 09:48 UTC, paradi2e commented on Makefile
> +updte_version:
тут буквы не хватает (

2022-05-24 18:33 UTC, NullIsOne commented on Makefile
> +updte_version:
исправлено

2022-05-24 18:34 UTC, NullIsOne commented
>на m1 ошибка с архитектурой

зафиксировал архитектуру, чтобы билдилось с одной и тестилось с ней же

2022-05-25 05:57 UTC, merged