IDPT-940 Add check for selectable generator
surfstudio/ReactiveDataDisplayManager pull request #170
Opened 2022-06-07 10:08 UTC by kombatkos

## Что сделано?

- Добавил описание к документации евентов
- Написал метод проверки на наличие didSelectEvent или didDeselectEvent в генераторе
- Добавил метод проверки во все Менеджеры как для коллекции, так и для таблицы (метод вызывается перед добавлением/вставкой генератора)

## Зачем это сделано?

Не сразу понятно что к билдеру нужно подключить .selectable плагин так как генераторы базово имеют ивенты didSelectEvent и didDeselectEvent. Теперь сделано так что если мы подключили любой из ивентов, но забыли подключить selectable плагин, то метод добавления генераторов выдаст assertionFailure с сообщением о том что нужно подключить плагин.

## На что обратить внимание?

- Пришлось открыть приватное свойство plugins в PluginCollection

## Как протестировать?

- добавить didSelectEvent к генератору таблицы или коллекции не добавляя плагин selectable
- запустить
- зайти на измененный экран
- выйдет ошибка с описанием
- добавить плагин .selectable()
- перезапустить
- зайти на измененный экран
- ошибки не будет!

2022-06-08 06:24 UTC, NullIsOne requested changes

2022-06-08 06:24 UTC, NullIsOne commented on Source/Protocols/Plugins/PluginAction/PluginCollection.swift
> +    var plugins = [Plugin]()
```suggestion
    private(set) var plugins = [Plugin]()
```

2022-06-08 06:24 UTC, NullIsOne commented on Source/Collection/Manager/BaseCollectionManager.swift
> +        checkSelectablePlugin(for: generator)
Похоже мы повторяем ошибку из-за которой пришлось вводить `Registrator` в #162 
Суть проблемы в том, что добавление генераторов происходит во многих местах и немного избыточно делать проверку в каждом из них.

Проверку также можно расширить, чтобы проверялось наличие в генераторах FoldableItem и соответствие плагину.
И будет круто если проверка сможет работать на расширение, то есть при добавлении новых `AbilityItem` и плагинов не надо будет контрибьютить в библиотеку.

Идеи по реализации с тебя =)
Можем обсудить варианты голосом если нужно.

2022-06-09 08:43 UTC, kombatkos commented on Source/Collection/Manager/BaseCollectionManager.swift
> +        checkSelectablePlugin(for: generator)
Переделал реализацию. Теперь она в CollectionGeneratorsProvider и TableGeneratorsProvider

2022-06-09 10:51 UTC, NullIsOne commented on Source/Utils/Event.swift
> +        return  listners.isEmpty
```suggestion
        return listners.isEmpty
```
Лишний пробел

2022-06-09 10:51 UTC, NullIsOne commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +        willSet { checkPlugins(for: newValue) }
Nice

2022-06-09 10:51 UTC, NullIsOne commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    var delegate: TableDelegate?
Чтобы не переносить делегат в GeneratorsProvider можно в новую сущность эти проверки вынести.
Дать им доступ к PluginsProvider  и будет норм по ответственостям.

2022-06-09 10:51 UTC, NullIsOne commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    func checkPlugin(for generator: SelectableItem?) {
Пока в процессе?
Хотели же попробовать универсальный подход с пополняемым словарем плагинов и их Item.

2022-06-09 11:30 UTC, kombatkos commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    func checkPlugin(for generator: SelectableItem?) {
Универсальный метод ниже, список добавляется в checkPlugins.
Для selectable отдельный метод так как там ориентир не только на SelectableItem - так как это также должно работать без плагина, но и также на ивенты (это основной ориентир для проверки selectable плагина).
Остальные плагины будут ориентироваться только на то что принадлежит ли генератор к Item. (пример с FoldableItem)

2022-06-09 12:21 UTC, kombatkos commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    var delegate: TableDelegate?
Получится так что TableGeneratorsProvider будет наследником от новой сущности где и будет лежать делегат? Других мыслей нет.

2022-06-09 12:29 UTC, NullIsOne commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    var delegate: TableDelegate?
delegate лежит в manager
delegate описывает PluginsProvider

В новой сущности может лежать weak ref на PluginsProvider

2022-06-09 12:30 UTC, kombatkos commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    var delegate: TableDelegate?
Это понятно, но там же везде наследования

2022-06-09 12:32 UTC, kombatkos commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    var delegate: TableDelegate?
Это сработает если я уберу open из TableGeneratorsProvider и приинициализирую его в Менеджере

2022-07-05 17:01 UTC, NullIsOne commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    func checkPlugin(for generator: SelectableItem?) {
Что-то я подзабыл зачем нам эта двойственность..

2022-07-05 17:07 UTC, NullIsOne commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    var delegate: TableDelegate?
Надо разделить ответственности.
GeneratorsProvider всегда хранил генераторы и выдавал их.
Теперь он почему-то знает о плагинах и проверяет их консистентность.
Странная история.

Не совсем понимаю как open связано с введением новой сущности.
Новый PluginChecker может быть также как и остальные части ddm публичным и устанавливаемымчерез builder. (Желательно)

2022-07-07 09:31 UTC, kombatkos commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    func checkPlugin(for generator: SelectableItem?) {
Затем что SelectableItem используется всегда независимо от того пользуемся ли мы ивентами
let eventsNotEmpty = generator?.didSelectEvent.isEmpty == false || generator?.didDeselectEvent.isEmpty == false
Поэтому для selectable у нас отдельный метод

2022-07-07 09:31 UTC, kombatkos commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    func checkPlugin(for generator: SelectableItem?) {
Для всех остальных AbilityItem универсальный метод

2022-07-07 10:18 UTC, kombatkos commented on Source/Table/DataSource/TableGeneratorsProvider.swift
> +    var delegate: TableDelegate?
Переделал

2022-07-07 13:37 UTC, NullIsOne approved these changes

2022-07-07 13:46 UTC, merged