IDPT-968 UITests for selectable plugin
surfstudio/ReactiveDataDisplayManager pull request #171
Opened 2022-06-08 10:32 UTC by kombatkos

## Что сделано?

- Немного изменил логику селекта ячеек в SelectableTableViewController и CollectionViewController добавив изменение текста при выделении
- Написал UI тесты для этих экранов (проверка селекта/деселекта на основе текста ячейки)

## Зачем это сделано?

Иногда Unit тестов не достаточно для того чтобы результат работы был корректным, так как модульные тесты проверяют только отдельные механизмы как щеколда в примере ниже, но нам нужно в целом знать как это работает. Поэтому приняли решение что для плагинов нужны UI тесты (открытие двери в примере ниже)

![1516922137191938278](https://user-images.githubusercontent.com/56546669/172594920-9eebd605-e455-447d-b746-1798347d081d.gif)

## Как протестировать?

- Запустить тест <SelectablePluginExampleUITest>

2022-06-09 11:26 UTC, NullIsOne requested changes

2022-06-09 11:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/SelectableTableViewController/SelectableTableViewController.swift
> +                generator?.cell?.fill(with: "selected cell")
UI тесты не должны менять визуальное представление. Делать подгонку изменением модели это плохая практика.
Попробуй вместо замены текста использовать accessibilityLabel и accessibilityIdentifier или accessibilityValue если без них никак.

А вообще я думал, что можно проверять `isSelected` ячейки по которой тапаем.

2022-06-09 11:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +        deselectedCell.tap()
По ТЗ это должна быть одна ячейка. 
По коду это не совсем понятно, потому что для второго тапа используется другая query.

2022-06-09 11:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +        XCTAssertTrue(selectedCell.exists)
Из доки

>The fact that an element exists does not imply that it is hittable. Elements can exist offscreen, or exist onscreen but be hidden by another element, causing their [isHittable](doc://com.apple.documentation/documentation/xctest/xcuielement/1500561-ishittable?language=swift) property to return false.

Это не то что нам нужно. 
Надо проверить признак `isSelected` конкретной ячейки. Так результат будет нагляднее.

2022-06-09 11:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +    func testSelectablePluginNonAutoDeselectedCollection() throws {
А почему у коллекции только один кейс тестируется?)

2022-06-09 11:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +    func testSelectablePluginNonAutoDeselected() throws {
у нас так или иначе есть необходимость дублировать прогон кейсов для коллекции, поэтому и нейминг можно сделать с уклоном на это.

Предлагаю постороить его по такому шаблону.

`test{collection_type}_when{action_type}_then{expectation}`
или
`testTable_whenSelectableItemTapped_thenItemIsSelected`
тогда для коллекции изменится только префикс.
`testCollection_whenSelectableItemTapped_thenItemIsSelected`

О том какой именно плагин тестируется - понятно из названия `SelectablePluginExampleUITest`

2022-06-09 11:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +        // Given
Немного по Given/When/Then

По стандарту это Предусловия/Действия/Анализ результата действий
У нас тут немного не так получилось.

В Given собрались query. 
Под When действия для перехода к конкретному экрану. 
Под Then действия тела теста и анализ вперемешку.

Эта концепция Given/When/Then не очень хорошо ложится на UI тесты,  потому что нам даже для формирования предусловия всегда необходимо сделать определенный набор действий.
Разделяя query от действий мы ухудшаем читаемость. Чтобы осознать куда приходится tap, в текущей концепции надо вернуться в блок Given..

Присмотрись к подходу из теста стабильности примера - `ReactiveDataDisplayManagerExampleUITests`
Вынеся подготовку (с переходом) в функцию мы добились деления теста на preparations и assert.
В дальнейшем нам можно двигаться в подобном направлении, вынося подготовку в отдельные функции. Как минимум выбор таба и переход на экран примера можно переиспользовать в каждом тесте.
Функции подготовки предлагаю именовать в стиле `setWhat`
assert можно же оставить телом теста.

2022-06-09 11:38 UTC, kombatkos commented on Example/ReactiveDataDisplayManager/Table/SelectableTableViewController/SelectableTableViewController.swift
> +                generator?.cell?.fill(with: "selected cell")
accessibilityLabel и accessibilityIdentifier или accessibilityValue - для unit тестов. Для UI - все эти штуки возвращают nil, accessibilityLabel - возвращает значение с отображаемой ячейки. UI тесты это тесты визуала, поэтому пришлось при селекте менять текст лэйбла так как даже isSelected всегда показывает одно и тоже значение.

2022-06-09 16:40 UTC, kombatkos commented on Example/ReactiveDataDisplayManager/Table/SelectableTableViewController/SelectableTableViewController.swift
> +                generator?.cell?.fill(with: "selected cell")
Переделал на isSelected, accessibilityIdentifier помог найти нужную таблицу

2022-06-09 16:41 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +        deselectedCell.tap()
Теперь одна

2022-06-09 16:41 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +        XCTAssertTrue(selectedCell.exists)
Теперь проверяем isSelected

2022-06-09 16:42 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +    func testSelectablePluginNonAutoDeselectedCollection() throws {
Добавил в коллекцию такой же свитер как в таблице, теперь в коллекции тестируем оба кейса

2022-06-09 16:42 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +    func testSelectablePluginNonAutoDeselected() throws {
Переделал

2022-06-09 16:44 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SelectablePluginExampleUITest.swift
> +        // Given
Согласен что было смешение When/Then, но там никак их не разделить. Убрал метки

2022-06-10 10:06 UTC, NullIsOne approved these changes

2022-06-10 11:46 UTC, merged