Paginatable plugin test
surfstudio/ReactiveDataDisplayManager pull request #175
Opened 2022-06-14 14:29 UTC by kombatkos

## Что сделано?

- Добавлен тест для плагина пагинации

## На что обратить внимание?

- При получении ячеек в коллекции в отличии от таблицы мы получаем только те, которые видны на экране, поэтому реализация тестов для коллекции и таблицы разная

## Как протестировать?

- Запустить тест PaginatablePluginExampleUITest

2022-06-14 17:02 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/PaginatablePluginExampleUITest.swift
> +        let maxIteration = 10
В нашем примере есть преимущество - отсутствие реальных запросов на сервер.
Задержки для имитации загрузки зафиксированы в примере. Можно отталкиваться от этого и не закладывать лишние свайпы вверх =)

Еще не помешало бы добавить в тесты индикацию того что во время подгрузки пачки у нас индикатор анимируется.

2022-06-15 08:30 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/PaginatablePluginExampleUITest.swift
> +        let maxIteration = 10
Добавил тесты на индикацию загрузки

2022-06-15 08:31 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/PaginatablePluginExampleUITest.swift
> +        let maxIteration = 10
Свайпы вверх никак не зависят от секунд загрузки, они зависят от высоты устройства и от наполнения таблицы.

2022-06-15 11:46 UTC, NullIsOne requested changes

2022-06-15 11:46 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/PaginatablePluginExampleUITest.swift
> +        let activityIndicator = app.activityIndicators.firstMatch
Первый попавшийся индикатор это не то.
Поставь ему accessibilityIdentifier и проверяй конкретный индикатор с футера таблицы/коллекции.

2022-06-15 12:41 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/PaginatablePluginExampleUITest.swift
> +        let activityIndicator = app.activityIndicators.firstMatch
Дал ему id

2022-06-15 16:52 UTC, NullIsOne approved these changes

2022-06-15 16:52 UTC, merged