SwipeActions add-on test
surfstudio/ReactiveDataDisplayManager pull request #177
Opened 2022-06-15 07:37 UTC by kombatkos

## Что сделано?

- Добавил тесты для плагина SwipeActions

## На что обратить внимание?

- Не могу проверить на M1 - свайпы на симуляторе не работают

## Как протестировать?

- Запустить тест SwipeActionsPluginExampleUITest

2022-06-16 08:38 UTC, NullIsOne requested changes

2022-06-16 08:38 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SwipeActionsPluginExampleUITest.swift
> +        cell.swipeLeft()
Можно добавить в пример действия и на правый свайп и проверки теста расширить

- swipeLeft 
- проверка cell.buttons (правых) по идентификаторам
- swipeRight 
- проверка что никаких кнопок нет
- swipeRight
- проверка cell.buttons (левых) по идентификаторам

и еще можно добавить тест на выполнение действий

- swipeLeft
- активация действия удаления
- ячейка с идентификатором исчезла

2022-06-16 16:49 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/SwipeActionsPluginExampleUITest.swift
> +        cell.swipeLeft()
Добавил еще тестов, кнопки ищу по лейблам так не придется лезть в RDDM

2022-07-05 05:20 UTC, NullIsOne approved these changes

2022-07-05 05:34 UTC, merged