Fix project configuration for m1
surfstudio/ReactiveDataDisplayManager pull request #179
Opened 2022-06-15 14:03 UTC by kombatkos

## Что сделано?

- Добавил конфиги для M1
- Проверил решение на swipible plugin
- ...

## Зачем это сделано?

- Более быстрый запуск
- Устранение проблем связанных с симуляторами запущенных из под эмуляции intel
- Восстановление работоспособности тестов

## На что обратить внимание?

- Работает только на симуляторах начиная с iOS 14
- ...

## Как протестировать?

Если RDDM был установлен:
- Удалить DerivedData
- Сделать Clean
- В терминале вызвать make projects
- Запустить на маке с M1 без Rosetta iOS 14 - iOS 15
- Проверить плагин swippable на таблице и коллекции

2022-06-15 14:19 UTC, Ikeret approved these changes, later dismissed
На M1 все ок. Билдится, свайпы работают)

2022-06-15 17:12 UTC, NullIsOne requested changes
Круто что у вас на m1 теперь работает лучше.

На Intel и старом таргете ничего не сломалось.

Добавить шаблонов для упрощения поддержки этой конфигурации и будет совсем огонь.

2022-06-15 17:12 UTC, NullIsOne commented on Example/Podfile
> +target 'ReactiveDataDisplayManagerExample_iOS_M1' do
Чтобы не копировать настройки, можно использовать abstract_target
https://guides.cocoapods.org/syntax/podfile.html#abstract_target

Получится 2 таргета: `ExampleApp` и таргета `UITests`

2022-06-15 17:12 UTC, NullIsOne commented on Example/project.yml
> +    ReactiveDataDisplayManagerExample_iOS_M1:
Попробуй вынести в template основную конфигурацию,  чтобы не пришлось дублировать поднятие версии и другие возможные настройки
https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#target-template
Только учти что часть параметров таргета обязательные и их прийдется указывать в описании таргета (даже с шаблоном)
Например параметры type/platform
Как референс можно глянуть на лосось.

2022-06-15 17:12 UTC, NullIsOne commented on Example/project.yml
> +          MARKETING_VERSION: "7.2.1"
В makefile у меня есть правило `update_version` которое служит для обновления версии.
Когда будет финальный вариант конфига, можешь поправить пути к конфигам в этом правиле.

2022-06-16 06:18 UTC, kombatkos commented on Example/project.yml
> +    ReactiveDataDisplayManagerExample_iOS_M1:
Поднятие версии нам итак придется менять в 4х местах (iOS, iOS_M1, tvOS, tvOS_M1)

2022-06-16 06:23 UTC, kombatkos commented on Example/project.yml
> +    ReactiveDataDisplayManagerExample_iOS_M1:
Или таргеты мы убираем и оставляем как было, но добавляем config для M1 (debug, release, m1) ?

2022-06-16 06:48 UTC, kombatkos commented on Example/Podfile
> +target 'ReactiveDataDisplayManagerExample_iOS_M1' do
переделал

2022-06-16 06:49 UTC, kombatkos commented on Example/project.yml
> +    ReactiveDataDisplayManagerExample_iOS_M1:
Убрал таргеты для M1 в отдельную папку, в project.yml заинклудил эти таргеты

2022-06-16 06:49 UTC, kombatkos commented on Example/project.yml
> +          MARKETING_VERSION: "7.2.1"
Добавил пути к таргетам

2022-06-16 08:30 UTC, NullIsOne commented on Example/Podfile
> +target 'ReactiveDataDisplayManagerExample_iOS_M1' do
не совсем
абстрактного таргета тут нет
конфа для m1 в текущем варианте является подтаргетом app и зависит от него

после полного clean может сломаться

суть асбтракного таргета в том, что его нет. 
зависимость iOS_M1 от iOS нам не нужна

2022-06-16 08:32 UTC, NullIsOne commented on Example/project.yml
> +    ReactiveDataDisplayManagerExample_iOS_M1:
не так(

> Поднятие версии нам итак придется менять в 4х местах, но в одном файле (iOS, iOS_M1, tvOS, tvOS_M1)

если они будут созданы из одного шаблона, то количество мест уменьшится вдвое (как минимум)

ключевое слово здесь template
все общие параметры могут быть взяты из шаблона что лежит в отдельном файлике

версии в идеале обновлять именно в этом файлике и только в нем

2022-06-16 08:36 UTC, kombatkos commented on Example/Podfile
> +target 'ReactiveDataDisplayManagerExample_iOS_M1' do
Пробовал с абстрактным таргетом, он не создает Podfile.lock. Тут же после полного clean все создается нормально.

2022-06-16 09:36 UTC, NullIsOne commented on Example/Podfile
> +target 'ReactiveDataDisplayManagerExample_iOS_M1' do
Пробуй еще )
Что-то делаешь не так

2022-06-16 17:06 UTC, NullIsOne approved these changes, later dismissed
Гуд.
Проверить только один комент надо.

Удивительно что m1 таргет на intel тоже работает ведь в этой конфе нет никакого exclud'а. Может с обновлениями xcode ранние issue поправили и можно уже оставить один таргет. Посмотрим. Пока так оставим.

2022-06-16 17:06 UTC, NullIsOne commented on Example/project.yml
> +              TEST_TARGET_NAME: ReactiveDataDisplayManagerExample_iOS
```suggestion
              TEST_TARGET_NAME: ReactiveDataDisplayManagerExample_iOS_M1
```

2022-06-16 17:13 UTC, kombatkos commented
> Гуд. Проверить только один комент надо.
> 
> Удивительно что m1 таргет на intel тоже работает ведь в этой конфе нет никакого exclud'а. Может с обновлениями xcode ранние issue поправили и можно уже оставить один таргет. Посмотрим. Пока так оставим.

Пробовал оставить один указав в массиве таргетов тестов 2 штуки для M1 и обычный, но это не сработало ругается на x86 архитектуру

2022-06-16 17:45 UTC, NullIsOne approved these changes

2022-06-16 17:45 UTC, merged