Add move alert in movable and draggable
surfstudio/ReactiveDataDisplayManager pull request #181
Opened 2022-06-16 08:26 UTC by kombatkos

## Что сделано?

- Добавил сигналы о перемещении ячейки в Movabe и Drag'n'Droppable плагины
- Добавил пример использования для CollectionView
- ...

## Зачем это сделано?

- Бывает нужно сделать какое то действие после перемещения ячейки

## Как протестировать?

- Запустить 
- Таб Collection
- Экраны:
Collection with movable cell
 Collection with drag'n'droppable cell

2022-06-16 08:59 UTC, NullIsOne requested changes

2022-06-16 08:59 UTC, NullIsOne commented on Source/Protocols/Plugins/Generators/MovableItem.swift
> +    var id: Int { get }
Давай сделаем AnyHashable 
Это позволит в качестве индикатора использовать Int/String и прочие типы способные быть id.

Еще возможно стоит вынести это из MovableItem в отдельный протокол.
Когда будем вливать изменения в `preview/8` то приведем DiffableItem к этому новому протоколу.

2022-06-16 08:59 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/MovablePlugin/MovablePluginDataSource.swift
> +    public typealias ChangePositionResult = (id: Int, oldIndex: IndexPath, newIndex: IndexPath)
В этом tuple id можно сделать optional. Это упростит миграцию.

Тип лучше привести к универсальному AnyHashable

2022-06-16 08:59 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/DragAndDroppablePlugin/DroppablePluginDelegate.swift
> +    public typealias ChangePositionResult = (id: DragAndDroppableItem.Identifier, oldIndex: IndexPath, newIndex: IndexPath)
Тип id лучше универсализировать до AnyHashable

2022-06-16 08:59 UTC, NullIsOne commented on Source/Protocols/Plugins/Generators/MovableItem.swift
> +    var id: Int { get }
Сразу отвечу на вопрос.
Да, при вызове cellDidChangePosition прийдется добавить каст примерно такого вида
```
cellDidChangePosition?(((generator as? IdentifieableItem).id, sourceIndexPath, destinationIndexPath))
```

2022-06-16 08:59 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/MovablePlugin/MovablePluginDataSource.swift
> +    public typealias ChangePositionResult = (id: Int, oldIndex: IndexPath, newIndex: IndexPath)
Есть смысл tupple заменить структурой.
Так мы сможем прописать документацию к каждому property.
Указать там почему id может быть nil и к какому протоколу привести генератор для поддержки этого.

2022-06-16 08:59 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/MovableCollectionViewController/MovableCollectionViewController.swift
> +        movablePlugin.dataSource.cellDidChangePosition = { result in
Будет лучше если можно будет установить замыкание через конструктор плагина.
Мы оставили dataSource open чтобы на основе плагина можно было сделать свой более крутой.

Для конфигурации базового плагина следует использовать передачу параметра через статический инициализатор.

2022-06-16 08:59 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/DragAndDroppableCollectionViewController/DragAndDroppableCollectionViewController.swift
> +        dragAndDroppablePlugin.droppableDelegate.cellDidChangePosition = { result in
Аналогично movable следует перенести установку замыкания в статическую функцию dragAndDroppable

2022-06-16 11:20 UTC, kombatkos commented on Source/Protocols/Plugins/Generators/MovableItem.swift
> +    var id: Int { get }
> Сразу отвечу на вопрос. Да, при вызове cellDidChangePosition прийдется добавить каст примерно такого вида
> 
> ```
> cellDidChangePosition?(((generator as? IdentifieableItem).id, sourceIndexPath, destinationIndexPath))
> ```

не понадобилось

2022-07-05 05:31 UTC, NullIsOne approved these changes

2022-07-05 05:56 UTC, merged