Multiple Drag'n'Drop
surfstudio/ReactiveDataDisplayManager pull request #182
Opened 2022-06-20 05:05 UTC by kombatkos

## Что сделано?

- Настроил множественный перенос объектов коллекции 
- Добавил в параметры настройки отображения вью при перетаскивании и бросании 
- ...

## Зачем это сделано?

Для перетаскивания ячеек таблицы или коллекции в режиме allowMultipleSelection + generator.isNeedDeselect = false

## Как протестировать?

- Запустить
- Таб "Table"
- Table with drag and drop cells
- выделить несколько ячеек и перетащить в другое место

2022-07-05 05:34 UTC, NullIsOne commented
> Добавил в параметры настройки отображения вью при перетаскивании и бросании

лайк
Очень здорово с такой кастомизацией

2022-07-05 05:56 UTC, NullIsOne requested changes
- Подтянуть актуальный develop
- Почистить от комментариев
- Добавить аналогичные функции/кастомизации для коллекции

Когда выбираем несколько, то появляется баджик с количеством. 
Как его цвет поменять?
Можно ли вместо количества писать что-то типа "3 пиццы"?
Надо где-то в описании параметров превью добавить комментарий о том что это не кастомизируется,  если это действительно так.

2022-07-05 05:56 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Views/Cells/Generators/TitleCollectionGenerator.swift
> +    var id: AnyHashable?
Не будет ли конфликтовать с изменениями из #181 ?
(Скоро его смерджу, надо будет перепроверить и подвести к единообразному добавлению id)

2022-07-05 05:56 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/DragAndDroppablePlugin/DraggablePluginDelegate.swift
> +//        if let preview = draggableParameters?.preview {
Комментарии можно удалить если не нужны.
И todo что ниже тоже, так как мы ее разрешили.

2022-07-05 08:37 UTC, kombatkos commented on Source/Protocols/Plugins/FeaturePlugin/DragAndDroppablePlugin/DraggablePluginDelegate.swift
> +//        if let preview = draggableParameters?.preview {
Нужны, раскоментировал

2022-07-05 08:37 UTC, kombatkos commented on Example/ReactiveDataDisplayManager/Collection/Views/Cells/Generators/TitleCollectionGenerator.swift
> +    var id: AnyHashable?
В этом месте не конфликтовало

2022-07-05 16:51 UTC, NullIsOne requested changes
По правкам норм, но какие-то лишние файлы в diff затерялись

2022-07-05 16:51 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Views/Cells/Generators/TitleCollectionGenerator.swift.orig
> +>>>>>>> 66ed5af2ff8e3df984caab84bac3097c58359028
Этого фала не должно быть в diff.
Остался после слияния видимо

2022-07-05 16:51 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/DragAndDroppablePlugin/DragAndDroppablePlugin.swift.orig
> +>>>>>>> 66ed5af2ff8e3df984caab84bac3097c58359028
И снова лишний файл

2022-07-05 16:51 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/DragAndDroppablePlugin/DroppablePluginDelegate.swift.orig
> +>>>>>>> 66ed5af2ff8e3df984caab84bac3097c58359028
И опять

2022-07-07 09:20 UTC, kombatkos commented on Source/Protocols/Plugins/FeaturePlugin/DragAndDroppablePlugin/DragAndDroppablePlugin.swift.orig
> +>>>>>>> 66ed5af2ff8e3df984caab84bac3097c58359028
Убрал, видимо после конфликтов залетели

2022-07-07 09:20 UTC, kombatkos commented on Source/Protocols/Plugins/FeaturePlugin/DragAndDroppablePlugin/DroppablePluginDelegate.swift.orig
> +>>>>>>> 66ed5af2ff8e3df984caab84bac3097c58359028
Убрал

2022-07-07 13:20 UTC, NullIsOne approved these changes

2022-07-07 13:31 UTC, merged