Managers basic work tests
surfstudio/ReactiveDataDisplayManager pull request #185
Opened 2022-06-21 06:36 UTC by kombatkos

## Что сделано?

- Добавлены тесты написанные ранее
- Переделаны реализации тестов под современный билдер
- Добавлен моковый Modifier для таблицы так как с какстомным дата соус некоторые методы в UITableViewSpy не рабочие, обращение к методам перезагрузки дергается в modifier
- ...

## Зачем это сделано?

Для тестирования базовых менеджеров библиотеки

## Как протестировать?

Запуск тестов:
- BaseCollectionManagerTests
- BaseStackManagerTests
- BaseTableManagerTests
- GravityTableManagerTests
- ManualTableManagerTests
- ManualTableManagerWithCustomModifierTests

2022-06-22 19:02 UTC, kombatkos commented on Source/Table/Manager/ManualTableManager.swift
> +        }
На этом крашились некоторые тесты

2022-07-05 06:39 UTC, NullIsOne reviewed
Не все посмотрел
Тут надо аккуратно.

(Закроем устаревший)
Closing #102

2022-07-05 06:39 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/View/UITableViewSpy.swift
> +    // this method not work with custom dataSource, use MockModifier
```suggestion
    // this method not work with base dataSource, use MockDataSource
```

2022-07-05 06:39 UTC, NullIsOne commented on Source/Table/Manager/ManualTableManager.swift
> +        }
В ветке `preview-8` с этим получше возможно.
Пока сойдет это решение.
Главное что тестами мы это покрыли и заметим если что-то пойдет не так.

2022-07-05 06:41 UTC, NullIsOne commented
(Закроем устаревший)
Closes #102

2022-07-19 13:38 UTC, NullIsOne requested changes
См. комменты

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Collection/Manager/BaseCollectionManagerTests.swift
> +    func testThatRemoveGeneratorRemovesEmptySections() {
![Снимок экрана 2022-07-19 в 17 10 33](https://user-images.githubusercontent.com/28707156/179758269-1718085d-5f58-474c-942b-38102007cfdf.png)
Надо пофиксить тесты удаления

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/Generators/MockTableCellGenerator.swift
> +class MockTableCellGenerator: TableCellGenerator {
```suggestion
class StubTableCellGenerator: TableCellGenerator {
```

Ничего не подменяем и не шпионим, поэтому это всего лишь Stub. Даже не Spy.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/Generators/MockTableHeaderGenerator.swift
> +class MockTableHeaderGenerator: TableHeaderGenerator {
```suggestion
class StubTableHeaderGenerator: TableHeaderGenerator {
```

Ничего не подменяем и не шпионим, поэтому это всего лишь Stub. Даже не Spy.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/Modifier/MockTableModifier.swift
> +final class MockTableModifier: Modifier<UITableView, UITableView.RowAnimation> {
```suggestion
final class SpyTableModifier: Modifier<UITableView, UITableView.RowAnimation> {
```

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/View/UITableViewSpy.swift
> +final class UITableViewSpy: UITableView {
```suggestion
final class SpyUITableView: UITableView {
```

Чтобы с другими Stub/Mock/Spy было однородно.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/Generators/MockGravityTableHeaderGenerator.swift
> +final class MockGravityTableHeaderGenerator: GravityTableHeaderGenerator {
```suggestion
final class StubGravityTableHeaderGenerator: GravityTableHeaderGenerator {
```

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/Generators/MockGravityTableCellGenerator.swift
> +class MockGravityTableCellGenerator: MockTableCellGenerator, GravityItem {
```suggestion
class StubGravityTableCellGenerator: MockTableCellGenerator, GravityItem {
```

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/DataSource/MockTableDataSource.swift
> +class MockTableDataSource: NSObject, TableDataSource {
Тут лучше наследоваться от BaseTableDataSource все-таки и просто переопределить функцию `configure` в которой modifier и остальное задается..
Эта функция open так что проблем быть не должно.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Mock/DataSource/MockTableDataSource.swift
> +final class MockTableDataSourceWithModifier: MockTableDataSource {
Лишний.
(см. коммент выше)

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
> +            // then
Табуляция съехала. Сделай re-indent.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
> +        (header as? SelectableItem)?.didSelectEvent.invoke(with: ())
Мы так мало тестируем.
В предыдущем варианте теста имитировался вызов нажатия по ячейке средствами системы.
Я про обращение к делегату здесь.
`ddm.tableView(tableView, didSelectRowAt: IndexPath(row: 0, section: 0))`

Мы такое тоже можем, если в тесте сохраним делегат, передаваемый в TableBuilder.

Такой подход будет естественней.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
> +            // then
re-indent

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
> -        ddm.tableView(tableView, didSelectRowAt: IndexPath(row: 0, section: 0))
Вернуть бы нажатие через делегат.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Stack/Manager/BaseStackManagerTests.swift
> +        ddm.forceRefill()
После этого refill неплохо бы проверит что стек заполнился.
Иначе нет этому подтверждения.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Stack/Manager/BaseStackManagerTests.swift
> +fileprivate final class MockStackCellGenerator: StackCellGenerator {
```suggestion
fileprivate final class StubStackCellGenerator: StackCellGenerator {
```

И в отдельный файл их вынести бы.

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Manager/GravityTableManagerTests.swift
> +        XCTAssertTrue(ddm.generators[0][0] === gen2 && ddm.generators[0][1] === gen1)
Лучше разделить на две проверки и заменить `===` методом `XCTAssertIdentical`

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Manager/GravityTableManagerTests.swift
> +        XCTAssertTrue(ddm.generators[1][0] === gen3 && ddm.generators[0][0] === gen1)
Можно применить `XCTAssertIdentical ` вместо `===` и разбить на две проверки вместо одной длинной строки с `&&`

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Manager/GravityTableManagerTests.swift
> +        XCTAssertTrue(ddm.generators[0][0] === gen1 && ddm.generators[0][1] === gen2)
XCTAssertIdentical

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Collection/Manager/BaseCollectionManagerTests.swift
> +        XCTAssertTrue(ddm.generators[0][0] === gen1 && ddm.generators[0][1] === gen2)
XCTAssertIdentical

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
> +            XCTAssert(ddm?.generators[0][0] === header)
XCTAssertIdentical

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
> +            XCTAssert(ddm?.generators[0][0] === header)
XCTAssertIdentical

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/GravityFoldingHeaderGenerator.swift
> +            XCTAssert(ddm?.generators[0].count == 1)
XCTAssertEqual

2022-07-19 13:38 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Manager/BaseTableManagerTests.swift
> +        XCTAssertEqual(ddm.sections.count, 1)
Тут бы кроме  проверки ddm.sections.count и ddm.generators.count проверять через Spy что столько-то секций было создано.
Правда с реализацией этого могут быть проблемы.
Если встрянем, то можно так как есть оставить.

Хорошо со Stack получилось. там есть нативное arrangedSubviews не связанное напрямую с ddm. 
Поэтому тесты stack проверяют больше чем эти.

2022-07-21 13:47 UTC, kombatkos commented on ReactiveDataDisplayManagerTests/REFACTORING/Table/Manager/BaseTableManagerTests.swift
> +        XCTAssertEqual(ddm.sections.count, 1)
Добавил эту проверку в метод testThatAddSectionGeneratorWorksCorrectly

2022-07-21 14:03 UTC, kombatkos commented on ReactiveDataDisplayManagerTests/REFACTORING/Collection/Manager/BaseCollectionManagerTests.swift
> +    func testThatRemoveGeneratorRemovesEmptySections() {
Странно, эти тесты у меня зеленые, добавил expectation в первый метод, надо проверить с ним

2022-07-21 17:24 UTC, NullIsOne commented on ReactiveDataDisplayManagerTests/REFACTORING/Collection/Manager/BaseCollectionManagerTests.swift
> +    func testThatRemoveGeneratorRemovesEmptySections() {
На CI еще хуже ситуация
![Снимок экрана 2022-07-21 в 21 22 04](https://user-images.githubusercontent.com/28707156/180275496-0c4e28b8-eac1-4fb6-ac62-1d5d13131c71.png)

2022-07-22 05:47 UTC, kombatkos commented on ReactiveDataDisplayManagerTests/REFACTORING/Collection/Manager/BaseCollectionManagerTests.swift
> +    func testThatRemoveGeneratorRemovesEmptySections() {
Это связано с performButchUpdate почему то тут не работает, хотя когда я ставил animation: .none - локальные тесты примерно такую же ошибку выдавали

2022-07-23 09:10 UTC, NullIsOne commented
![Снимок экрана 2022-07-23 в 13 08 06](https://user-images.githubusercontent.com/28707156/180598486-522f655e-6ac5-4895-80a3-86d14d5c07b7.png)
- Отформатировал тесты
- Обновил StubCellGenerator с полностью кастомного на базовый.
Внутри ddm есть сравнение по `===` поэтому с предыдущим стабом эти тесты могли падать и были нестабильны.

2022-07-23 09:13 UTC, NullIsOne approved these changes

2022-07-23 09:13 UTC, merged