Highlightable plugin test + Adding select methods to the plugin
surfstudio/ReactiveDataDisplayManager pull request #187
Opened 2022-06-23 08:59 UTC by kombatkos

## Что сделано?

- Модифицировал Highlightable plugin методами селекта/деселекта
- Добавил документацию к плагину
- Добавил реализацию в example
- Написал тесты на все кейсы
- ...

## Зачем это сделано?

Стандартный selectionStyle у таблицы редко когда подходит, а у коллекции его вообще нет, поэтому было принято решение сделать так чтоб можно было применять стиль на выделенную ячейку

## На что обратить внимание?

- Сделал автодеселект с анимацией завязанном на SelectableItem (оттуда получаем флаг isNeedDeselect)
- ...

## Как протестировать?

- Запустить
- Таб "Collection"
- Первая ячейка
или
- Taб "Table"
- Последняя ячейка

тесты
- Запустить тест HighlightablePluginExampleUITest

2022-06-23 09:28 UTC, Ikeret commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/HighlightablePluginExampleUITest.swift
> +        cell.press(forDuration: 2)
тут получается не совсем корректный тест, который будет неуспешный, если следующий `XCTAssertTrue(cell.label == normalStyle)` выполнится до истечения времени нажатия?
Может добавить `sleep`?

2022-06-23 09:28 UTC, Ikeret commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/HighlightablePluginExampleUITest.swift
> +        cell.press(forDuration: 2)
Аналогично для теста таблицы

2022-06-23 10:08 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/HighlightablePluginExampleUITest.swift
> +        cell.press(forDuration: 2)
Тут пока выполняется нажатие в 2 секунды тест замирает, и двигается по телу метода только после того как с ячейки будет отпущен "палец"

2022-06-23 10:09 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/HighlightablePluginExampleUITest.swift
> +        cell.press(forDuration: 2)
В это время выполняется только асинхронный код который был вызван ранее

2022-06-23 10:10 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/HighlightablePluginExampleUITest.swift
> +        cell.press(forDuration: 2)
Если еще добавить sleep(2), тогда тест будет выполняться 4 секунды

2022-06-23 10:10 UTC, Ikeret commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/HighlightablePluginExampleUITest.swift
> +        cell.press(forDuration: 2)
ок, понял) тогда все гуд

2022-06-23 10:11 UTC, Ikeret submitted a review, later dismissed

2022-07-05 06:28 UTC, NullIsOne requested changes
- Поправить билд
- Попробовать переписать тесты с долгим нажатием на `XCTtestExpectation`

2022-07-05 06:28 UTC, NullIsOne commented on Source/Table/Plugins/PluginAction/TableHighlightPlugin.swift
> +        UIView.animate(withDuration: animationDuration, delay: animationDelay) {
на CI падает здесь
Говорит что `UIView` не может найти

Добавь `import UIKit` вверху и проблема должна уйти

2022-07-05 06:28 UTC, NullIsOne commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/HighlightablePluginExampleUITest.swift
> +        cell.press(forDuration: 2)
Хитро, но можно иначе в тестах.

Для ожидания какого-то результата в тестах есть `XCTestExpectation`
Его можно создать с предикатом и вызвать ему `fullfill` в том же async блоке.
А уже после press проверить что Expectation закрылось.

Такая проверка будет более понятной, нежели assert внутри асинхронного блока.
Попробуй

2022-07-05 07:29 UTC, kombatkos commented on Example/ReactiveDataDisplayManagerExampleUITests/Plugins/HighlightablePluginExampleUITest.swift
> +        cell.press(forDuration: 2)
Добавил признак нажатия + expectation с задержкой, после нажатия проверяю признак

2022-07-05 07:29 UTC, kombatkos commented on Source/Table/Plugins/PluginAction/TableHighlightPlugin.swift
> +        UIView.animate(withDuration: animationDuration, delay: animationDelay) {
Добавил

2022-07-05 16:55 UTC, NullIsOne approved these changes

2022-07-05 17:19 UTC, merged