Init reusable components fixed
surfstudio/ReactiveDataDisplayManager pull request #196
Opened 2022-09-29 13:08 UTC by kombatkos

## Что сделано?

- Создан проект для переиспользуемых ячеек 
- Создана ячейка-пробел
- ...

## Зачем это сделано?

Чтобы начать разработку пере-используемых компонентов, что позволит ускорить прототипирование и декорирование проектов.

## На что обратить внимание?

- В тестах заглушка нужна чтобы таргет не был пустым
- Сборка для tvOS упала - In Progress
- Проект с SPM не видит новый таргет - In Progress
- ...

## Как протестировать?

- Вставить в любой пример `adapter += TableSpacerCell.rddm.baseGenerator(with: .init(height: 40, color: .rddm), and: .class)` или аналог для коллекций. Попробовать разные параметры.
P.S. Отдельный экран с демонстрацией компонентов сделаем позже

2022-09-30 08:46 UTC, NullIsOne requested changes
Что-то чиним, а что-то ломаем)
см. комменты

Добавлю еще что проверку сборки примера импорта через SPM можно добавить к GitHubActions отдельным шагом.
Так отслеживать поломки будет удобнее.
Репа у нас публичная так что проблем с лимитами по времени сборок быть не должно.

2022-09-30 08:46 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/HighlightableTableTableViewController/HighlightableTableTableViewController.swift
> +        adapter += TableSpacerCell.rddm.baseGenerator(with: .init(height: 24), and: .class)
Нельзя сюда)

Это UI тесты валит.

2022-09-30 08:46 UTC, NullIsOne commented on ReactiveDataComponents/Package.swift
> +let package = Package(
Значит отдельным пакетом надо. Понятно.

2022-09-30 08:46 UTC, NullIsOne commented on ReactiveDataComponents/.gitignore
> +.DS_Store
Это после инициализации пакета появилось?
Оно нам точно нужно? Мы же не будем ссылаться на эту папку как на отдельный репозиторий..

2022-09-30 08:46 UTC, NullIsOne commented on ReactiveDataDisplayManager.podspec
> -Pod::Spec.new do |s|
Без этого импорт через cocoapods невозможен будет.
А ну-ка верни к моей версии)
Там все норм было.

2022-09-30 08:46 UTC, NullIsOne commented on SPMExample/ReactiveDataDisplayManagerSPMExample/ExamplePackage/Sources/ExamplePackage/Table/MainSPMTableViewController.swift
> +import ReactiveDataComponents
Если уж импортнули то можно пробел вставить.
Проверил. Норм работает теперь и ни на что не ругается.

2022-09-30 09:03 UTC, kombatkos commented on ReactiveDataComponents/.gitignore
> +.DS_Store
Я думал как отдельной репой

2022-09-30 09:15 UTC, kombatkos commented on ReactiveDataComponents/Package.swift
> +let package = Package(
Надо, иначе СПМ не работает
RDDM -> Components -> SPMExample (добавляет зависимость от RDDM) - Подобные цепи выдают ошибку сборки пакета

2022-09-30 09:25 UTC, kombatkos commented on ReactiveDataDisplayManager.podspec
> -Pod::Spec.new do |s|
Вернул, подкоректировал subspec

2022-10-04 09:34 UTC, NullIsOne commented on ReactiveDataComponents/.gitignore
> +.DS_Store
Пусть останется
Видимо SPM нужно это для чего-то раз он при инциализации пакета создает.

2022-10-04 09:36 UTC, NullIsOne requested changes

2022-10-04 09:36 UTC, NullIsOne commented on ReactiveDataDisplayManager.podspec
> -Pod::Spec.new do |s|
![Снимок экрана 2022-10-04 в 13 35 40](https://user-images.githubusercontent.com/28707156/193786663-2cfbfc05-04f3-4200-ba98-bdc8df5d7c42.png)
Проверяй через `make lint_lib` пожлуйста)

2022-10-04 09:38 UTC, NullIsOne commented
Еще конфликты с develop надо разрешить.
Просто влить ветку и принять актуальный Brewfile

2022-10-10 13:26 UTC, NullIsOne commented
Все поправил и расширил проверки на Github Actions.
теперь будет проверять подключение через поды и сборку примера с подключением через SPM
Жду зеленого и мерджу)

2022-10-10 13:31 UTC, NullIsOne approved these changes

2022-10-10 13:33 UTC, merged