Доработка Expandable Item
surfstudio/ReactiveDataDisplayManager pull request #211
Opened 2023-05-17 06:17 UTC by kombatkos

## Что сделано?

- Добавлена проверка на совпадение колличества генераторов и реальных ячеек в таблице перед вызовом performButchUpdate для обновления высоты ExpandableItem ячеек

## Зачем это сделано?

- На некоторых проектах валидация ячеек может происходить в специальных менеджерах по работе с генераторами, до вызова forceRefill(). Чтоб не получилось так чтоб у нас таблица обновляется без этих ячеек, была введена проверка, иначе можно получить падение в методе tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath)

2023-05-17 08:27 UTC, NullIsOne commented on Source/Table/DataSource/BaseTableDataSource.swift
> +        let numberOfSectionsAreEqual = tableView.numberOfSections == provider?.generators.count
```suggestion
        let numberOfSectionsAreEqual = tableView.numberOfSections == provider?.sections.count
```

2023-05-23 15:21 UTC, Ikeret requested changes

2023-05-23 15:21 UTC, Ikeret commented on Source/Collection/DataSource/BaseCollectionDataSource.swift
> +            self?.animator?.perform(in: collectionView, animated: true, operation: nil)
мне кажется тут лучше вызвать invalidateLayout вместо пустого batchUpddate

2023-05-24 08:41 UTC, NullIsOne approved these changes

2023-05-24 08:42 UTC, NullIsOne commented on Source/Collection/DataSource/BaseCollectionDataSource.swift
> +            self?.animator?.perform(in: collectionView, animated: true, operation: nil)
поправлено в соседнем ПР (уже влито сюда)

2023-05-24 08:47 UTC, Ikeret approved these changes

2023-05-24 09:10 UTC, kombatkos commented on Source/Table/TableBuilder.swift
> +    /// `emptyAnimatorDebounceTime` which used in `QueuedAnimator`  to improve performance of empty animation processing.
Указать что есть дефолт 150 миллисекунд

2023-05-24 10:02 UTC, merged