SPT-1455 Сделать Foldable plugin доступным для BaseManager
surfstudio/ReactiveDataDisplayManager pull request #214
Opened 2023-05-22 16:18 UTC by Golubeykov

## Что сделано?
Сделал Foldable plugin доступным для BaseManager

## Зачем это сделано?
Ранее данный плагин был доступен только для ManualManager, но он не удобный. Большинство пользователей выбирает BaseManager. 

## Как протестировать?
1) Установить патч
[ReactiveDataDisplayManager-18-23-40.patch](https://github.com/surfstudio/ReactiveDataDisplayManager/files/11533356/ReactiveDataDisplayManager-18-23-40.patch)
2) Таб Table
3) Table with foldable cell

## Демо
https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/caad402a-008c-4f4b-a45e-1ea0ef937f1f

2023-05-22 16:41 UTC, Ikeret commented
Патч для того, что на ветку не переключаться?)

2023-05-22 16:45 UTC, Ikeret commented on Source/Table/Manager/BaseTableManager.swift
> +    open func insert(after generator: TableCellGenerator,
Вроде Никита, имел в виду, чтобы инсерт не был доступен публично в BaseTableManager
Но дождемся ответа @NullIsOne

2023-05-23 07:12 UTC, Golubeykov commented
> Патч для того, что на ветку не переключаться?)

Не, я заменил manualBuilder на base в приложении-примере. Не знаю, можно ли так было делать, поэтому вынес в патч)

2023-05-23 08:49 UTC, NullIsOne requested changes
Немного доработать + запушить замену билдера из `FoldableTableViewController`

2023-05-23 08:49 UTC, NullIsOne commented on Source/Table/Manager/BaseTableManager.swift
> +    open func insert(after generator: TableCellGenerator,
Да. Надо сделать его internal, а в manual public.
internal надо будет переименовать, чтобы в manual старая инструкция осталась.

2023-05-23 08:49 UTC, NullIsOne commented on Source/Table/Plugins/PluginAction/TableFoldablePlugin.swift
> +            manager?.insert(after: generator, new: childGenerators, with: .fade)
Давай еще в `FoldableItem` добавим параметр для анимаций 
Такой алиас в `TableFoldablePlugin` -> `public typealias AnimationGroup = (remove: UITableView.RowAnimation, insert: UITableView.RowAnimation)`
По дефолту через extension протокола оставить (remove: .none, insert: .fade)
В example проекте поиграться с указанием анимаций и оставить лучшие на твое усмотрение.

2023-05-23 13:45 UTC, NullIsOne approved these changes

2023-05-23 13:47 UTC, merged