Feature/spt 1456/stress test
surfstudio/ReactiveDataDisplayManager pull request #215
Opened 2023-05-23 08:29 UTC by NullIsOne

## Что сделано?

- Добавлен QueuedAnimator для сбора операций инвалидации размеров таблицы/коллекции
- Добавлен UI-стресс тест для отслеживания крашей при активном использовании вставок вместе с expandable ячейкой и ее валидацией
- Перемещен сбор аниматора в builder
- ...

## Зачем это сделано?

Чтобы повысить стабильность и исключить ошибки в будущем.

## На что обратить внимание?

- debounceTime регулируется через builder. значение по-умолчанию 150ms
- метод `scheduleIfNeeded ` нужен только для UI стресс теста

## Как протестировать?

- Погонять пример и тесты

2023-05-23 14:54 UTC, Ikeret requested changes

2023-05-23 14:54 UTC, Ikeret commented on Source/Table/Manager/ManualTableManager.swift
> +        let indexes = (0...generatorsCount - 1).map { IndexPath(row: $0, section: index) }
```suggestion
        let indexes = (0..<generatorsCount).map { IndexPath(row: $0, section: index) }
```

2023-05-23 14:54 UTC, Ikeret commented on Source/Protocols/Plugins/FeaturePlugin/MovablePlugin/MovablePluginDataSource.swift
> +        animator?.perform(in: view, animated: true, operation: nil)
я так понял тут пустой batchUpdates вызывается? 
Почему не прописано удаление и вставка элемента? возможно в этом краш

2023-05-23 15:35 UTC, Ikeret commented on Source/Protocols/Plugins/FeaturePlugin/MovablePlugin/MovablePluginDataSource.swift
> +        animator?.perform(in: view, animated: true, operation: nil)
> Добавлен QueuedAnimator для сбора операций инвалидации размеров таблицы/коллекции

для инвалидации размеров лучше не использовать пустой батч

2023-05-24 06:15 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/MovablePlugin/MovablePluginDataSource.swift
> +        animator?.perform(in: view, animated: true, operation: nil)
В случае с Movable верно замечено. 
Изменения подтянулись по рефакторингу, но тут действительно следует заменить на вставку через modifier.
Однако, краш был совсем не в этом месте а в expandable.

По поводу практики пустого batchUpdates - это тянется с таблицы. 
Там нет invalidateLayout и Animator изначально создавался чтобы  разделить применение пары методов begin+end updates и performBatchUpdates.
Для коллекции действительно лучше invalidateLayout. Теперь мы четко разделяем пустой апдейт и непустой, поэтому можем это накрутить.

2023-05-24 06:44 UTC, NullIsOne commented on Source/Protocols/Plugins/FeaturePlugin/MovablePlugin/MovablePluginDataSource.swift
> +        animator?.perform(in: view, animated: true, operation: nil)
Аниматор коллекции поправил.
По movable за вставку/удаление отвечает сам метод dataSource 
`collectionView(_ collectionView: UICollectionView, moveItemAt sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath) `
или
`func tableView(_ tableView: UITableView, moveRowAt sourceIndexPath: IndexPath, to destinationIndexPath: IndexPath)`

В плагине мы лишь финализируем состояние. Записываем перемещения в массив генераторов и вызываем animator. 
В diffable работает и без аниматора.

В общем с movable все правильно и стабильно.

2023-05-24 08:22 UTC, Ikeret approved these changes

2023-05-24 08:41 UTC, merged