SPT-1000 Создать разделитель
surfstudio/ReactiveDataDisplayManager pull request #216
Opened 2023-05-23 11:11 UTC by Golubeykov

## [SPT-1000](https://jira.surfstudio.ru/browse/SPT-1000)

## Что сделано?
Создал переиспользуемую ячейку-разделитель.

## Зачем это сделано?
Сделать альтернативу системным сепараторам.

## Как протестировать?
1) Установить патч (если нужно, могу создать отдельный раздел в табе Table, но пока решил сделать на примере Table with foldable cell)
[ReactiveDataDisplayManager-14-02-08.patch](https://github.com/surfstudio/ReactiveDataDisplayManager/files/11542992/ReactiveDataDisplayManager-14-02-08.patch)
2) Таб Table
3) Table with foldable cell 
4) Убедиться в наличии сепараторов, можно поиграть с их размерами

## Демо
<img src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/3d16bb8f-a59b-4c58-a07b-feae7930c32d" width="300">

2023-05-23 13:54 UTC, NullIsOne approved these changes, later dismissed

2023-05-23 14:18 UTC, Golubeykov commented
@NullIsOne увидел лишнюю проперти, удалил.

2023-05-23 15:14 UTC, Ikeret requested changes

2023-05-23 15:14 UTC, Ikeret commented on Components/Sources/Common/Views/SeparatorView.swift
> +        setNeedsUpdateConstraints()
В описании этого метода сказано о пересчете контрейтов из-за изменения параметров вью
Поэтому обычно вызывается `layoutIfNeeded()` при изменении констрейтов.

2023-05-23 15:14 UTC, Ikeret commented on Components/Sources/Collection/CollectionSeparatorCell.swift
> +    public override init(frame: CGRect) {
пустой инит можно не писать

2023-05-23 15:14 UTC, Ikeret commented on Components/Sources/Collection/CollectionSeparatorCell.swift
> +    public private(set) var separator: SeparatorView = .init(frame: .zero)
```suggestion
    public let separator: SeparatorView = .init(frame: .zero)
```

2023-05-25 06:32 UTC, Golubeykov commented on Components/Sources/Collection/CollectionSeparatorCell.swift
> +    public private(set) var separator: SeparatorView = .init(frame: .zero)
Поправил сразу в одном коммите 👍🏻

2023-05-25 08:02 UTC, NullIsOne requested changes

2023-05-25 08:02 UTC, NullIsOne commented on Components/Sources/Common/Views/SeparatorView.swift
> +    public struct Model {
```suggestion
    public struct Model: Equatable {
```
суть в том чтобы все ячейки из компонентов подготовить к использованию с diffableDataSource.
А для этого достаточно привести модельку к Equatable.

2023-05-25 08:02 UTC, NullIsOne commented on Components/Sources/Common/Views/SeparatorView.swift
> +        layoutIfNeeded()
В SpacerView тоже  `layoutIfNeeded()` тогда поставим.

2023-05-25 08:02 UTC, NullIsOne commented on Components/Sources/Table/TableSeparatorCell.swift
> +public final class TableSeparatorCell: UITableViewCell, SeparatorWrapper {
Вот уже 3 ячейки и мы делаем для них рутинную работу.
Создаем `Wrapper`, создаем TableCell и CollectionCell.

Давай попробуем избавиться хотя бы от создания ячеек. Надо грамотно применить Generic и должна получиться хорошая база.

Протокол Wrapper достаточно сделать один.
А реализации ConfigurableItem описывать в extensions c where.

2023-05-29 13:26 UTC, NullIsOne approved these changes

2023-05-29 13:26 UTC, NullIsOne commented on Components/Sources/Table/TableWrappedCell.swift
> +/// Empty table cell with `View`
В комментарии можно добавить, что метод configure реализован в extension к `ViewWrapper`

(Можно в следующем ПР)

2023-05-29 13:26 UTC, NullIsOne commented on Components/Sources/Collection/CollectionWrappedCell.swift
> +    public let nestedView: View = .init(frame: .zero)
Инициализация по классу и альтернативные варианты договорились делать в #219

2023-05-30 09:04 UTC, Ikeret approved these changes

2023-05-30 10:04 UTC, merged