SPT-1360 Создать текстовую ячейку
surfstudio/ReactiveDataDisplayManager pull request #219
Opened 2023-05-25 05:58 UTC by Golubeykov

## [SPT-1360](https://jira.surfstudio.ru/browse/SPT-1360)

## Что сделано?
Создал переиспользуемую текстовую ячейку со следующими параметрами конфигурации: 
- текст String
- стиль UIColor, UIFont
- верстка TextAlignment, LineBreakMode, NumberOfLines
- отступы UIEdgeInsets

## Зачем это сделано?
Данный компонент будет использоваться в прототипе чата с нативной версткой

## Как протестировать?
1) Таб Table
2) Table with custom components

## Демо
<img src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/b88d4337-caf0-4991-bca5-79ac9c294ffd" width="300">

2023-05-25 08:25 UTC, NullIsOne requested changes

2023-05-25 08:25 UTC, NullIsOne commented on Components/Sources/Common/Views/LabelView.swift
> +    public typealias TextStyle = (color: UIColor, font: UIFont)
Лучше использовать структуры, чтобы конструктор у них читаемый был и можно было часть параметров задефолтить. В typealias дефолт проставить не получится.

А также переместить описание этих типов в nested, то есть
```
public struct Model {
   public struct TextStyle {
   ...
}
```

2023-05-25 08:25 UTC, NullIsOne commented on Components/Sources/Common/Views/LabelView.swift
> +        public let text: String
Иногда в текст мы передаем NSAttributedString. Причем в attributedString может быть переопределена часть параметров. В тч layout.

Надо предусмотреть что ячейка может конфигурироваться как String, так и NSAttributedString.
Самое просто - добавить enum для текста.

2023-05-25 08:25 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/CustomizableComponentsTableViewController/CustomizableComponentsTableViewController.swift
> +final class CustomizableComponentsTableViewController: UIViewController {
```suggestion
final class ComponentsOverviewTableViewController: UIViewController {
```

2023-05-25 08:25 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/CustomizableComponentsTableViewController/CustomizableComponentsTableViewController.swift
> +    private lazy var recievedMessageGenerator = BaseCellGenerator<TableLabelCell>(with: recievedMessageModel, registerType: .class)
```suggestion
    private lazy var recievedMessageGenerator =TableLabelCell.rddm.baseGenerator(with: recievedMessageModel, registerType: .class)
```
Можно еще так)
Этот способ предпочтительней.

2023-05-25 08:25 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/CustomizableComponentsTableViewController/CustomizableComponentsTableViewController.swift
> +            sentMessageGenerator
Один и тот же генератор по 3 раза)
Пока сойдет, но потом переделаем под diffable и lazy var надо будет на функции переделывать..

2023-05-25 08:25 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/CustomizableComponentsTableViewController/CustomizableComponentsTableViewController.swift
> +    private lazy var sentMessageStyle: LabelView.TextStyle = (.black, .systemFont(ofSize: 16, weight: .regular))
Кажется что style и layout можно сделать let

2023-05-25 08:25 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/CustomizableComponentsTableViewController/CustomizableComponentsTableViewController.swift
> +        .add(plugin: .foldable())
не нужон здесь foldable ведь)

2023-05-25 08:25 UTC, NullIsOne commented on Components/Sources/Common/Views/LabelView.swift
> +    public struct Model {
```suggestion
    public struct Model: Equatable {
```

2023-05-25 09:46 UTC, Ikeret commented on Components/Sources/Common/Views/LabelView.swift
> +            public init(alignment: NSTextAlignment, lineBreakMode: NSLineBreakMode, numberOfLines: Int) {
не хватает параметров по умолчанию, иногда нужно изменить только какой то один из этих

2023-05-25 09:53 UTC, Ikeret requested changes

2023-05-25 09:53 UTC, Ikeret commented on Components/Sources/Common/Views/LabelView.swift
> +            public init(alignment: NSTextAlignment, lineBreakMode: NSLineBreakMode, numberOfLines: Int) {
не хватает параметров по умолчанию, иногда нужно изменить только какой то один из этих

2023-05-25 09:53 UTC, Ikeret commented on Components/Sources/Common/Views/LabelView.swift
> +        public let text: String
может проще всего вернуть closure с лейблом для самостоятельной настройки? Ну или добавить такую возможность хотя бы

2023-05-25 09:53 UTC, Ikeret commented on Components/Sources/Common/Views/LabelView.swift
> +    private var textView = UILabel(frame: .zero)
Не всегда используют стандартный UILabel, может добавим еще один инит с классом UILabel
```swift
public init(labelClass: UILabel.Type) {
    textView = labelClass.init()
}
```

2023-05-25 10:35 UTC, Golubeykov commented on Components/Sources/Common/Views/LabelView.swift
> +        public let text: String
Я добавил enum с associated value, гляньте плс) Вроде так просто настраивать) С closure, имхо, посложнее

2023-05-25 11:06 UTC, Golubeykov commented on Example/ReactiveDataDisplayManager/Table/CustomizableComponentsTableViewController/CustomizableComponentsTableViewController.swift
> +            sentMessageGenerator
Вынес в функцию, так действительно аккуратнее смотрится 👍🏻

2023-05-25 14:03 UTC, Ikeret requested changes

2023-05-25 14:03 UTC, Ikeret commented on Components/Sources/Common/Views/LabelView.swift
> +    }
`configureConstraints()` еще вызвать

2023-05-25 14:03 UTC, Ikeret commented on Components/Sources/Collection/CollectionLabelCell.swift
> +    public let label: LabelView = .init(frame: .zero)
Инит с классом не получится использовать, надо либо объявить open и разрешить наследоваться от класса, либо добавить параметр в модель

2023-05-29 06:55 UTC, Golubeykov commented on Components/Sources/Collection/CollectionLabelCell.swift
> +    public let label: LabelView = .init(frame: .zero)
Ты имеешь в виду сделать вот так? Интересно, не знал про .init. Доуточню на синке) 
```swift
public let label = LabelView(frame: .zero)
```

2023-05-30 07:40 UTC, NullIsOne commented on Components/Sources/Common/Views/LabelView.swift
> +        // Mind that attributed string may re-configure other model`s properties
Этот коммент надо бы переместить к `case attributedString(NSAttributedString)` и через `///` сделать чтобы он подсвечивался.

2023-05-30 07:40 UTC, NullIsOne commented on Components/Sources/Common/Views/LabelView.swift
> +        // Mind that attributed string may re-configure other model`s properties
Само решение с enum одобряю.

2023-05-30 07:42 UTC, NullIsOne commented on Components/Sources/Common/Views/LabelView.swift
> +    private var textView = UILabel(frame: .zero)
Осталось лишь добавить возможность инициализировать nestedView через класс.
Остальные замечания вроде поправлены.

2023-05-30 08:15 UTC, Golubeykov commented on Components/Sources/Collection/CollectionLabelCell.swift
> +    public let label: LabelView = .init(frame: .zero)
Поправил 👍🏻

2023-05-30 09:02 UTC, Ikeret submitted a review, later dismissed

2023-05-30 09:07 UTC, Golubeykov commented on Components/Sources/Common/Views/LabelView.swift
> +        // Mind that attributed string may re-configure other model`s properties
Подвинул коммент, но при выборе case на контроллере коммент не появляется. Пробовал разместить коммент с разных сторон от case, копировал пробелы и переносы из работающего case spacer. Пробовал делать cleanBuild folder. Зацикливаться не стал. Возможно, это мой XCode чудит. Гляньте плс, что у вас. Если так же, то еще подумаю.

2023-05-30 09:11 UTC, Ikeret commented on Components/Sources/Common/Views/LabelView.swift
> +        // Mind that attributed string may re-configure other model`s properties
все ок
<img width="419" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/24b76c18-f91e-4ce7-ba61-2e37be2f5fbc">

2023-05-30 09:57 UTC, NullIsOne requested changes

2023-05-30 09:57 UTC, NullIsOne commented on Components/Sources/Common/Views/LabelView.swift
> +        textView = model.labelClass.init()
С таким подходом могут быть проблемы при реюзе. 
Вызывется configure, старый лейбл никуда не денется, а новый добавится поверх него..

2023-05-30 10:10 UTC, NullIsOne commented on Components/Sources/Common/Views/LabelView.swift
> +        textView = model.labelClass.init()
Вынесем решение этой проблемы в отдельную задачу

2023-05-30 10:10 UTC, NullIsOne approved these changes

2023-05-30 10:35 UTC, merged