SPT-1362 Создать ячейку сообщения
surfstudio/ReactiveDataDisplayManager pull request #221
Opened 2023-05-25 13:49 UTC by Golubeykov

## [SPT-1362](https://jira.surfstudio.ru/browse/SPT-1362)

## Что сделано?
Создал переиспользуемую ячейку сообщения со следующими параметрами конфигурации: 
- текст String
- стиль UIColor, UIFont
- верстка TextAlignment
- отступы UIEdgeInsets
- отступы внутри пузыря UIEdgeInsets

Внутри MessageView используется созданная ранее LabelView.

## Зачем это сделано?
Данный компонент будет использоваться в прототипе чата с нативной версткой

## На что обратить внимание
1) Сделал конфигурацию текста только через String. Без NSAttributedString. Подумал, что из-за вложенности MessageView, который конфигурируется по-своему, конфигурация может показаться усложненной. Хотя вот сейчас пишу и думаю, что может и норм. Что думаете? Добавить поддержку NSAttributed, по аналогии с LabelView? 
2) Сделал закругления с радиусом, которое мне показалось норм. И добавил обводку. Может тоже добавить это в конфигурацию? Или усложним? Что думаете?

## Как протестировать?
1) Таб Table
2) Table with custom components

## Демо
<img src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/083604ec-7702-4db7-b7f9-9b4f82495cfb" width="300">

2023-05-25 13:54 UTC, NullIsOne commented
>Добавить поддержку NSAttributed, по аналогии с LabelView?
Да. 
Одно из частых требований в чатах это подсветка ссылок и телефонов. 
C Attributed + TextView это проще сделать.

>Сделал закругления с радиусом, которое мне показалось норм. И добавил обводку. Может тоже добавить это в конфигурацию? Или усложним? Что думаете?

Однозначно выводить в конфигурацию.
Причем скругления могут быть

2023-05-25 14:11 UTC, NullIsOne requested changes

2023-05-25 14:11 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +    private var labelView = LabelView(frame: .zero)
>Для текста использовать TextView с отключенным режимом редактирования. Это позволит завести механизм кликанья по ссылкам внутри сообщения.

Из описания задачки)
Плюс в textView можно проще вести estimated расчет высоты, что тоже пригодится в чате.

Вообщем надо добавить возможность кликанья по ссылкам внутри сообщения. Я рекомендую метод с TextView.

2023-05-25 14:11 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/ComponentsOverviewTableViewController/ComponentsOverviewTableViewController.swift
> +                                                     externalEdgeInsets: UIEdgeInsets(top: 12, left: UIScreen.main.bounds.width / 2, bottom: 12, right: 16),
![Simulator Screenshot - iPhone 14 Pro - 2023-05-25 at 18 06 00](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/54715738-7463-4fed-9a37-5900d3a8e882)

Баблы так не работают)
externalEdgeInsets это максимальный предел ширины + вертикальные отступы между сообщениями.
Сам бабл должен быть по размеру текста и internalEdgeInsets.

2023-05-25 14:22 UTC, Ikeret requested changes

2023-05-25 14:22 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +        layer.borderWidth = 1
откуда эти параметры? В дизайне ведь разные могут быть цвета/скругления

2023-05-25 14:22 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +    private var labelView = LabelView(frame: .zero)
Использовать UILabel для чата не очень, т.к. может понадобиться выделение ссылок, номеров телефона

2023-05-25 14:22 UTC, Ikeret commented on Components/Sources/Collection/CollectionMessageCell.swift
> +public final class CollectionMessageCell: UICollectionViewCell, MessageWrapper {
Необходимо считать размер ячейки заранее, т.к. на мейн потоке при большом количестве сообщений будут лаги. Пример расчета высоты в `VerticalSizableTextGenerator` и `SizableCollectionViewCell`
Есть неплохой доклад про создание чата и оптимизации UI https://youtu.be/QD2cA1aORH8

2023-05-25 14:22 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +        public init(text: String, style: MessageStyle, textAlignment: NSTextAlignment, externalEdgeInsets: UIEdgeInsets, internalEdgeInsets: UIEdgeInsets) {
`internalEdgeInsets` для отступов UILabel от superview, а `externalEdgeInsets` для чего добавлен?
Еще message model мало чем отличается от LabelView model, можно как то переиспользовать, объединить модели

2023-05-30 13:22 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +        layer.borderWidth = 1
Сделал эти свойства параметрами модели

2023-05-30 13:22 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +    private var labelView = LabelView(frame: .zero)
Поменял на UITextView

2023-05-30 14:00 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +        public init(text: String, style: MessageStyle, textAlignment: NSTextAlignment, externalEdgeInsets: UIEdgeInsets, internalEdgeInsets: UIEdgeInsets) {
Для ограничения размеров messageView внутри ячейки. К примеру, кому-то надо ограничить размер messageView в половину экрана (как на примере). Это можно задать через externalEdgeInsets.

2023-05-30 14:10 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +        public init(text: String, style: MessageStyle, textAlignment: NSTextAlignment, externalEdgeInsets: UIEdgeInsets, internalEdgeInsets: UIEdgeInsets) {
Это ведь проще задать с помощью размеров или пропорции для самой ячейки
Предлагаю использовать нечто похожее на итем сайз из CompositionalLayout
<img width="1106" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/bec6cfeb-a874-4dcb-bfc5-9b89cf70e985">

2023-05-30 14:17 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +        public init(text: String, style: MessageStyle, textAlignment: NSTextAlignment, externalEdgeInsets: UIEdgeInsets, internalEdgeInsets: UIEdgeInsets) {
В данном случае UICollectionCell будет заполнять всю ширину, а размер TextView внутри можно задать с помощью fractional (`textView.widthAnchor.constaint(equalTo: contentView.widthAnchor, multiplier: **fractional**)` или с помощью точных значений

2023-05-30 14:26 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +        public init(text: String, style: MessageStyle, textAlignment: NSTextAlignment, externalEdgeInsets: UIEdgeInsets, internalEdgeInsets: UIEdgeInsets) {
И можно добавить вариант со статическим отступом, например:
```swift
enum LayoutDimention {
    case fractional(CGFloat)
    case absolute(CGFloat)
    case offset(CGFloat)
}
```
И предусмотреть вариант, что это может быть фиксированная ширина, либо ограничение максимальной

2023-05-30 14:41 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +        public init(text: String, style: MessageStyle, textAlignment: NSTextAlignment, externalEdgeInsets: UIEdgeInsets, internalEdgeInsets: UIEdgeInsets) {
multiplier плохо поддается апдейтам = проблемы при реюзе

Вариант с LayoutDimention можно попробовать. Чем гибче настройка компонента тем лучше.

2023-05-30 14:44 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +        public init(text: String, style: MessageStyle, textAlignment: NSTextAlignment, externalEdgeInsets: UIEdgeInsets, internalEdgeInsets: UIEdgeInsets) {
> multiplier плохо поддается апдейтам = проблемы при реюзе

вроде это если менять константу? Если удалять констрейнт с мультиплаером и устанавливать новый, то должно быть ок, но надо потестить

2023-05-31 08:15 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +        public init(text: String, style: MessageStyle, textAlignment: NSTextAlignment, externalEdgeInsets: UIEdgeInsets, internalEdgeInsets: UIEdgeInsets) {
да, проблемы multiplier при смене

в любом случае вынесем это в отдельную задачку

2023-05-31 09:11 UTC, NullIsOne commented
Исключил MessageView из билда для tvOs, потому что для tvOs мы не можем использовать isEditable из-за чего сборка падает.
Возможно для универсальности надо будет заменить внутренний TextView на что-то более низкоуровневое типа textContainer+ textLayout...

2023-05-31 09:11 UTC, NullIsOne submitted a review, later dismissed
Аппрув
Доработки вынес в отдельные 3 задачи, которые необходимо будет сделать по-порядку

2023-05-31 13:32 UTC, Ikeret approved these changes, later dismissed

2023-05-31 13:32 UTC, Ikeret commented on Components/Sources/Common/Views/LabelView.swift
> +        layoutSubviews()
заменить на `setNeedsLayout`

2023-05-31 13:43 UTC, Ikeret approved these changes

2023-05-31 14:00 UTC, merged