Feature/spt 1361/chat prototype
surfstudio/ReactiveDataDisplayManager pull request #223
Opened 2023-05-30 06:32 UTC by NullIsOne

## Что сделано?

- Проинициализирован отдельный таргет ReactiveChat
- Поправлена конфигурация app таргетов
- ...

## Зачем это сделано?

Для демонстрации всей мощи декорации компонентами на примере динамического чата с историей.

## На что обратить внимание?

- `LayoutType` выбирает реализацию UI чата. Далее в TableChatController будет добавлена талица с адаптером, а в CollectionChatController коллекция. (Для коллекции )
- Отображение сообщений будет сделано после завершения текущих задач по компонентам
- Бекенд чата будет выполнен в минималистичном стиле в отдельной задаче.
- ...

## Как протестировать?

- Запустить таргет ReactiveChat

https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/f38893e3-762f-4494-911c-9f001a94b9b7

2023-05-30 08:54 UTC, Ikeret requested changes

2023-05-30 08:54 UTC, Ikeret commented on Example/ReactiveChat/Application/HelloController.swift
> +        !(textField.text?.isEmpty ?? true)
```suggestion
        textField.text?.isEmpty == false
```
так проще для понимания)

2023-05-30 08:54 UTC, Ikeret commented on Example/ReactiveChat/Library/Reusable/ChatInputView/ChatInputView.swift
> +        onSendTapped?(text.trimWhitespacePrefix())
по идее в конце строки тоже пробелы удалять надо

2023-05-30 08:54 UTC, Ikeret commented on Example/ReactiveChat/Library/Reusable/ChatInputView/ChatInputView.swift
чат инпут очень сложный и нагруженный получился, можем InputView в отдельный класс вынести? Так и переиспользовать можно будет

Еще с текст вью баг странный, последний введенный символ отличается шрифтом
<img width="251" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/5b5fb7a3-cf2f-45eb-976b-74b2ef3ab22c">

2023-05-30 08:54 UTC, Ikeret commented on Example/ReactiveChat/Library/Extensions/UILabel.swift
> +    }()
```suggestion
    }
```
Иначе получается что base хранит переменную, а не создает новые. Также в UIButton

2023-05-30 10:41 UTC, NullIsOne commented on Example/ReactiveChat/Library/Extensions/UILabel.swift
> +    }()
Без `()` не скомпилится жеж)
Читай base как дефолтовый лейбл со свойствами по-умолчанию.
Скопировано со старого проекта.

2023-05-30 10:45 UTC, NullIsOne commented on Example/ReactiveChat/Library/Reusable/ChatInputView/ChatInputView.swift
> +        onSendTapped?(text.trimWhitespacePrefix())
Можно подумать над этим.
ChatInputView создавался под конкретные требования проекта. Его можно резать и разделять, если захотим это переиспользовать, но пока он в таком состоянии.
Это лишь часть демо-проекта, необходимая для демонстрации. В пакет библиотеки он не входит)

2023-05-30 10:49 UTC, Ikeret commented on Example/ReactiveChat/Library/Extensions/UILabel.swift
> +    }()
ну и `=` убрать сверху)
<img width="503" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/7d169a9a-1cac-4eba-b121-3f9967b4ee86">

2023-05-30 10:50 UTC, Ikeret commented on Example/ReactiveChat/Library/Extensions/UILabel.swift
> +    }()
Просто сейчас в бейз хранится объект и при добавлении в другую вью - он пропадет из первой

```swift
let a = UILabel.base
let b = UILabel.base

a === b // true
```

2023-05-30 12:13 UTC, NullIsOne commented on Example/ReactiveChat/Library/Extensions/UILabel.swift
> +    }()
Fixed

2023-05-31 13:33 UTC, Ikeret approved these changes

2023-05-31 13:36 UTC, merged