[SPT-1465] Аудит Example проекта. Поиск места отладки accessibility плагина.
surfstudio/ReactiveDataDisplayManager pull request #224
Opened 2023-05-30 17:27 UTC by Ikeret

## Что сделано?

- Исправлены хуки для 7.4
- Сделаны доработки в AccessibilityItem и пр.
- Добавлена поддержка Accessibility для коллекций
- Исправлены тесты коллекции для Highlightable
- Добавлен ActionProvider для кастомных экшенов

## Зачем это сделано?

<Описание цели.  Психологический барьер, чтобы мы все понимали что делаем библитеку лучше.>

## На что обратить внимание?

- Accessibility параметры теперь в саму ячейку, а не contentView
- В ExpandableItem (ExpandableTableCell) при использовании self переменных в Strategy значения не меняются, т.к. не срабатывает метод в плагине. Есть идея отказаться от AccessibilityStrategyProvider в генераторах, добавить в итом метод для обновления accessibility параметров

2023-05-31 09:39 UTC, NullIsOne reviewed
Потыкал Example
Описал странности в комментах
Кажется что не все SelectableItem и FoldableItem добавляют трейт button, хотя проверки на наличие обработчика в этой ветке еще нет..

2023-05-31 09:39 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Views/Cells/DynamicHeightViewCell/Subviews/RectangleColorCollectionViewCell.swift
> +            labelStrategy = .just(model.accessibilityName)
Прикольная фича для цветов.

2023-05-31 09:39 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/Views/Cells/DynamicHeightViewCell/Subviews/RectangleColorCollectionViewCell.swift
> +            labelStrategy = .just(model.accessibilityName)
Однако диапозон чувствительности у него слишком широкий.
Оттенков мало различает.
![Снимок экрана 2023-05-31 в 13 30 44](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/4000451d-7415-4951-bb15-c99fc9c0e236)
![Снимок экрана 2023-05-31 в 13 30 51](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/1b067f1b-c4ad-4dee-95bd-5153dd34f09e)
![Снимок экрана 2023-05-31 в 13 31 01](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/b50efd8e-67e2-4113-a0a6-08a41e057ed9)
![Снимок экрана 2023-05-31 в 13 31 23](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/c5fc6c4f-bdf1-4e4e-a81d-8a94f812efb2)

2023-05-31 09:39 UTC, NullIsOne commented on Source/Table/Plugins/PluginAction/TableAccessibilityPlugin.swift
> +            if let headerGenerator = manager?.sections[section] as? AccessibilityStrategyProvider {
Надо еще проверить HeaderView, TItleHeaderGenerator и SectionTitleHeaderGenerator

![Снимок экрана 2023-05-31 в 13 35 50](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/9b5934e2-4f71-467d-bc03-46bc86efe9c7)
![Снимок экрана 2023-05-31 в 13 36 04](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/da59a670-7411-4443-9c9c-304f6e4a8bd2)

2023-05-31 09:48 UTC, NullIsOne commented on Source/Utils/AccessibilityModifier.swift
> +    static func modify(item: AccessibilityItem, generator: AccessibilityStrategyProvider)
Еще не очень нравится наличие двух методов тут.
Почему бы modifyWithGenerator не вынести в отдельный Modifier
```
struct GeneratorAccessibilityModifier: AccessibilityModifier {
 
    let generator: AccessibilityStrategyProvider
    
     func modify(item: AccessibilityItem)

}
```
Имя плохое. static теряем, но получаем возможность разнести реализации по файлам и теоретически уменьшить дублирование.
Что думаешь?

2023-05-31 13:44 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Collection/Views/Cells/DynamicHeightViewCell/Subviews/RectangleColorCollectionViewCell.swift
> +            labelStrategy = .just(model.accessibilityName)
Хотя бы что-то))

2023-05-31 13:50 UTC, Ikeret commented on Source/Utils/AccessibilityModifier.swift
> +    static func modify(item: AccessibilityItem, generator: AccessibilityStrategyProvider)
В ячейку не сильно хочется добавлять поля для хранения проперти. А разделил методы чтобы не было опциональности генератора

2023-05-31 14:34 UTC, Ikeret commented on Source/Table/Plugins/PluginAction/TableAccessibilityPlugin.swift
> +            if let headerGenerator = manager?.sections[section] as? AccessibilityStrategyProvider {
В таблицах только одна ячейка пока адаптирована - `ExpandableTableCell`, в коллекциях - все

2023-05-31 14:38 UTC, Ikeret commented
Не вижу в чем ошибка при билде🤷🏻‍♂️
локально собирается и все тесты зеленые

2023-06-01 08:48 UTC, NullIsOne requested changes, later dismissed
Чисто стилевые замечания к исправлению.

В сборке проблема с Sourcery. CI использует `make build_lib_iOS`
Еще пока разбираюсь что случилось

2023-06-01 08:48 UTC, NullIsOne commented on Source/Collection/Events/CollectionEvent.swift
> +    case invalidatedCellAccessibility(IndexPath, UICollectionViewCell)
ScrollEvent, TableEvent, CollectionEvent являются отражением определенного системного делегата.
Я понимаю, что эти события добавлены сюда для удобства использования в плагине, но может найдется другой вариант?

Как минимум новые события можно отделить меткой MARK.

2023-06-01 08:48 UTC, NullIsOne commented on Source/Collection/Plugins/PluginAction/CollectionAccessibilityPlugin.swift
> +    private func processCollectionCell(_ indexPath: IndexPath, _ cell: UICollectionViewCell, with manager: BaseCollectionManager?) {
В private extension пожалуйста

2023-06-01 08:48 UTC, NullIsOne commented on Source/Protocols/Plugins/Generators/Accessibility/AccessibilityItem+Invalidation.swift
> +public enum AccessibilityItemKind {
Хорошо что этот enum не зависит от типов коллекции

2023-06-01 08:48 UTC, NullIsOne commented on Source/Table/Plugins/PluginAction/TableAccessibilityPlugin.swift
> +    private func processTableCell(_ indexPath: IndexPath, _ cell: UITableViewCell, with manager: BaseTableManager?) {
В private extension пожалуйста

2023-06-01 08:48 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/Views/Cells/ExpandableTableCell/ExpandableTableCell.swift
> +            .just(isSmall ? "collapsed" : "expanded"),
Все думал и думал как бы все-таки в стратегии указать, что она динамичная, но ничего кроме замыканий не придумалось, а это как-то фу)
с KeyPath упираемся в то что Root неизвестен.
combine требует дополнительного кода, что только усложняет реализацию..

Так что твое решение простое и понятное) Оставляем такие стратегии + invalidator.
Однако надо не забыть в доке прописать как и в каком случае этим пользоваться.

2023-06-01 08:57 UTC, NullIsOne commented
> Не вижу в чем ошибка при билде🤷🏻‍♂️ локально собирается и все тесты зеленые
![Снимок экрана 2023-06-01 в 12 56 56](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/3f0bd33d-9d87-40d2-bf07-5d59f88db7fc)

2023-06-01 10:52 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Table/Views/Cells/ExpandableTableCell/ExpandableTableCell.swift
> +            .just(isSmall ? "collapsed" : "expanded"),
да, добавим доку. Есть план разделить на 4 части: Base, Custom Items, Invalidation, Debug

2023-06-02 07:49 UTC, NullIsOne commented
Добавил комиты для починки тестов.

Основная причина как всегда: скрытые трейты и поведение на их основе.

1. Переопределение трейтов отключено в UI тестах
2. Тесты полагающиеся на a11y value + invalidate переписаны на прямой доступ к установке a11y value

По второму моменту возможно поможет прокачка инвалидатора, чтобы можно было инвалидировать только value или только label.

Плюс надо пройтись по замечаниям от линтера.

2023-06-02 16:35 UTC, NullIsOne approved these changes

2023-06-05 08:03 UTC, merged