Feature/spt 1473/chat backend
surfstudio/ReactiveDataDisplayManager pull request #226
Opened 2023-06-02 18:48 UTC by NullIsOne

## Что сделано?

- Проинициализирован минималистичный backend на swift + vapor
- Созданы клиенты api и websockets
- Настроена отправка/получение сообщений между сервером и клиентом
- ...

## Зачем это сделано?

Чтобы иметь реальную контроллируемую пару клиент+сервер для демонстрации мощи RDDM и декораций

## На что обратить внимание?

- Сохранение истории и метод загрузки истории в отдельной заадче
- Отображение сообщений в отдельной задаче (тк надо подготовить декорации и ячейку сообщения)
- ...

## Как протестировать?

- Запустить ReactiveServer (отдельный SPM пакет папкой)
- Запустить ReactiveChat таргет
- Войти в чат под любым именем
- Смотреть логи сервера и клиента

2023-06-02 18:50 UTC, NullIsOne commented on Example/ReactiveServer/Sources/Utils/Codable+Response.swift
> +//  File.swift
Вижу... 
почему-то SPM при создании всегда файлы `File.swift` создает и не дает переименовать.
Поправлю тут и в остальных местах в пн

2023-06-02 18:56 UTC, NullIsOne commented on Example/ReactiveChat/Transport/Impl/Protocols+PropertyWrapper.swift
> +@propertyWrapper
Понимаю что на проектах такой DI неприменим, но тут идея в том, чтобы максимально разгрузить контроллеры оставив там лишь помещение таблицы и наполнение данными.
При этом не хотелось усложнять пример добавлением MVP, MVVM и прочие архитектуры.
MVC + DI и всем все понятно)

2023-06-05 08:28 UTC, Ikeret requested changes

2023-06-05 08:28 UTC, Ikeret commented on Example/ReactiveChat/Transport/Impl/CoreState.swift
> +        allMessages.sort(by: { $0.timestamp < $1.timestamp })
новые сообщения должны быть самыми первыми ведь, надо наоборот сортировать
и вставлять в начало новые сообщения

2023-06-05 08:28 UTC, Ikeret commented on Example/ReactiveChat/Transport/Impl/URLSessionWebSocketClient.swift
> +                switch message {
для читаемости можно обработку success вынести в метод ниже, чтобы тройной вложенности не было)

2023-06-05 08:41 UTC, Ikeret commented
Как запустить сервер? Не нашел ни таргета, ни xcodeproj
<img width="512" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/0181bb81-748f-4e27-a80d-be1e7e7e1e82"> <img width="310" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/0d7ebc19-e7f5-448c-9ebf-a597d36ddf14">

2023-06-05 10:19 UTC, Ikeret commented
> Как запустить сервер? Не нашел ни таргета, ни xcodeproj
> <img alt="image" width="512" src="https://user-images.githubusercontent.com/14955886/243299600-0181bb81-748f-4e27-a80d-be1e7e7e1e82.png"> <img alt="image" width="310" src="https://user-images.githubusercontent.com/14955886/243299668-0d7ebc19-e7f5-448c-9ebf-a597d36ddf14.png">

Разобрались, все ок работает) Можно попробовать добавить таргет сервера в основной воркспейс

2023-06-05 12:13 UTC, Ikeret commented on Example/ReactiveChat/Transport/Impl/CoreState.swift
>          allMessages.append(message)
инсертить новые сообщения в начало лучше, чтобы было меньше сортировки

2023-06-05 12:14 UTC, Ikeret submitted a review, later dismissed

2023-06-05 12:23 UTC, NullIsOne commented on Example/ReactiveChat/Transport/Impl/CoreState.swift
> +        allMessages.sort(by: { $0.timestamp < $1.timestamp })
поправлено

2023-06-05 12:23 UTC, NullIsOne commented on Example/ReactiveChat/Transport/Impl/URLSessionWebSocketClient.swift
> +                switch message {
готово

2023-06-05 12:43 UTC, NullIsOne commented
> > Как запустить сервер? Не нашел ни таргета, ни xcodeproj
> > <img alt="image" width="512" src="https://user-images.githubusercontent.com/14955886/243299600-0181bb81-748f-4e27-a80d-be1e7e7e1e82.png"> <img alt="image" width="310" src="https://user-images.githubusercontent.com/14955886/243299668-0d7ebc19-e7f5-448c-9ebf-a597d36ddf14.png">
> 
> Разобрались, все ок работает) Можно попробовать добавить таргет сервера в основной воркспейс

Настроил через xcodegen, чтобы сервер в этом же workspace был.
Надеюсь CI не сильно замедлится от резолвинга

2023-06-05 13:51 UTC, Ikeret commented
Можно отключить подпись сертификатов как то? 

<img width="454" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/62ddd4f0-d98f-4d31-972f-5bc650f86b45">

Если None поставить, то ошибка пропадает)
<img width="454" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/209aef62-3500-449c-891e-9c3651d372c6">

А так единый таргет получился удобным, если не нужно одновременно смотреть логи девайса и сервера, можно только переключаться между консолями таргетов)
<img width="475" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/7a681db6-b464-43e5-aa1f-0a813ca72903">

2023-06-06 09:01 UTC, Ikeret commented
> Можно отключить подпись сертификатов как то?
> 
> <img alt="image" width="454" src="https://user-images.githubusercontent.com/14955886/243372126-62ddd4f0-d98f-4d31-972f-5bc650f86b45.png">
> Если None поставить, то ошибка пропадает) <img alt="image" width="454" src="https://user-images.githubusercontent.com/14955886/243372317-209aef62-3500-449c-891e-9c3651d372c6.png">
> 
> А так единый таргет получился удобным, если не нужно одновременно смотреть логи девайса и сервера. Можно только переключаться между консолями таргетов) <img alt="image" width="475" src="https://user-images.githubusercontent.com/14955886/243372954-7a681db6-b464-43e5-aa1f-0a813ca72903.png">

По прежнему ошибка 
<img width="677" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/d5a701ef-b80d-45dc-9fbf-53aff7ad8736">

2023-06-06 11:16 UTC, NullIsOne commented
> > Можно отключить подпись сертификатов как то?
> > <img alt="image" width="454" src="https://user-images.githubusercontent.com/14955886/243372126-62ddd4f0-d98f-4d31-972f-5bc650f86b45.png">
> > Если None поставить, то ошибка пропадает) <img alt="image" width="454" src="https://user-images.githubusercontent.com/14955886/243372317-209aef62-3500-449c-891e-9c3651d372c6.png">
> > А так единый таргет получился удобным, если не нужно одновременно смотреть логи девайса и сервера. Можно только переключаться между консолями таргетов) <img alt="image" width="475" src="https://user-images.githubusercontent.com/14955886/243372954-7a681db6-b464-43e5-aa1f-0a813ca72903.png">
> 
> По прежнему ошибка <img alt="image" width="677" src="https://user-images.githubusercontent.com/14955886/243640456-d5a701ef-b80d-45dc-9fbf-53aff7ad8736.png">

Добавил настроек, чтобы CODE SIGN был полностью отключен для сервера
Однако у меня и до этого было норм как на картинке
![Снимок экрана 2023-06-06 в 14 56 05](https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/bd63e882-e989-4deb-8cc9-2a50136f74f5)

2023-06-06 15:33 UTC, Ikeret approved these changes

2023-06-06 16:06 UTC, merged