Feature/spt 1474/view wrappers optimisation
surfstudio/ReactiveDataDisplayManager pull request #227
Opened 2023-06-05 15:10 UTC by NullIsOne

## Что сделано?

- Оптимизировано добавление констрейнтов в реализации `ViewWrapper`
- Изменен тип Alignment в `AlignmentProvider`
- Добавлен упрощенный способ создания генератора `TableWrappedCell` и `CollectionWrappedCell`
- ...

## Зачем это сделано?

Чтобы не было проблем с подвисшыми констрейнтами и вопросов о том как создать генератор.

## На что обратить внимание?

- Конструктор LabelView из класса не нужен) Любая вьюшка ConfigurableItem может быть обернута в TableWrappedCell или в CollectionWrappedCell.
- ...

## Как протестировать?

- Тапнуть в примере на строчку Table with custom components

2023-06-05 15:49 UTC, Ikeret requested changes

2023-06-05 15:49 UTC, Ikeret commented on Components/Sources/Common/Models/Alignment.swift
> +    case trailing
А вертикальный алайнмент не нужен?

2023-06-05 15:49 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +                    externalAlignment: Alignment?,
external и internal не понятны из контекста, раскрывают реализацию вью
Лучше назвать external = containerInsets, а internal - textInsets

Но вообще идея с external insets не очень нравится в плане того, что для каждой вью надо определять свои уникальные отступы. Есть несколько проблем, к примеру
- вертикальные могут зависеть от соседних ячеек (сверху сообщение от того же автора; системное сообщение; сообщение другого автора; другой тип сообщения и т.д.)
- будет задаваться только один из отступов (скорее всего верхний, т.к. скролл снизу вверх)
- для разного alignment будет один и тот же отступ от границы экрана, но задавать его нужно будет по-разному

Мне кажется проще задать min и max ширину контейнера, отступы от краев экрана будут регулироваться через инсеты секции, а между ячейками - через ячейки спейсеры или interItemSpacing

Итог: можно оставить пока такую реализацию, но можно бы проконсультироваться с дизайнерами насчет требований к чатам / посмотреть другие чаты и отступы в них

2023-06-06 11:28 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +                    externalAlignment: Alignment?,
Нам в любом случае нужно поставить 4 границы для поддержки динамического размера. 
UIEdgeInsets идеально подходит для настройки этих отступов. 
Если где-то нижний или верхний отступ всегда будет 0, это не проблема. Проблема была бы если б отступ был x и мы не давали возможность его изменить.

Alignment нужен для задания относительных отступов. 
При необходимости мы можем добавить привязку на процент от ширины и что угодно другое. 

Не стоит ограничиваться чатом. Чат это ультимативный пример. 
Механизм ViewWrapper же для оборачивания любой вьюшки в ячейку.
Со временем добавим новых кейсов Alignment, когда поймем что нужно.

2023-06-06 15:40 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +                    externalAlignment: Alignment?,
> Не стоит ограничиваться чатом. Чат это ультимативный пример.

Но ведь MessageView конкретно для чата сделана, по ней и замечания
Как минимум надо переименовать параметры в ините (externral, internal)

А про инсеты это в общем написал, что плохая идея для чата их использовать как отступы между ячейками. Как для ViewWrapper - вопросов нет)

2023-06-08 07:11 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +                    externalAlignment: Alignment?,
Переизобрел `Alignment` чтобы он был неразрывен с `UIEdgeInsets`
Параметр теперь в модельках зовется `viewAlignment`

В следующей задачке буду выносить общие модельки и добавлять resultBuilder чтобы было как-то так
```
   Message.rddm.collectionGenerator {
        .alignment(..)
        .textStyle(..)
        .textAlignment(..)
        .text(..)
        ...
   }
```
Все параметры необязательные. Для каждого будет значение по-умолчанию.

2023-06-08 09:08 UTC, Ikeret approved these changes

2023-06-08 09:25 UTC, merged