Hotfix/replace hardcoded animation parameter
surfstudio/ReactiveDataDisplayManager pull request #234
Opened 2023-06-19 15:20 UTC by NullIsOne

## Что сделано?

- Заменен захардкоженный флаг
- Обновлена версия
- ...

## Зачем это сделано?

Чтобы флаг пробрасывался из ExpandableItemб. как и задумывалось.

## На что обратить внимание?

- Это нам айайай. Пропустили такое на 7.3.5 
- ...

2023-06-20 08:09 UTC, Ikeret requested changes

2023-06-20 08:09 UTC, Ikeret commented on Source/Collection/DataSource/BaseCollectionDataSource.swift
> +            self?.animator?.perform(in: collectionView, animated: expandable.animatedExpandable, operation: nil)
замыкание со ссылкой на самого себя `expandable`

2023-06-20 10:29 UTC, NullIsOne commented
поправил замечание и починил отключение анимации

https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/bf6103b4-def8-4475-9a78-54a5a5730420

причина неработающей анимации была в реализации SafeAnimator и проверках

еще подумаю как это и главный фикс 7.3.5 совместить

2023-06-20 11:13 UTC, NullIsOne commented
Теперь точно поправил)

В 7.3.5 мы добавили связку аниматоров и не учли что при animated = false
Animator1.perform -> UIView.perfromWithoutAnimation + Animator1.performAnimated -> Animator2.performAnimated -> Animator3.performAnimated 
то есть второй и последний аниматор в цепочке будет вызван вне UIView.performWithoutAnimation

Поэтому анимация в примере ExpandableCell оставалась вне зависимости от состояния свитча.

Теперь работает так при animated = false
Animator1.perform -> Animator2.perform -> Animator3.perform ->  UIView.performWithoutAnimation + Animator3.performAnimated
@kombatkos @Ikeret готово к ревью

2023-06-20 11:21 UTC, Ikeret approved these changes

2023-06-21 06:36 UTC, kombatkos approved these changes
Работает, проверил на проекте

2023-06-21 08:03 UTC, merged