[SPT-1363] Таблица - плагин TwoDirectionalPaginatable
surfstudio/ReactiveDataDisplayManager pull request #237
Opened 2023-06-21 08:33 UTC by Golubeykov

## Что сделано?

- Добавил TableBackwardPaginatablePlugin для пагинации при скролле вверх (ранее была пагинация только для скролла вниз)
- Добавил в example-проект ViewController, который реализует оба плагина для пагинации (есть баг, поэтому пока что Draft PR)
- Добавил тесты (пока не работают из-за предыдущего пункта)

## Зачем это сделано?

Добавить новые возможности для библиотеки. Как пример, обратная пагинация может использоваться в чатах. 

## На что обратить внимание?
- Это драфтовый ПР, т.к. есть баг, который пока что не могу пофиксить. Если начинать скроллить вверх, то всё работает как надо (видео 1). Если наоборот, то лоадеры появляются в нужных местах, а вот кнопка retry внезапно вместо футера появляется в хэдере (видео 2). 
<details><summary>Видео</summary>

https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/10f614dd-f822-4833-8470-7af8b2b399cf
https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/1025802f-03f8-458d-80ee-796626518142

</details>

## Что попробовал, чтобы пофиксить
Явно разделил логику прикрепления progress view для forward/backward пагинаций. Попробовал создать делегатов для PaginationOutput и иницилизировал отдельный ProgressView для каждого варианта пагинации. Но всё равно пофиксить не получилось. 

## Как протестировать?
Чтобы воспроизвести баг надо:
Зайти в Table -> Table with two direction pagination -> Проскроллить вниз -> Появится лоадер -> Лоадер исчезнул, футер стал пустым
ОР: После лоадера в футере появилась кнопка Retry
ФР: Кнопка Retry появилась в хэдера

2023-06-21 09:09 UTC, NullIsOne requested changes

2023-06-21 09:09 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                                  output: forwardPaginationDelegate))
тут стоит тоже явно указать направление для наглядности

2023-06-21 09:09 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        currentPage += 1
```suggestion
        currentPage -= 1
```
по логике так должно быть)

2023-06-21 09:09 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        return currentPage < Constants.pagesCount
И это условие должно сравнивать с нулем

2023-06-21 09:09 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                self.adapter.scrollTo(generator: self.adapter.sections[middleSection].generators[middleRow], scrollPosition: .middle, animated: false)
Подскролл точно необходим тут?

2023-06-21 09:09 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +            adapter.insert(before: firstGenerator, new: makeGenerator())
insert уже включает в себя вызов необходимых для перегрузки таблицы методов

Поэтому  reload ниже не нужен.

Я бы еще предложил вместо нескольких вызовов insert использовать insertAtBeginning который может пачку новых генераторов вставить в начало секции

2023-06-21 09:09 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        adapter => .reload
Здесь можно попробовать insertAtEnd применить

2023-06-21 09:09 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                self.adapter.scrollTo(generator: self.adapter.sections[middleSection].generators[middleRow], scrollPosition: .middle, animated: false)
Попробуй избавиться от reload при вставке страниц. Это должно помочь сохранять позицию скролла.

2023-06-21 09:09 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +    private lazy var forwardPaginationDelegate = ForwardPaginationDelegate(input: self, nextPageAction: loadNextPage)
Что-то сложно получилось с этими обертками.
Думаю что ошибка с неверным отображением Error и индикатора связана с тем что где-то input/output не с тем плагином пейрится..

Давай таки откажемся от попытки вместить это в 7.4 и позволим себе изменить оригинальные протоколы плагина Paginatable, чтобы конфликт имплементации 2х onPaginationInitialized решался переименование в `onForwardPaginationInitialized` 
Таким образом Output для Forward меняется на
```
func onForwardPaginationInitialized
func loadNextPage
```

а output для Backward будет
```
func onBackwardPaginationInitialized
func loadPrevPage
```

2023-06-21 11:12 UTC, Golubeykov commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                self.adapter.scrollTo(generator: self.adapter.sections[middleSection].generators[middleRow], scrollPosition: .middle, animated: false)
Позиция скролла не сохраняется, он показывает первую ячейку из новодобавленных. Но слегка облегчил логику скролла в https://github.com/surfstudio/ReactiveDataDisplayManager/pull/237/commits/68df7fe3da26b0952a9f9711fefd2d75f8dd62b8

2023-06-21 11:20 UTC, Golubeykov commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        currentPage += 1
Я думал ограничить пагинацию 10-ю страницами, не важно в какую сторону. Но этот вариант тоже норм, чтобы ввести currentPage в ноль, надо все равно попробовать пролистать и вперед и назад)

2023-06-21 12:04 UTC, Golubeykov commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +    private lazy var forwardPaginationDelegate = ForwardPaginationDelegate(input: self, nextPageAction: loadNextPage)
Попробовал, но почему-то ошибка остается 🤔
Подумаю еще, в чем может быть проблема

2023-06-21 15:00 UTC, Ikeret commented
Нашел проблему с кнопкой ретрай не в том месте. Дело в статик полях `UILabel.base` и `UIButton.base` которые используются для `PaginatorView`. Я в одном из ПР об этом писал, но видимо это поправлено только в 7.4

Суть в том, что лейбл с кнопкой сначала добавляются  в футер вью, а затем добавляются в хедер вью. И из-за этого они пропадают из футера.

<img width="502" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/6dc77f00-087b-45fa-8615-a16a40a21362">

2023-06-21 17:53 UTC, NullIsOne requested changes
Немного отладить подскроллы

2023-06-21 17:53 UTC, NullIsOne commented on Source/Table/Plugins/PluginAction/TablePaginatablePlugin.swift
> +    /// Plugin to display `progressView` while next/previous page is loading
Доку надо размножить. 
Каждому свою. Без вариативных перечислений.

2023-06-21 17:53 UTC, NullIsOne commented on Source/Table/Plugins/PluginAction/TablePaginatablePlugin.swift
> +public extension PaginatableOutput {
После разделения extension этот не нужен не так ли?

2023-06-21 17:53 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        var generators = [TableCellGenerator]()
можно смаппить вот так 
```
let generators = (0...Constants.pageSize).map { _ in
                return makeGenerator()
            }
```

и не нужен будет for each c append

2023-06-21 17:53 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        for _ in 0...Constants.pageSize {
тут тоже можно как предложено в fillNext

2023-06-21 17:53 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                    self.adapter.scrollTo(generator: currentFirstGenerator, scrollPosition: .top, animated: false)
Этот скролл необходим чтобы оставаться на том же месте, но визуально текущая реализация после скролла оставляет видимой только предыдущую страницу.
Например, грузили page -1, а после всего видим page 0

Я попробовал поиграться и кажется с таким подходом более актуальный контент показывается
```
let canIterate = self.fillPrev()
                let currentFirstGenerator = self.adapter.sections.first?.generators[safe: Constants.pageSize]
                if let currentFirstGenerator = currentFirstGenerator {
                    self.adapter.scrollTo(generator: currentFirstGenerator, scrollPosition: .top, animated: true)
                }
```

но все равно видны анимации.
Тут надо еще поиграться

2023-06-21 17:53 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +            self?.tableView.scrollToRow(at: Constants.firstPageMiddleIndexPath, at: .middle, animated: false)
Этот скролл в середину чтобы не запускать backward pagination при отображении нулевой страницы?
Можно его убрать.  canIterate должен отключить его. У метода reload есть completion, чтобы переключить canIterate в true уже после отображения нулевой страницы

2023-06-21 17:53 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        adapter.insertAtEnd(to: sectionHeader, new: generators, with: .none)
```suggestion
        adapter.insertAtEnd(to: sectionHeader, new: generators, with: .bottom)
```

2023-06-21 17:53 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        adapter.insertAtBeginning(to: sectionHeader, new: generators, with: .none)
```suggestion
        adapter.insertAtBeginning(to: sectionHeader, new: generators, with: .top)
```

2023-06-22 07:03 UTC, Golubeykov commented
> Нашел проблему с кнопкой ретрай не в том месте. Дело в статик полях `UILabel.base` и `UIButton.base` которые используются для `PaginatorView`. Я в одном из ПР об этом писал, но видимо это поправлено только в 7.4
> 
> Суть в том, что лейбл с кнопкой сначала добавляются в футер вью, а затем добавляются в хедер вью. И из-за этого они пропадают из футера.
> 
> <img alt="image" width="502" src="https://user-images.githubusercontent.com/14955886/247595063-6dc77f00-087b-45fa-8615-a16a40a21362.png">

В моих гипотезах как пофиксить этого варианта не было, так что еще бы долго возился) Спасибо за помощь! 🔥

2023-06-22 09:03 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Extensions/UIButton.swift
> -    }()
в 7.4 эти поля оказывается тоже не пофикшены, надо туда тоже эти измененеия добавить

2023-06-22 14:47 UTC, Golubeykov commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                    self.adapter.scrollTo(generator: currentFirstGenerator, scrollPosition: .top, animated: false)
Получилось сделать появление новых ячеек без смещения позиции скролла через calculatableHeightGenerator

2023-06-22 15:08 UTC, Golubeykov commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +            self?.tableView.scrollToRow(at: Constants.firstPageMiddleIndexPath, at: .middle, animated: false)
Работает, если сделать .reloadWithCompletion и в completion положить updatePagination(canIterate: true). Но появляется другая проблема - пустой хэдер под PaginatorView (скрин ниже).
<img src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/8f6e36f4-6fc1-449d-bf64-f9f0ba08a99f" width="200">
Он инитится при updatePagination(canIterate: true). Можно решить подскроллом вниз на высоту этого хэдера (патч [removeInitialScrollToMiddle.patch](https://github.com/surfstudio/ReactiveDataDisplayManager/files/11835479/removeInitialScrollToMiddle.patch), но при скролле вверх он снова появляется). И чтобы запустить пагинацию, надо отмотаться вниз, а потом наверн. Не совсем очевидно для пользователей со стороны. Я бы предложил оставить as is с первоначальным скроллом в середину. Так вроде и для пользователя более понятно (может скроллить вверх/вниз и пагинация сразу заработает). 
Что думаете?

2023-06-22 17:37 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Extensions/UIButton.swift
> -    }()
Сделаю в своей ветке с правкой по тестам

2023-06-22 17:59 UTC, NullIsOne approved these changes, later dismissed

2023-06-22 17:59 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +            self?.tableView.scrollToRow(at: Constants.firstPageMiddleIndexPath, at: .middle, animated: false)
Для примера сочетания двух плагинов сойдет.
В чате надо будет оптимизировать.

2023-06-22 17:59 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +        return currentPage != 0
Можно добавить комментарий что количество страниц по сути бесконечно в обе стороны

2023-06-23 09:48 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +            self?.tableView.scrollToRow(at: Constants.firstPageMiddleIndexPath, at: .middle, animated: false)
потому что на canIterate устанавливается лоадер в таблицу
<img width="563" alt="image" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/14955886/3e23428b-5520-4065-b0aa-c463b50f704f">

2023-06-23 09:58 UTC, Ikeret requested changes

2023-06-23 09:58 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                if let initialGeneratorsHeight = initialGeneratorsHeight, let newGeneratorsHeight = newGeneratorsHeight {
синхронизация контент оффсета должна быть где-то внутри плагина, чтобы в каждом контроллере не писать ее заново. Вместо складываний cellHeight попробуй использовать contentSize у таблицы, там точно должно быть корректно учтены отступы и высоты ячеек

2023-06-23 10:11 UTC, Golubeykov commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                    print($1.cellHeight)
```suggestion

```

2023-06-27 09:04 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                if let initialGeneratorsHeight = initialGeneratorsHeight, let newGeneratorsHeight = newGeneratorsHeight {
Добавили в отдельную задачу SPT-1514

2023-06-27 09:11 UTC, Ikeret approved these changes

2023-06-27 09:11 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                let finalOffset = CGPoint(x: 0, y: newContentSizeHeight - initialContentSizeHeight)
Проблему с недостаточным подскроллом предлагаю решить в SPT-1514
Предполагаю, что там добавляется какой-то инсет у хедера или фактический размер хедера не соотвествует переданному в делегат (80)

2023-06-27 10:16 UTC, Golubeykov commented on Example/ReactiveDataDisplayManager/Table/TwoDirectionPaginatableTableViewController/TwoDirectionPaginatableTableViewController.swift
> +                let finalOffset = CGPoint(x: 0, y: newContentSizeHeight - initialContentSizeHeight)
Получилось пофиксить с помощью смены стиля таблицы с Grouped на Plain. Но это не целевое решение, в рамках SPT-1514 покопаю, где эта дельта в разнице стилей.

2023-07-10 08:05 UTC, NullIsOne approved these changes

2023-07-10 08:05 UTC, merged