[SPT-1514] Попробовать затянуть подскролл прямо в плагин backward paginatable
surfstudio/ReactiveDataDisplayManager pull request #243
Opened 2023-06-28 06:17 UTC by Golubeykov

## [SPT-1514](https://jira.surfstudio.ru/browse/SPT-1514)
## Что сделано?

- Перенес логику подскролла в BackwardPaginatablePlugin. Нужно для сохранения позиция скрола в случае загрузки предыдущей страницы. 

## Зачем это сделано?

Чтобы пользователям не приходилось 

## На что обратить внимание
При обратной пагинации (если скроллить наверх), при после вставки новых ячеек в начало, сбивается позиция изначального скролла примерно на 20 единиц. При чем эта проблема актуальна только для второй страницы скролла. Дальнейшие страницы грузятся с корректным возвратом на изначальную позицию скролла. В таблице получилось пофиксить это сменив стиль с Grouped на Plain (но это тоже не целевое решение). В коллекции такого нет. На момент создания ПРа пофиксить не получилось. Поэтому ПР драфтовый. 

## Как протестировать?
Чтобы воспроизвести проблему надо:
Зайти в Collection/Table -> Collection/Table with two direction pagination -> Проскроллить вверх. 

<details><summary>Демо</summary>

https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/017ba0b4-7532-43c8-8eac-b01140b1f5bf

</details>

2023-06-28 11:16 UTC, Ikeret requested changes

2023-06-28 11:16 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Collection/TwoDirectionPaginatableCollectionViewController/TwoDirectionPaginatableCollectionViewController.swift
> +    private weak var backwardPaginatableInput: BackwardPaginatableInput?
Заменить слова Forward и Backward на Top и Bottom

2023-06-28 11:16 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Collection/TwoDirectionPaginatableCollectionViewController/TwoDirectionPaginatableCollectionViewController.swift
> +                input?.returnToScrollPositionBeforeLoading()
- спрятать вызов метода внутрь `updatePagination`
- добавить Bool параметр обозначающий необходимость вызова этого метода
- вызывать только при необходимости синхронизации (смотреть на сохраненный contentInset и contentOffset)

2023-06-28 11:16 UTC, Ikeret commented on Source/Collection/Plugins/PluginAction/CollectionBackwardPaginatablePlugin.swift
> +            currentContentHeight = collectionView?.contentSize.height ?? 0
Сделать опциональным, чтобы в зависимости от наличия вызывать метод синхронизации
Возможно нужен contentOffset еще для корректного расчета для первой страницы

2023-06-28 11:16 UTC, Ikeret commented on Source/Collection/Plugins/PluginAction/CollectionBackwardPaginatablePlugin.swift
Вместо addSubview сделать метод с добавлением и установкой первоначального фрейма
Для `ProgressDisplayableItem` добавить метод, возвращающий высоту (`viewHeight`)

2023-07-10 09:44 UTC, NullIsOne commented
Счетчик  `currentPage` в примере один на двоих, поэтому возможны такие ситуации

https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/2dbf90a2-d22f-44c2-a1f6-e0340a0c0343


https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/18f5200f-8c5c-43ae-a70b-ec118591d39f

Надо поправить.

2023-07-11 18:08 UTC, Golubeykov commented
> Счетчик `currentPage` в примере один на двоих, поэтому возможны такие ситуации
> 
>  Simulator.Screen.Recording.-.iPhone.14.-.2023-07-10.at.13.05.59.mp4 
>  Simulator.Screen.Recording.-.iPhone.14.-.2023-07-10.at.13.05.12.mp4 
> Надо поправить.

Поправил 👍🏻

2023-07-12 08:18 UTC, NullIsOne requested changes

2023-07-12 08:18 UTC, NullIsOne commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +            collectionView?.setContentOffset(finalOffset, animated: false)
Что-то не работает у коллекции подскролл
В конец верхней страницы проматывает

https://github.com/surfstudio/ReactiveDataDisplayManager/assets/28707156/302d1da3-aa0b-4949-9c61-da269b0b9910

2023-07-12 08:18 UTC, NullIsOne commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +    private let isSaveScrollPositionNeeded: Bool
Рубильник не используется.
В `TableTopPaginatablePlugin` тоже.

Мы же решили что без подскролла плохой UX. Можно удалить рубильник совсем тогда.

2023-07-12 08:18 UTC, NullIsOne commented on Source/Collection/Plugins/PluginAction/CollectionPaginatablePlugin.swift
> +    private var isLoadError = false
```suggestion
    private var isErrorWasReceived = false
```

2023-07-12 08:18 UTC, NullIsOne commented on Source/Table/Plugins/PluginAction/TablePaginatablePlugin.swift
> +                                    output: TopPaginatableOutput) -> TableTopPaginatablePlugin {
выровнять по табам

2023-07-12 08:18 UTC, NullIsOne commented on Source/Collection/Plugins/PluginAction/CollectionPaginatablePlugin.swift
> +                                    output: TopPaginatableOutput) -> CollectionTopPaginatablePlugin {
выровнять по табам

2023-07-12 08:18 UTC, NullIsOne commented on Source/Table/Plugins/PluginAction/TableTopPaginatablePlugin.swift
> +            tableView?.setContentOffset(finalOffset, animated: false)
setContentOffset это метод ScrollView. Получается мы можем переиспользовать подскролл и логику с хранением currentContentSize в отдельной сущности. 
Отличается только метод подсчета finalOffset из-за расположения header у коллекции.

Когда плагин будет работать как часы - подумаем над тем как уменьшить дублирование.
Изменения идут в develop поэтому тут у нас много опций, вплоть до создания базового пагинатора независимого от коллекций и направлений, с возможностью выбора.

2023-07-12 08:21 UTC, NullIsOne commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +            collectionView?.setContentOffset(finalOffset, animated: false)
TwoDirectionPaginatableExampleUITest надо добавить кейсы для коллекции, чтобы на CI это тоже отлавливалось.

2023-07-12 10:23 UTC, Golubeykov commented on Source/Collection/Plugins/PluginAction/CollectionPaginatablePlugin.swift
> +    private var isLoadError = false
Поправил сразу везде

2023-07-12 11:05 UTC, Golubeykov commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +            collectionView?.setContentOffset(finalOffset, animated: false)
> Что-то не работает у коллекции подскролл В конец верхней страницы проматывает
> 
>  Simulator.Screen.Recording.-.iPhone.14.Pro.-.2023-07-12.at.11.59.24.mp4

Странно, у меня не воспроизводится данное поведение. У тебя точно последняя версия ветки? 

https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/1be49e21-1584-456f-8e0f-602b5d3d1ce6

2023-07-12 11:22 UTC, Golubeykov commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +    private let isSaveScrollPositionNeeded: Bool
Конкретно в данном случае да, подскролл нужен для UX. Но я думал сделать вариативность для пользователей. Добавил флаг в инит плагина. Если надо совсем удалить, дай знать)

2023-07-13 08:01 UTC, NullIsOne reviewed
Осталось

- сделать rebase от свежего develop
- удалить или доделать рубильник ` isSaveScrollPositionNeeded`
- добавить Warning комментарий для `TableTopPaginatable` плагина указывающий на то что `UITableView.style` должен быть `plain`. 

По поводу последнего пункта. 
`grouped` и `insetGrouped` в таблице нужны для `sicky headers` при котором сверху всегда отображается заголовок секции. Он как бы "прилипает". Это актуально для таблиц с несколькими секциями. Пагинация же наоборот применяется в моно-таблицах без заголовков.
Это заведомо конфликтующие механики, поэтому предлагаю ограничиться комментарием.

В примере с `UICollectionView` подобный глюк с offset может быть связан с `contentInsetAdjustmentBehaviour` или с работой лейаута.
На Xcode 15  к сожалению верхняя пагинация прокручивает в конец страницы, поэтому не могу поковырять и направить точнее.

2023-07-13 08:01 UTC, NullIsOne commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +    private let isSaveScrollPositionNeeded: Bool
Я про то, что флаг ставится при ините, хранится в инстансе плагина, но ни в какой проверке не участвует.

Фейковый рубильник получается, который по факту ничего не делает.

Либо добавить его перед логикой с setContentOffset, либо убрать.

2023-07-13 08:01 UTC, NullIsOne commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +            collectionView?.setContentOffset(finalOffset, animated: false)
Точно, перепроверил.
Может Xcode 15 Beta чудит. 
`testCollection_whenSwipeUpAndDown_thenFirstVisibleCellChanged` локально падает.
Если на CI норм, то спишем на Xcode 15 и решим проблему при миграции на Release Candidate.

2023-07-13 09:23 UTC, Golubeykov commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +            collectionView?.setContentOffset(finalOffset, animated: false)
<img width="470" alt="Снимок экрана 2023-07-13 в 12 22 55" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/6d6b31df-2c6e-4c01-9f88-554f8d02cc02">

Да, у меня тесты прогоняются

2023-07-13 09:27 UTC, Golubeykov commented on Source/Collection/Plugins/PluginAction/CollectionTopPaginatablePlugin.swift
> +    private let isSaveScrollPositionNeeded: Bool
А, понял про что ты) Да, действительно рубильник ни на что не влиял. Поправил 👍🏻 
Спасибо за коммент!

2023-07-14 07:21 UTC, NullIsOne approved these changes

2023-07-14 07:22 UTC, merged