[SPT-1478] Интерактивность MessageView
surfstudio/ReactiveDataDisplayManager pull request #244
Opened 2023-06-30 10:46 UTC by Golubeykov

## [SPT-1478](https://jira.surfstudio.ru/browse/SPT-1478)
## Что сделано?

- Добавил механизм распознавания ссылок (dataDetectorTypes, linkTextAttributes) через конфигурацию вьюхи (то есть  этот механизм можно не включать)
- Добавил замыкание для кастомной обработки нажатия на ссылки
- Добавил замыкание для кастомной обработки нажатия на тело сообщения
- Добавил возможность не включать выделение и копирование текста

## Зачем это сделано?

Добавить новые возможности для библиотеки. Пример - взаимодействие с ячейкой сообщения в чате. 

## На что обратить внимание
1) Обнаружил баг, который так же есть в базовой ветке и аффектит эту задачу. На момент создания ПРа пофиксить не получилось. Суть заключается в том, что при инициализации таблицы поверх основного contentView ячейки поверх создается еще один пустой contentView. Он перехватывает на себя нажатия. **Но** если пролистать таблицу ниже, при переиспользовании, этот пустой contentView пропадает. Пробовал убирать другие элементы по типу дат и спейсера, крутил-вертел генераторы. Разобраться не получилось. Вот скрин с пустой contentView над ячейкой (выделена синим).  
<img width="600" alt="odd content view" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/a4ba7239-b0e1-4243-97f4-5101df37f48d">
2) Если добавлять на MessageView одновременно tapHandler и dataDetectionHandler, то обрабатываться будет только tapHandler (т.к. один перекрывает другой). Пока что не смотрел, как можно их совместить. Дайте знать, если требуется совместить.

## Как протестировать?

Зайти в Table -> Table with custom components -> Проскроллить полученные сообщения (тап работать не будет из-за бага выше) -> Дойдя до отправленных сообщений, нажать на ссылку, попробовать выделить/скопировать текст -> Просколллить вверх, теперь на полученные сообщения можно нажимать, должен появиться алерт

<details><summary>Демо</summary>

https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/3e437d2b-839a-4d44-a138-edbbc4864b61

</details>

2023-06-30 11:36 UTC, Ikeret requested changes

2023-06-30 11:36 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +            textView.addGestureRecognizer(tapGesture)
Можно не удалять предыдущий gesture recognizer. Добавить один раз в ините и дальше смотреть есть ли хэндлер из модели

2023-06-30 11:36 UTC, Ikeret commented on Components/Sources/Common/Views/MessageView.swift
> +        handleDataDetection(.link, URL.absoluteString)
URL может быть не только ссылка, а еще телефон по идее

2023-06-30 11:36 UTC, Ikeret commented on Example/ReactiveDataDisplayManager/Table/ComponentsOverviewTableViewController/ComponentsOverviewTableViewController.swift
> +        property.selectable(true)
при `isSelectable = false` выключается data detector, можно добавить коммент к полям `dataDetectionHandler` и `dataDetectorTypes` или принудительно ставить true

2023-07-10 09:37 UTC, NullIsOne requested changes

2023-07-10 09:37 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +        public typealias DataDetectionHandler = (DataDetectionType, String) -> Void
Давай DataDetectionHandler, DataDetectionType, linkTextAttributes в одну структуру вынесем, также как делали для BorderStyle и BackgroundStyle.
Таким образом можно будет переиспользовать эту подмодель в других компонентах.

Структуру сделать Equatable и не прийдется описывать  `func == ` модели.

2023-07-10 09:37 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +        public typealias TapHandler = () -> Void
TapHandler тоже стоит вынести в какую-то общую структуру.
к нему в пару можно добавить какие-нибудь настройки подсветки.

2023-07-10 09:37 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +            public static func selectable(_ selectable: Bool) -> Property {
Selectable необходим для включения detection. Лучше сделать это свойство автоматическим, чтобы при включении dataDetection или tapHandler selectable переключалось в true.
Это же свойство внутренней вбюшки, а не ячейки.

2023-07-10 09:37 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +        private static func areDictionariesEqual(_ lhs: [NSAttributedString.Key: Any]?, _ rhs: [NSAttributedString.Key: Any]?) -> Bool {
Эта функция не понадобится если тип сменить на 
```
private(set) public var linkTextAttributes: [NSAttributedString.Key: AnyEquatable]?
```

Можно будет использовать обычное сравнение `==`

2023-07-13 14:52 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +        public typealias TapHandler = () -> Void
Тоже вынес tapHandler в отдельную структуру, но пока что добавил туда только tapAction: ()->Void, т.к. хотел сначала проговорить что имелось в виду под параметрами подсветки? Изменение attributedString / background в другую в рамках анимации (к примеру, текст и background меняют цвет на 0.5 сек и потом возвращаются обратно)?

2023-07-13 15:08 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +            public static func selectable(_ selectable: Bool) -> Property {
Добавил логику принудительного сеттинга isSelectable в true, если dataDetection или tapHandler != nil. Добавил коммент для пользователей, если они захотят поставить свойство isSelectable в false.

2023-07-13 19:05 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +        private static func areDictionariesEqual(_ lhs: [NSAttributedString.Key: Any]?, _ rhs: [NSAttributedString.Key: Any]?) -> Bool {
Может я где-то туплю, но при пересаживании на AnyEquatable получаю краш.
<img width="701" alt="Снимок экрана 2023-07-13 в 21 51 47" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/cf5b2975-03e5-4fe6-9d36-a3d2f696bdcf"> . Делал по аналогии другим классам, где используется AnyEquatable. Перебрал различные варианты, в чем может быть проблема, пофиксить не получилось. Еще гляну, но если у тебя идеи, дай знать плс) 

Сделал вот такие доработки [anyEq.patch](https://github.com/surfstudio/ReactiveDataDisplayManager/files/12043489/anyEq.patch)

2023-07-13 19:23 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +            textView.addGestureRecognizer(tapGesture)
У меня в данном случае появилась проблема, связанная с переиспользованием ячеек (но это не точно). На ячейке сохраняется предыдущий gestureRecognizer. И (видимо) он и отрабатывает в кейсах, когда в модели tapHandler отсутствует, но при нажатии на ячейку он отрабатывает. Поэтому в примере на скрине вместо нажатия на ссылку срабатывает TapGesture.
<img width="238" alt="Снимок экрана 2023-07-13 в 22 18 51" src="https://github.com/surfstudio/ReactiveDataDisplayManager/assets/47087482/9104ecbc-ac64-499f-9180-a3791eebae9c">

Поэтому в явном виде удалял предыдущие gestureRecognizer.  

Дай плс знать, если я не так тебя понял и ты имел в виду другое)

2023-07-14 07:59 UTC, NullIsOne requested changes
- Добавить идентификатор для точного сравнения Handler
- Добавить TextStyle и BackgroundStyle для подсветки TapHandler
- Поправить билд на tvOS (Lint/pod)
- Оптимизировать обращение с GestureRecognizer

2023-07-14 07:59 UTC, NullIsOne commented on Components/Sources/Common/Models/Styles/DataDetection.swift
> +    public var dataDetectorTypes: UIDataDetectorTypes = []
```
 - ERROR | [ReactiveDataDisplayManager/Components] xcodebuild:  /Users/runner/work/ReactiveDataDisplayManager/ReactiveDataDisplayManager/Components/Sources/Common/Models/Styles/DataDetection.swift:23:141: error: 'UIDataDetectorTypes' is unavailable in tvOS
```

То есть надо чтобы этот тип был исключен из сборки на tvOS.
Поможет `#if os(iOS)` 
Ориентируйся на `make lint_lib` или просто переключись на tvOS таргет для проверки (но тогда симулятор tvOS прийдется установить)

2023-07-14 07:59 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +            textView.addGestureRecognizer(tapGesture)
Сережа имеет ввиду, что  gesture recognizer можно повесить один раз.
В ` handleTapGesture` у нас стоит гард проверяющий наличие обработчика, а вот обнуления обработчика (tapHandler) не происходит, потому что ` self.tapHandler = tapHandler` спрятан за `if let`.

Понятненько?)

2023-07-14 07:59 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +            /// To set it to **false**, dataDetection and tapHandler must be nil
Хм.. а ведь когда мы на макрос переедем, он не будет такой коммент генерить..
Надо как-то добавить возможность комментирования статик-сеттеров в макрос.

2023-07-14 07:59 UTC, NullIsOne commented on Components/Sources/Common/Models/Styles/TapHandler.swift
> +        return true
Потенциально опасно.
Может TapHandler добавить обязательный AnyHashable идентификатор?
Практично будет строкой задавать. Давать краткое описания работы в замыкании..

2023-07-14 07:59 UTC, NullIsOne commented on Components/Sources/Common/Models/Styles/DataDetection.swift
> +        areDictionariesEqual(lhs.linkTextAttributes, rhs.linkTextAttributes) &&
Тут тоже сам обработчик хорошо бы идентифицировать.

2023-07-14 07:59 UTC, NullIsOne commented on Components/Sources/Common/Models/Styles/TapHandler.swift
> +public struct TapHandler: Equatable {
Для подсветки можно добавить TextStyle и BackgroundStyle

2023-07-14 14:00 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +            /// To set it to **false**, dataDetection and tapHandler must be nil
Тут бы голосом проговорить, не совсем понял, как пофиксить этот момент 🙈

2023-07-14 14:17 UTC, Golubeykov commented on Components/Sources/Common/Views/MessageView.swift
> +            textView.addGestureRecognizer(tapGesture)
Сделал вот так, но по-прежнему остается проблема, о которой писал выше. Давай мб тогда голосом на ближайшем созвоне проговорим. 
[gesture.patch](https://github.com/surfstudio/ReactiveDataDisplayManager/files/12051225/gesture.patch)

2023-07-17 09:54 UTC, NullIsOne requested changes
Доделать по
- id в Handlers
- tapgesture в init

По сравнению NSDictionary оставляем как есть

Для решения проблемы с взаимоисключением TapGesture и жестов UITextView попробуй флаг `cancelsTouchesInView`
Вроде работает

2023-07-17 09:54 UTC, NullIsOne commented on Components/Sources/Common/Models/Styles/DataDetection.swift
> +    public let id = UUID()
Посмотри в сторону DiffableItem.id и AnyHashable.
Под AnyHashable попадают как Int, так и String.

Плюс надо добавить задание id в инициализатор.

2023-07-17 09:54 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +            /// To set it to **false**, dataDetection and tapHandler must be nil
Это комент к ПРу с макросом. Чтобы не забыть

2023-07-17 09:54 UTC, NullIsOne commented on Components/Sources/Common/Views/MessageView.swift
> +            textView.addGestureRecognizer(tapGesture)
В патче добавляется gesture recognize на каждый configure
Мы предлагаем сделать это 1 раз при ините MessageView...

2023-07-18 12:19 UTC, NullIsOne commented
@Golubeykov проблема с несрабатыванием тапа и невидимой contentView была в том, что наш ViewWrapper добавлял MessageView непосредственно к ячейке, а не к contentView.
reuse судя по всему фиксил это и тапы начинали работать.

Я также изменил способ подсветки сообщения, чтобы на стейты опираться, а не на анимацию дополнительную, но так сразу не взлетело..) Еще подумаю как улучшить.

2023-07-19 07:52 UTC, NullIsOne approved these changes
После экспериментов и небольшого исследования по чатам вырезал TapHandler за ненадобностью и наличием конфликтов с жестами из UITextView.

Также отрефакторил нейминг и оптимизировал DataDetectionStyle.Handler.

Потенциально полезно будет дать возможность контроллировать меню
> - (nullable UIMenu *)textView:(UITextView *)textView editMenuForTextInRange:(NSRange)range suggestedActions:(NSArray<UIMenuElement *> *)suggestedActions API_AVAILABLE(ios(16.0));
но пока нет запроса на конкретные действия оставим по дефолту share + copy.

2023-07-20 09:43 UTC, merged