RDDM. Унифицировать BaseEvent
surfstudio/ReactiveDataDisplayManager pull request #249
Opened 2023-07-18 10:22 UTC by kombatkos

## Что сделано?

- Удалил лишнее
- Добавил родительский UniversalEvent, и наследников
- ...

## Зачем это сделано?

- Чтобы не было дублирования, и в дальнейшем при добавлении новых ивентов можно было просто отнаследоваться.

## На что обратить внимание?

- ...

## Как протестировать?

- Сбилдить проект

2023-07-19 06:23 UTC, NullIsOne requested changes
Желание избежать переименований привело к неочень логичному неймингу.
Надо это исправить.

Мажорный апдейт 8.0 допускает переименования по проекту на уровня `BaseEvent<Input> -> Event<Input>`
Такой рефакторинг упростит внутреннюю структуру и invoke ивентов, а в migration guide  это будет лишь одна инструкция по переименованию.

2023-07-19 06:23 UTC, NullIsOne commented on Source/Utils/Event.swift
> +public class BaseEvent<Input>: UniversalBaseEvent<Input, Void> { }
BaseEvent без наследования никакой не Base.
Нейминг и структура из описания логичнее.

2023-07-19 06:23 UTC, NullIsOne commented on Source/Utils/Event.swift
>      public func invoke() {
Вместе с этим хорошо бы почистить места `?.didSelectEvent.invoke(with: ())` по всему проекту.

2023-07-19 11:20 UTC, kombatkos commented on Source/Utils/Event.swift
> +public class BaseEvent<Input>: UniversalBaseEvent<Input, Void> { }
Не совсем, будут конфликты

2023-07-20 09:42 UTC, NullIsOne commented on Source/Utils/Event.swift
> +public class BaseEvent<Input>: UniversalBaseEvent<Input, Void> { }
Конфликты можно разрешить несколькими способами.
InputEvent<Input> это тавталогия. (2 раза Input)

Есть требования задачи и им надо следовать. 

Конфликт 1 - `protocol Event` и `Event<Input>` из требований
Зачем сразу отклоняться от требований если можно переименовать протокол хотябы в `EventProtocol`?

Конфликт 2 - `PluginAction.Event`(assotiatedtype) и `Event<Input>`
Решается также просто изменениями в протоколе, которые ни на что снаружи библиотеки не влияют.

Запушил эти изменения, попутно поправив Unit тесты, которые ссылались на старый `BaseEvent<Input>` а не на `Event<Input>`

2023-07-21 06:19 UTC, merged