Added BaseCollectionCellGenerator & ConfigurableCollectionItem
surfstudio/ReactiveDataDisplayManager pull request #52
Opened 2019-03-28 09:49 UTC by maximality

Added `BaseCollectionCellGenerator` to simplify Collection Cells generation. No need to write Collection Generators everytime now :)

2019-03-28 09:52 UTC, ismetanin requested changes

2019-03-28 09:52 UTC, ismetanin commented on Source/BaseCollectionDataDisplayManager/Support/ConfigurableCollectionItemProtocol.swift
> +public protocol ConfigurableCollectionItem where Self: UICollectionViewCell {
Может просто поправим Configurable чтобы работала со всеми `UIView`?
```swift
public protocol Configurable where Self: UIView {

    associatedtype Model

    func configure(with model: Model)

}
```

2019-03-28 10:09 UTC, ismetanin approved these changes

2019-06-28 05:37 UTC, LastSprint approved these changes

2019-06-28 05:44 UTC, merged