IDPT-490 New roadmap
surfstudio/ReactiveDataDisplayManager pull request #74
Opened 2020-10-13 08:31 UTC by LastSprint

Освежил ROADMAP для RDDM. Здесь перечислен список целей, а в ментальной карте расписаны конкретные действия для достижения этих целей. Все действия будут превращены в задачи. 

Если есть идеи, предложения, то можно писать их комментариями к этому PR-у

2020-10-13 08:56 UTC, NullIsOne commented on ROADMAP.md
> +- Сократить время на написание шаблонного кода. Много времени уходит на написание однотипных генераторов. Необходимо посмотреть какие генераторы пишутся наиболее часто и написать 1 или несколько азов
Уже есть `BaseCellGenerator` и `BaseCollectionCellGenerator` использующие `Configurable`, но они не всегда подходят.
Например, когда в генераторе прописывается нечто вроде `var didTap: Closure<Bool>?`
Модель в Configurable и обработчик нажатия логически разделяются.
Было бы круто композицией добавлять этим базовым генераторам разного рода обработчики.

2020-10-13 10:13 UTC, LastSprint commented on ROADMAP.md
> +- Сократить время на написание шаблонного кода. Много времени уходит на написание однотипных генераторов. Необходимо посмотреть какие генераторы пишутся наиболее часто и написать 1 или несколько азов
Конкретно для didTap можно добавить selectableItem протокол и оно там заработает, но надо будет самому добавить ивент из протокола. Я правильно понял что ты об этом?

2020-10-13 10:26 UTC, NullIsOne commented on ROADMAP.md
> +- Сократить время на написание шаблонного кода. Много времени уходит на написание однотипных генераторов. Необходимо посмотреть какие генераторы пишутся наиболее часто и написать 1 или несколько азов
В selectableItem 
`var didSelectEvent: BaseEvent<Void>` а надо бывает например `Closure<Bool>` 

Нашёл пример в проекте
```
final class MyServiceMoreTableCellGenerator: SelectableItem, FoldableItem {

    // MARK: - SelectableItem

    var didSelectEvent = BaseEvent<Void>()
    var isNeedDeselect = true

    // MARK: - FoldableItem

    var didFoldEvent = BaseEvent<Bool>()
    var isExpanded = false
    var childGenerators: [TableCellGenerator] = []
}
```
Шаблонный код. Можно написать под него `BaseFoldableCellGenerator`, а можно расширить композицией.
Таких ситуаций будет много, поэтому мне кажется, что идти к нескольким базовым генераторам менее предпочтительно, чем отталкиваться от одного.
В этом мысль была.

2020-10-13 10:51 UTC, LastSprint commented on ROADMAP.md
> +- Сократить время на написание шаблонного кода. Много времени уходит на написание однотипных генераторов. Необходимо посмотреть какие генераторы пишутся наиболее часто и написать 1 или несколько азов
А как это должно выглядеть? Ну, то есть, тебе в любом случае нужно добавлять какое-то события в сам генератор, в смысле свойство дописывать. Здесь в примере оба протокола `SelectableItem` и `FoldableItem` нужны для того чтоб связать методы внутри адаптера с генератором. То есть они на самом деле включат определенное поведение в адаптере, а не в генераторе.  

А засовывать логику из разворачивающегося генератора в базовый кажется вообще неправильным, потому что это на самом деле контейнер для генераторов, по сути фасад. Но это наверное просто пример не очень удачный. Можешь по-быстрому накидать Proof of Concept с несколькими аспектами которые можно добавить композиций, чтоб было совсем понятно

2020-10-13 12:18 UTC, NullIsOne commented on ROADMAP.md
> +- Сократить время на написание шаблонного кода. Много времени уходит на написание однотипных генераторов. Необходимо посмотреть какие генераторы пишутся наиболее часто и написать 1 или несколько азов
Да, с Foldable немного не тот пример, попробуем другой в Proof of Concept.

Тут поможет только магия генериков 
```
/// Расширяем Configurable знакомыми Input Output
public protocol Configurable where Self: UIView {
    associatedtype Input
    associatedtype Output
    associatedtype Model
    
    var input: Input? { get set }
    var output: Output? { get set }

    func configure(with model: Model)
    
}

/// Шапка базового генератора
public class BaseCellGenerator<Cell: Configurable>: SelectableItem where Cell: UITableViewCell {

    // MARK: - Properties

    public var didSelectEvent = BaseEvent<Void>()

    public var input: Cell.Input?
    public var output: Cell.Output?

    // MARK: - Private properties

    private let model: Cell.Model
    private let registerClass: Bool
/// ...

/// Ячейка, допустим имеет текстовое поле и галку
extension SomeTableCell: Configurable {
    /// инпут будет только у текста, там допустим 1 метод validate
    typealias Input = TextFieldInputProtocol

    /// композиция output-ов
    typealias Output = TextFieldOutputProtocol & CheckboxOutputProtocol

    var input: Input?
    var output: Output?
  
    func configure(with model: String) {
        titleLabel.text = model
        configureAppearance()
    }
}

/// Таким образом имеем множество комбинаций
/// Необходимость в новом input или output появляется с добавлением вьюх в ячейку

/// по применению
gen = BaseCellGenerator<SomeTableCell>()

gen.input?.validate()

gen.output?.onTextChanged = { 
/// ...
}

gen.output?.onChecked = {
  /// ...
}

```

2020-10-14 13:13 UTC, LastSprint commented on ROADMAP.md
> +- Сократить время на написание шаблонного кода. Много времени уходит на написание однотипных генераторов. Необходимо посмотреть какие генераторы пишутся наиболее часто и написать 1 или несколько азов
Понял идею. Выглядит неплохо, но как будто что-то не так с этим решением, но у меня нет ничего конкретного, добавим такой генератор, выглядит в любом случае хорошо! Спасибо

2020-10-15 09:47 UTC, Alelenka requested changes

2020-10-15 09:47 UTC, Alelenka commented on ROADMAP.md
> +- Добавить возможность переиспользования конкретныx аспектов поведения. Например, если уже есть реализация сворчаивания, то можно взять роавно этот кусок логики и использвоать его в другом адаптере.
```suggestion
- Добавить возможность переиспользования конкретныx аспектов поведения. Например, если уже есть реализация сворачивания, то можно взять ровно этот кусок логики и использовать его в другом адаптере. 
```

2020-10-15 09:47 UTC, Alelenka commented on ROADMAP.md
> +- Сократить время на написание шаблонного кода. Много времени уходит на написание однотипных генераторов. Необходимо посмотреть какие генераторы пишутся наиболее часто и написать 1 или несколько азов
```suggestion
- Сократить время на написание шаблонного кода. Много времени уходит на написание однотипных генераторов. Необходимо посмотреть какие генераторы пишутся наиболее часто и написать 1 или несколько базовых генераторов.
```

2020-10-15 09:47 UTC, Alelenka commented on ROADMAP.md
> -- Добавить PTR и спинер из-коробки. [#32](https://github.com/surfstudio/ReactiveDataDisplayManager/issues/32)
Пункт удален - так как есть issue или актуальность пропала? Или может быть вынесено из данной библиотеки?

2020-10-22 13:25 UTC, LastSprint commented on ROADMAP.md
> -- Добавить PTR и спинер из-коробки. [#32](https://github.com/surfstudio/ReactiveDataDisplayManager/issues/32)
Точно, надо вернуть

2020-10-23 06:32 UTC, Alelenka approved these changes

2020-10-23 17:47 UTC, merged