Add table and scroll events
surfstudio/ReactiveDataDisplayManager pull request #77
Opened 2021-01-29 12:50 UTC by eysnerSurf

## Что сделано?

Добавлены 
1. scrollEvent и tableEvent
2. плагины
- TableScrollablePlugin
- TableHeaderVisiblePlugin
- TableDirectionScrollablePlugin

## Как протестировать?

Добавить в example необходимые плагины

2021-01-29 14:06 UTC, NullIsOne requested changes
- Возможно убрать UIScrollView из параметров ивента
- Прокачать комментарии
- см комментарии

2021-01-29 14:06 UTC, NullIsOne commented on Source/REFACTORING/Table/Plugins/TableHeaderVisiblePlugin.swift
> +    public init(action: @escaping (Int) -> Void) {
Пример хорошего плагина
Описания не хватает

Посмотри как в ManualTableStateManager у методов комментируется и назначение параметров в методах
По такому же паттерну тут надо пояснить что получим в closure в качестве Int номер секции (уточнить)

2021-01-29 14:48 UTC, eysnerSurf commented on Source/REFACTORING/Table/Plugins/TableScrollablePlugin.swift
> +            didScroll.invoke(with: scrollView)
Вообще наверное стоит отказаться от прокидывания scrollView и отдавать tableView. От того, что мы скастим до UIScrollView мы ничего не выиграем, т.к он и так суперкласс таблицы

2021-01-29 15:09 UTC, eysnerSurf commented on Source/REFACTORING/Table/Plugins/TableScrollablePlugin.swift
> +public class TableScrollablePlugin: PluginAction<ScrollEvent, BaseTableStateManager> {
Поменял на твой вариант

2021-01-29 15:09 UTC, eysnerSurf commented on Source/REFACTORING/Table/Plugins/TableHeaderVisiblePlugin.swift
> +    public init(action: @escaping (Int) -> Void) {
Добавил документацию

2021-01-29 15:09 UTC, eysnerSurf commented on Source/REFACTORING/Table/Delegate/BaseTableDelegate.swift
> +    open func scrollViewDidScroll(_ scrollView: UIScrollView) {
Поправил

2021-02-01 07:01 UTC, eysnerSurf commented on Source/REFACTORING/Table/Plugins/TableDirectionScrollablePlugin.swift
> +                userDidScrolled = true
Флаг убрал, вместо двух эвентов (scrollUp, scrollDown) теперь один, который возвращает направление прокрутки

2021-02-01 09:28 UTC, NullIsOne approved these changes

2021-02-01 09:29 UTC, merged