Add prefetching plugins
surfstudio/ReactiveDataDisplayManager pull request #78
Opened 2021-02-02 05:59 UTC by eysnerSurf

## Что сделано?

* Добавлены два плагина для префетчинга таблицы
1. TablePrefetchProxyPlugin - просто проксирует эвенты префетчинга
2. TablePreheaterablePlugin - добавился preheater, который занимается загрузкой и кэшированием
* Сделал пример использования

## На что обратить внимание?

Генератор хранит id реквеста - это возможно не лучший вариант, можно было бы передавать массив реквестов или также их id в плагин, но тут несколько проблем может возникнуть:
1) нужно было бы их как-то добавлять/удалять, в общем контролировать что реквест нужен (допустим ячейка удалилась и больше не нужно для нее кэшировать данные)
2) если передавать сами реквесты, то можно столкнуться с проблемой приведениях их к одному протоколу

## Как протестировать?

- нажать на любую ячейку таблицы

2021-02-02 10:40 UTC, NullIsOne requested changes
- см. придирки к наименованиям
- верстку из кода убрать чтобы не отвлекала
- добавить контроллер с картинками, но без включенного префетчинга
- генерализовать протокол префетчера

2021-02-02 10:40 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
> +        navigationController?.pushViewController(controller, animated: true)
Навигационный код отвлекает от самой цели примера
Давай попробуем его минимизировать
Например указать маршруты в storyboard а тут просто дергать нужную segue
Параметры между контроллерами мы передавать не будем, так что это не должно сильно усложнить расширение примеров

Смысл в том, чтобы в swift коде проекта был только код работы с самой библиотекой и меньше сервисного кода. Потому что библиотека у нас служит для конкретных целей

2021-02-02 10:40 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
> +        navigationController?.isNavigationBarHidden = true
Это лишнее
Ui не вылизываем пока. Пусть будет небольшой лаг при переходе - не страшно.

2021-02-02 10:40 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/PrefetchingTableViewController/ImageTableGenerator.swift
> +//
Кажется имеет смысл собирать ячейки в одной папке
Например `Table/Cells/Generators/ImageTableGeneraor`
Так проще будет искать

2021-02-02 10:40 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/PrefetchingTableViewController/PrefetchingTableViewController.swift
> +        NSLayoutConstraint.activate([
Верстку надо убрать в xib или storyboard
Наша библиотека не про верстку, поэтому убираем ее из swift-кода, чтобы в контроллерах было как можно меньше отвлекающего кода

2021-02-02 10:40 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/PrefetchingTableViewController/PrefetchingTableViewController.swift
> +        let stringImageUrl = "https://picsum.photos/id/\(Int.random(in: 50...500))/400/300"
Разница между коллекцией с префетчингом и без будет более наглядна если увеличить разрешение.
Поэксперементируй с размерами
На сервисе даже fhd можно https://i.picsum.photos/id/0/1920/1080.jpg?hmac=AdedhkCl_iciZ1DnZ92rgACLbgMZOBtvON6ehVr1c50 
Но возможно с таким качеством даже префетчинг не будет помогать)

2021-02-02 10:40 UTC, NullIsOne commented on Source/REFACTORING/Table/Plugins/TablePreheaterablePlugin.swift
> +public protocol RddmPreheater {
```suggestion
public protocol ContentPrefetching {

    associatedtype Content: Hashable

    func startPrefetching(for content: [Content])
    func cancelPrefetching(for content: [Content])
}
```

2021-02-02 10:40 UTC, NullIsOne commented on Source/REFACTORING/Table/Plugins/TablePreheaterablePlugin.swift
> +public protocol RddmPreheater {
`Preheater` vs `Prefetching`
Первое исходит из Nuke. Наименование в терминах сторонней библиотеки загрузки картинок.
Второе - термин из UIKit для датасорса таблиц или коллекции.

Я за второе.

`ContentPrefetching` чтобы абстрагироваться от типа подгружаемого контента.
`Content: Hashable` опционально. Но суть в том, что реквесты или url уникальны и в более сложных реализациях может потребоваться соотвествие `Hashable` 

Добро пожаловать в мир генериков)

2021-02-02 10:40 UTC, NullIsOne commented on Source/REFACTORING/Table/Plugins/TablePreheaterablePlugin.swift
> +    public var prefetchEvent = BaseEvent<[IndexPath]>()
Выглядит так, будто он повторяет в себе еще и логику `TablePrefetchProxyPlugin `

Либо убрать проксирование отсюда, либо наследоваться

2021-02-02 10:40 UTC, NullIsOne commented on Source/REFACTORING/Table/Table+RDDM.swift
> +    public func add(plugin: PluginAction<PrefetchEvent, BaseTableStateManager>) -> TableBuilder<T> {
Можно добавить @available чтобы было доступно только с 10 iOS

2021-02-02 15:22 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
> +                self.openPrefetchingTableViewController()
Добавил второй пример без префетчинга

2021-02-02 15:22 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
> +        navigationController?.pushViewController(controller, animated: true)
Именил на сегвеи

2021-02-02 15:22 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Table/MainTableViewController/MainTableViewController.swift
> +        navigationController?.isNavigationBarHidden = true
Убрал

2021-02-02 15:22 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Table/PrefetchingTableViewController/ImageTableGenerator.swift
> +//
Перенес

2021-02-02 15:22 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Table/PrefetchingTableViewController/PrefetchingTableViewController.swift
> +        NSLayoutConstraint.activate([
Верстку сделал в сториборде

2021-02-02 15:22 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Table/PrefetchingTableViewController/PrefetchingTableViewController.swift
> +        let stringImageUrl = "https://picsum.photos/id/\(Int.random(in: 50...500))/400/300"
Проверял уже разные размеры, оно в принципе и на 400*300 видно разницу из-за того, что бэк видимо долго картинку режет. Повысил до 720p

2021-02-02 15:23 UTC, eysnerSurf commented on Source/REFACTORING/Table/Plugins/TablePreheaterablePlugin.swift
> +public protocol RddmPreheater {
Изменил имя, поправил документацию где нужно, добавил Hashable

2021-02-02 15:23 UTC, eysnerSurf commented on Source/REFACTORING/Table/Plugins/TablePreheaterablePlugin.swift
> +    public var prefetchEvent = BaseEvent<[IndexPath]>()
Удалил эвенты

2021-02-02 15:23 UTC, eysnerSurf commented on Source/REFACTORING/Table/Table+RDDM.swift
> +    public func add(plugin: PluginAction<PrefetchEvent, BaseTableStateManager>) -> TableBuilder<T> {
Добавил

2021-02-04 10:22 UTC, NullIsOne approved these changes

2021-02-04 10:23 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/PrefetchingTableViewController/PrefetchingTableViewController.swift
> +        let stringImageUrl = "https://picsum.photos/id/\(Int.random(in: 50...500))/400/300"
как-то теперь и там и там медленно
видимо кэш переполняется
ну ок, откатим если что

2021-02-04 10:24 UTC, merged