Add example for foldable cell
surfstudio/ReactiveDataDisplayManager pull request #79
Opened 2021-02-03 09:00 UTC by eysnerSurf

## Что сделано?

* Добавил пример для сворачивающейся ячейки
* Поправил краш в плагине TableFoldablePlugin (добавляли генераторы, а потом в перезагружали строки, которые еще не добавили в таблицу)

## Как протестировать?

- нажать на ячейку `table with foldable cell` разводящей таблицы

2021-02-04 10:50 UTC, NullIsOne requested changes
Усложнилось подключение плагина из-за генерика

2021-02-04 10:50 UTC, NullIsOne commented on Source/REFACTORING/Table/Plugins/TableFoldablePlugin.swift
> +                let foldable = generator as? T,
Хм
Куда-то не туда едем

FoldableItem был не привязан к генератору. Разные генераторы наследовались и композицией добавляли возможности - SelectableItem, FoldableItem и тд

Плагин по задумке добавляет поддержку каких-либо ивентов всей таблице. Сочетаний может быть множество. Генераторы могут соответствовать или нет.

Рассмотрим на примере
Если я захочу добавить другой генератор в этой же таблице отличный от FoldableCellGenerator
Допустим он привязан к другой ячейке и отличается индикацией разворота. 
Или childGenerators другого типа, что более вероятно

С твоими изменениями получается что в описанном случае надо будет добавить 2 плагина. Конкретизировать генерик.

Раньше было лучше)
Генерики в этом случае. ни к чему

2021-02-04 10:50 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Table/Cells/Generators/FoldableCellGenerator.swift
> +    var didSelectEvent = BaseEvent<Void>()
А зачем ему обязательно SelectableItem?

2021-02-04 10:50 UTC, NullIsOne commented on Source/Protocols/Protocols.swift
> +// TODO: - Remove FoldableItem and GravityFoldableItem after release 7.0
Не не не
Усложнение миграции
GravityFoldableItem удалим (если такой был)
А FoldableItem пусть остается FoldableItem
без привязки к генератору

2021-02-04 10:54 UTC, NullIsOne commented on Source/REFACTORING/Table/Plugins/TableFoldablePlugin.swift
> +                let foldable = generator as? T,
ps
в случае с перфетчером генерилазиция плагина была оправдана
можешь сравнить эти случаи

2021-02-04 12:01 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Table/Cells/Generators/FoldableCellGenerator.swift
> +    var didSelectEvent = BaseEvent<Void>()
Лишнее, удалил

2021-02-04 12:01 UTC, eysnerSurf commented on Source/REFACTORING/Table/Plugins/TableFoldablePlugin.swift
> +                let foldable = generator as? T,
Да, тут понятно, что генерики добавляли лишний плагин (если необходимо использовать как в твоем примере с 2 разными генераторами), но их добавил из-за того, что у нас существует два практически идентичных протокола `GravityFoldableItem` и `FoldableItem`, но раз мы оставляем только универсальный `FoldableItem`, тогда и генерики не нужны больше

2021-02-04 12:01 UTC, eysnerSurf commented on Source/Protocols/Protocols.swift
> +// TODO: - Remove FoldableItem and GravityFoldableItem after release 7.0
Поправил, отписал по поводу этих протоколов в первом комментарии

2021-02-08 07:54 UTC, NullIsOne approved these changes

2021-02-08 07:55 UTC, merged