Add collection list example
surfstudio/ReactiveDataDisplayManager pull request #84
Opened 2021-02-09 10:23 UTC by Vadim4016

## Чек-лист

- [x] Я проверил, что проект собирается и не падает
- [x] Я проверил, что Example собирается и не падает  

## Что сделано?

- Добавлен разводящий экран для примеров UICollectionView (Класс MainCollectionViewController, выполнен по аналогии с MainTableViewController. В реализации используется таблица, и к Collection отношения не имеет.)
- Выстроенна стукрута папок аналогично примерам UITableView
- Добавлен экран CollectionListViewController с примером интерграции с новым list api. (Табличное представление через UICollectionView)
- Добалена кнопка в NavBar для возможности переключаться между стандартными режимами list api.

## Зачем это сделано?

Одно из задач рефактонга стоит интеграция RDDM с ListApi. 
Сделан базовый пример для наглядности и выявления узких мест. 

## Из минусов: 

- Базовая реализация BaseCollectionDataDisplayManager работает на основе дефолтного Layout и является делегатом UICollectionViewDelegateFlowLayout. 
- Из-за того что нам нужно переопределить базовый Layout, ломается работа с Header. Это происходит из-за того что расчет высоты Header происходит в дефолтной реализации менеджера, а для табличного списка используется внешний layout.

2021-02-09 10:43 UTC, eysnerSurf reviewed
Написал пару предложений

2021-02-09 10:43 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
> +            generator.didSelectEvent += { [weak self] in
Предлагаю вынести в отдельный метод, дальше может раздуваться при добавлении примеров

2021-02-09 10:43 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
> +                }
Возможно не стоит добавлять кейсы там где не нужна проверка версии iOS? Так избавимся от лишнего кода у следующих примеров

```suggestion
                switch model.segueId {
                case .listAppearances:
                    if #available(iOS 14.0, *) {
                        self.performSegue(withIdentifier: model.segueId.rawValue, sender: self.tableView)
                    } else {
                        self.showAlert("Available from 14 IOS")
                    }
                default:
                        self.performSegue(withIdentifier: model.segueId.rawValue, sender: self.tableView)
                }
```

2021-02-09 11:15 UTC, NullIsOne requested changes
Есть некоторые предложения по оформлению
И конфликты показались

По поводу листов в целом хорошо что это всего лишь новый тип лейаута
Минусы покрываемы новым решением: делегат сделаем отдельной сущностью и модификация будет удобной

2021-02-09 11:15 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
> +        case .plain: appearance = .sidebarPlain
На следующую строку после case перенести бы
Справедливо для всех  case

2021-02-09 11:15 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
> +        case .plain: appearance = .sidebarPlain
А вообще давай лучше спрячем отсюда эти свитчи
Чтобы суть быстрее ухватывалась

Типа
```
private extension UICollectionLayoutListConfiguration.Appearance {
   
   var title: String {
       switch self {
           /// заголовок
       }
   }
   
   var next: UICollectionLayoutListConfiguration.Appearance {
       switch self {
           /// следующий тип представления
       }
   }
}
```

2021-02-09 11:15 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
> +    func configureLayoutFlow() {
Example это наша обложка
Давай избавимся от сайдэффектов и сделаем функцию чище
`func configureLayoutFlow(with appearance: UICollectionLayoutListConfiguration.Appearance)`
аналогично и для `func updateBarButtonItem()`

2021-02-09 11:47 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
> +            generator.didSelectEvent += { [weak self] in
Вынес в метод `func openScreen(by segueId: SegueIdentifier)`

2021-02-09 11:47 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/MainCollectionViewController/MainCollectionViewController.swift
> +                }
Исправил

2021-02-09 11:57 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
> +    func configureLayoutFlow() {
Внес правки

2021-02-09 11:57 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
> +        case .plain: appearance = .sidebarPlain
Внес правки

2021-02-09 11:58 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
> +    private func changeListAppearance() {
Точно, скопировал из туториала Apple и незаметил. Внес правки

2021-02-09 12:02 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
> +    private lazy var titles: [String] = ["Item 1", "Item 2", "Item 3", "Item 4"]
```suggestion
    private lazy var titles = ["Item 1", "Item 2", "Item 3", "Item 4"]
```

2021-02-09 12:02 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/Cells/Generators/TitleCollectionListGenerator.swift
> +}
```suggestion

}
```

2021-02-09 12:22 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/CollectionListViewController/CollectionListViewController.swift
> +    private lazy var titles: [String] = ["Item 1", "Item 2", "Item 3", "Item 4"]
Поправил, скопировал из реализации базовой и не заметил.

2021-02-10 03:42 UTC, NullIsOne approved these changes

2021-02-10 03:46 UTC, merged