Add new base approach for collection view
surfstudio/ReactiveDataDisplayManager pull request #87
Opened 2021-02-10 09:09 UTC by Vadim4016

## Что сделано?

- Добавлена реализация RDDM для CollectionView (Events, Plagins, DataSource, Delegate)
- Добавлены базовые события CollectionView
- Добавлен базовый пример конфигурации CollectionView с новым подходом. Называется "Gallery without prefetching".

## Зачем это сделано?

Обновление архитекруты RDDM для CollectionView

## На что обратить внимание?

- Экран с примером работы называется "Gallery without prefetching", возможно стоило бы назвать его по другому, так как цель экран, это показ базовую настройку, а не загурзку картинок.  

- Возможно, стоит добавить показ Header для секции,  или все же отложить эту идею до след. прмером, а этот оставить максимально простым.

## Как протестировать?

- Открыть таб "Collection"
- Выбрать "Gallery without prefetching"

2021-02-10 09:30 UTC, eysnerSurf commented on Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
> +
```suggestion

    // MARK: - Typealias

```

2021-02-10 09:31 UTC, eysnerSurf commented on Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
> +
```suggestion

    // MARK: - Initialization

```

2021-02-10 09:40 UTC, eysnerSurf commented on Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
> +       }
Поехало немного
```suggestion
        guard
            let index = self.sections.index(where: { $0 === header }),
            self.generators.count > index
        else {
            return
        }
```

2021-02-10 10:11 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Collection/ImageCollectionViewController/Cells/ImageCell/ImageCollectionViewCell.swift
> +    // MARK: - UITableViewCell
```suggestion
    // MARK: - UICollectionViewCell
```

2021-02-10 10:12 UTC, eysnerSurf commented on Example/ReactiveDataDisplayManager/Collection/ImageCollectionViewController/Cells/ImageCell/ImageCollectionViewCell.swift
> +
```suggestion

// MARK: - Configurable

```

2021-02-10 10:30 UTC, NullIsOne requested changes
Норм

- Поправить марки
- Убрать ссылки на базовый датасорс и делегат, добавив протоколы

2021-02-10 10:30 UTC, NullIsOne commented on Source/REFACTORING/Collection/DataSource/BaseCollectionDataSource.swift
> +protocol CollectionDataSource: UICollectionViewDataSource {}
Еще не внесли в решение с таблицей, но думаем что ссылаться в билдере на базовый датасорс неправильно
Лучше расширить протокол и в методах билдера использовать его
Для коллекции предлагаю сразу это учесть
Типа такого будет
```
protocol CollectionDataSource: UICollectionViewDataSource, UICollectionViewDataSourcePrefetching {
    var provider: CollectionGeneratorsProvider? { get set }

    var prefetchPlugins: PluginCollection< BaseCollectionPlugin <PrefetchEvent>> { get set }
    var collectionPlugins: PluginCollection< BaseCollectionPlugin <CollectionEvent>> { get set }
}
```

2021-02-10 10:30 UTC, NullIsOne commented on Source/REFACTORING/Collection/DataSource/BaseCollectionDataSource.swift
> +protocol CollectionDataSource: UICollectionViewDataSource {}
И для делегата сразу выделить протокол, чтоб не ссылаться на базу
План тот же

2021-02-10 11:11 UTC, Vadim4016 commented on Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
> +
Внес правки

2021-02-10 11:11 UTC, Vadim4016 commented on Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
> +
Внес правки

2021-02-10 11:11 UTC, Vadim4016 commented on Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
> +       }
Внес правки

2021-02-10 11:12 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/ImageCollectionViewController/Cells/ImageCell/ImageCollectionViewCell.swift
> +    // MARK: - UITableViewCell
Внес правки

2021-02-10 11:12 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/ImageCollectionViewController/Cells/ImageCell/ImageCollectionViewCell.swift
> +
Внес правки

2021-02-10 11:14 UTC, Vadim4016 commented on Source/REFACTORING/Collection/DataSource/BaseCollectionDataSource.swift
> +protocol CollectionDataSource: UICollectionViewDataSource {}
Ушел на CollectionDataSource/CollectionDelegat, но не переделывал пока методы builder, так как в этом случае они будут публичными и потянут за собой другие изменения модификаторов. 

В ветке https://github.com/surfstudio/ReactiveDataDisplayManager/pull/83 идет схожая задача, посмотрю как решится там, и после уже внесу правки в коллекцию, что бы решения были идентичны.

2021-02-10 11:25 UTC, eysnerSurf commented on Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
> +        self.generators.removeAll()
Можно еще сразу лишние `self` убрать, которые остались от старого кода и перешли в `BaseCollectionManager`

2021-02-10 11:26 UTC, eysnerSurf commented on Source/REFACTORING/Collection/Manager/BaseCollectionManager.swift
> +        guard let collection = self.view else { return }
Можно еще сразу лишние `self` убрать, которые остались от старого кода и перешли в `BaseCollectionManager`

2021-02-11 06:44 UTC, NullIsOne commented on Source/REFACTORING/Collection/DataSource/BaseCollectionDataSource.swift
> +protocol CollectionDataSource: UICollectionViewDataSource {}
83 не жди)
возможно diffableDataSource съедет на следующую версию или вообще не будем делать
Так как концепция снапшотов похожа на наш подход к адаптеру из-за чего возникают противоречия

2021-02-11 06:49 UTC, NullIsOne approved these changes

2021-02-11 06:50 UTC, merged