Add sizable cell support
surfstudio/ReactiveDataDisplayManager pull request #91
Opened 2021-02-11 08:53 UTC by Vadim4016

## Чек-лист

- [x] Я проверил, что проект собирается и не падает
- [x] Я проверил, что Example собирается и не падает  
 
## Что сделано?

- Дабавлена поддержка SizableCollectionCellGenerator из старой версии RDDM.
- Добавлен пример использования. Называется "Sizable collection". (Пример основан на вертикальном скролле, и показывает как ячейка с текстом может вытягиваться по высоте, в зависимости от длины текста.)

## Зачем это сделано?

Одной из проблем использвоания RDDM было расширение базового менеджера, для возможности рассчета размера ячейки. 
Проекты на котрых ссылался при работе: 
- РивГош
- Триколор
- Бетховен 

## На что обратить внимание?

1)  Сам по себе SizableCollectionCellGenerator бесполезен без контекста работы layout, и вообще общей задумки. 
Метод Flow делегата вызывает только UICollectionViewFlowLayout, и не  никакой гарантии что кастомный Layout будет использовать эти методы. 
Отсюда получается, что SizableCollectionCellGenerator будет работать 100% только с UICollectionViewFlowLayout, а значит не может считаться полностью абстрактным. Из-за всего этого может возникнуть путаница в использовании этого протокола.

## Как протестировать?

- Открыть таб "Collection"
- Выбрать "Sizable collection"

2021-02-11 10:56 UTC, NullIsOne requested changes
Проверить как работает автоматический расчет высоты ячейки в списках на коллекции
Пример со списком на коллекции делать новым билдером
Попробовать вынести UICollectionViewDelegateFlowLayout отдельным делегатом наследовавшись от базового
Описать недостающие методы

2021-02-11 10:56 UTC, NullIsOne commented on Source/REFACTORING/Collection/Delegate/BaseCollectionDelegate.swift
> +protocol CollectionDelegate: UICollectionViewDelegateFlowLayout {
Хм
Видимо я в задачке написал что надо сделать это частью базы, но это не подошло

В протоколе CollectionDelegate надо оставить protocol CollectionDelegate: UICollectionViewDelegate 

А реализацию поддержки размера перенести в отдельный делегат, который будет реализовывать UICollectionViewDelegateFlowLayout

Получится без копипасты так сделать?

2021-02-11 10:56 UTC, NullIsOne commented on Source/REFACTORING/Collection/Delegate/BaseCollectionDelegate.swift
> +    open func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
кроме этих методов есть ещё optional методы которые надо описать

2021-02-12 09:33 UTC, Vadim4016 commented on Source/REFACTORING/Collection/Delegate/BaseCollectionDelegate.swift
> +protocol CollectionDelegate: UICollectionViewDelegateFlowLayout {
- Вынес в отдельный FlowCollectionDelegate
- Добавил новый flowBuilder
- Поправил пример

2021-02-12 09:38 UTC, Vadim4016 commented on Source/REFACTORING/Collection/Delegate/BaseCollectionDelegate.swift
> +    open func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
Добавил реализацию всех методов. 
Так же добавил поддержку размеров Header из старой реализации.

2021-02-15 03:04 UTC, NullIsOne submitted a review, later dismissed
Норм
Только перед мерджем надо конфликты поправить

2021-02-15 06:22 UTC, eysnerSurf submitted a review, later dismissed

2021-02-16 03:18 UTC, NullIsOne approved these changes

2021-02-16 03:18 UTC, merged