Add foldable cell support
surfstudio/ReactiveDataDisplayManager pull request #92
Opened 2021-02-12 08:56 UTC by Vadim4016

## Чек-лист

- [x] Я проверил, что проект собирается и не падает
- [x] Я проверил, что Example собирается и не падает  
 
## Что сделано?

- Дабавлена поддержка Foldable поведения.
- Добавлен пример использования. Называется "Foldable collection". (Пример основан на вертикальном скролле, и показывает как ячейка с текстом может вытягиваться по высоте, в зависимости от длины текста.) В примере есть 2 типа конфигураци (Grid/Table)
- Добавил новый протокод CollectionFoldableItem. Полная копия FoldableItem, но с поддержкой ячеек для Collection. Теперь FoldableItem, без префикса Table, кажется общим, но это не так.
- По аналогии с таблицей, добавил новый менеджер ManualCollectionManager, с поддержкой вставки.
- Добавил новый плагин "CollectionFoldablePlugin".

## Зачем это сделано?

Добавление эффекта разворачивания ячеек как в таблице.

## На что обратить внимание?

1) Что бы добавить поддержку вставки, создал `ManualCollectionManager`, но так и не понял зачем это было нужно. Возможно, я ошибочно понять задумку. 
2) В плагине `CollectionFoldablePlugin` идет каст (см. подробнее в `CollectionFoldablePlugin`, строка 32 )
 до нужного менеджера! (так же как и в таблице), что очень запутывает поведение, так как мы должны точно значит с какими менеджерами может работать тот или иной плагин. Как вариант решения этого: Вынести manager из `BaseCollectionPlugin` в Generic, что бы убрать абстракцию.  
3) CollectionFoldableItem описывает свое состояние через флаг `isExpanded`, на который опирается плагин  CollectionFoldablePlugin отлавливая событие didSelect. Проблема в том, что работает это корректно только в уже отрисованной таблице, а если у. флаг `isExpanded == false`. 
Если мы хотим сразу показать раскрытую ячейку, то должны сами, в ручную ее открывать и отдавать manager! (см. подробнее в `FoldableCollectionViewController`, строка 116 )

## Найден баг!

Табличная версия сворачивания, не умеет отображать себя в раскрытом состоянии на старте, так же нет поддержки каскадного поведения. 
Если добаить в папку, другую папку с ячейками, то сворачивание первой не свернет дочернюю.

## Как протестировать?

- Открыть таб "Collection"
- Выбрать "Foldable collection"

2021-02-15 03:26 UTC, NullIsOne requested changes
- Поправить визуальную часть примера (при изменении appearanes)
- insert через extension
- есть конфликты

2021-02-15 03:26 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/FoldableCollectionViewController/FoldableCollectionViewController.swift
> +            guard let viewModel = ImageCollectionViewCell.ViewModel.make(for: imageSize) else { continue }
Размер бы при смене appearance подгонять под новое соотношение сторон
Или в самой ячейке поиграть с contentType
Выглядит неаккуратно в примере

2021-02-15 03:26 UTC, NullIsOne commented on Source/REFACTORING/Collection/Manager/ManualCollectionManager.swift
> +public class ManualCollectionManager: BaseCollectionManager {
Можно добавить этот метод базовому просто через extension
Пока у нас CollectionManager один и нет никаких GravityManager - это норм

Проблему с приведением к конкретным типам менеджера в TableFoldablePlugin уже решаем в другой задачке

2021-02-16 03:25 UTC, Vadim4016 commented on Source/REFACTORING/Collection/Manager/ManualCollectionManager.swift
> +public class ManualCollectionManager: BaseCollectionManager {
Удалили ManualManager, его методы вынес в extension.
Так же метод remove вынес в extension, так как он не является методом протокола DataDisplayManager. 
Вспомогательные методы отметил MARK: - Helper, а остальные убрал в private extension, так как теперь никто кроме BaseManager их не использует.

2021-02-16 04:15 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/FoldableCollectionViewController/FoldableCollectionViewController.swift
> +            guard let viewModel = ImageCollectionViewCell.ViewModel.make(for: imageSize) else { continue }
Согласен.  
Это происходит из-за того что мы подгружаем картинку под размер 100x100, а прим изменении layout, не перезагружается контент, а только одновляется под новый размер. 

Я вижу несколько вариантов решения: 
1) Отказаться от картинок вообще (но тогда получится просто серые фигиры)
2) Задать стандартный размер, подходящий для всех layout. (то как это сделано в таблице. Загружаем большую картинку, хотя она не нужна такого размера.)
3) При изменении layout загружать картинку другого размера.

Сейчас я внес изменения под 2-ю версию. 
Минусы: Картинка загружается большего размера, а значит ждать ее чуть дольше.
Плюсы: Не усложнаяется код тем что нам нужно дописывать логику перезагрузки картинки под другой размер. 

Возможно, стоит вооще отказаться от картинок в этом примере, тогда код получится максимально простым.

2021-02-16 05:43 UTC, NullIsOne approved these changes
Замечания исправлены
Но конфликты остались

2021-02-16 05:43 UTC, NullIsOne commented on Example/ReactiveDataDisplayManager/Collection/FoldableCollectionViewController/FoldableCollectionViewController.swift
> +            guard let viewModel = ImageCollectionViewCell.ViewModel.make(for: imageSize) else { continue }
2й вариант норм

Чаще всего все-таки на проектах именно такая ситуация. Бэк возвращает один конкретный размер, а мы его отображаем.

Картинки не передают суть разворачивания, но о том чем их заменить, чтобы не было серых квадратов - надо подумать.
Раз уж ты теперь не с нами, сделаем это отдельной задачкой

2021-02-16 10:34 UTC, eysnerSurf submitted a review, later dismissed

2021-02-17 06:25 UTC, Vadim4016 commented on Example/ReactiveDataDisplayManager/Collection/FoldableCollectionViewController/FoldableCollectionViewController.swift
> +            guard let viewModel = ImageCollectionViewCell.ViewModel.make(for: imageSize) else { continue }
Обновил ПР, поправил конфликты.

2021-02-17 06:27 UTC, NullIsOne approved these changes

2021-02-17 06:28 UTC, merged